// Auto-extracted from AIKeysSettings.tsx to avoid dragging the entire
// 856-LOC settings panel (React, supabase client, lucide icons, toast)
// into every chunk that only needs to read the provider catalog.
// Pure data — safe to import from anywhere with zero side-effects.

export interface ProviderConfig {
  id: string;
  name: string;
  icon: string;
  placeholder: string;
  helpUrl: string;
  helpText: string;
  /** Country of origin — drives the country filter in Settings. */
  country: string;
  models: { id: string; name: string; description: string; /** Model can read image input. */ vision?: boolean }[];
  /** Platform-hosted provider — no user API key required. Aureon-managed. */
  isPlatform?: boolean;
  /** Optional note shown under platform providers (e.g. subscription gating). */
  platformNote?: string;
}

export const AI_PROVIDERS: ProviderConfig[] = [
  // ───────────────────────── ON THIS DEVICE ─────────────────────────
  {
    id: "ollama",
    name: "Ollama (local)",
    icon: "◇",
    country: "This device",
    placeholder: "no key needed — type: local",
    helpUrl: "https://ollama.com/download",
    helpText: "Runs on this machine at localhost:11434. Start it with OLLAMA_ORIGINS=* so the browser may call it.",
    models: [
      { id: "llama3.2", name: "Llama 3.2", description: "Small, fast, local" },
      { id: "llama3.1:8b", name: "Llama 3.1 8B", description: "Balanced local model" },
      { id: "qwen2.5:7b", name: "Qwen 2.5 7B", description: "Strong multilingual local model" },
      { id: "mistral", name: "Mistral 7B", description: "Fast local model" },
      { id: "deepseek-r1:8b", name: "DeepSeek R1 8B", description: "Local reasoning model" },
      { id: "llava", name: "LLaVA", description: "Local vision model", vision: true },
    ],
  },
  {
    id: "lmstudio",
    name: "LM Studio (local)",
    icon: "◇",
    country: "This device",
    placeholder: "no key needed — type: local",
    helpUrl: "https://lmstudio.ai",
    helpText: "Runs on this machine at localhost:1234. Enable the local server and CORS in LM Studio.",
    models: [{ id: "local-model", name: "Loaded model", description: "Whatever model LM Studio has loaded" }],
  },
  {
    id: "groq",
    name: "Groq",
    icon: "◆",
    country: "United States",
    placeholder: "gsk_...",
    helpUrl: "https://console.groq.com/keys",
    helpText: "Get your API key from the Groq console",
    models: [
      { id: "llama-3.3-70b-versatile", name: "Llama 3.3 70B", description: "Fast open-weight flagship" },
      { id: "llama-3.1-8b-instant", name: "Llama 3.1 8B", description: "Instant, cheap" },
      { id: "qwen/qwen3-32b", name: "Qwen3 32B", description: "Strong reasoning" },
    ],
  },

  // ───────────────────────── UNITED STATES ─────────────────────────
  {
    id: "google",
    name: "Google AI (Gemini)",
    icon: "◈",
    country: "United States",
    placeholder: "AIzaSy...",
    helpUrl: "https://aistudio.google.com/app/apikey",
    helpText: "Get your API key from Google AI Studio",
    models: [
      { id: "gemini-3-pro-preview", name: "Gemini 3 Pro", description: "Newest — frontier reasoning, 1M context" },
      { id: "gemini-3-flash-preview", name: "Gemini 3 Flash", description: "Next-gen flash, balanced speed + capability" },
      { id: "gemini-2.5-pro", name: "Gemini 2.5 Pro", description: "Strong reasoning + multimodal" },
      { id: "gemini-2.5-flash", name: "Gemini 2.5 Flash", description: "Fast, balanced performance" },
      { id: "gemini-1.5-pro", name: "Gemini 1.5 Pro", description: "Legacy — 2M context" },
      { id: "gemini-1.0-pro", name: "Gemini 1.0 Pro", description: "Oldest available — original Gemini API" },
    ],
  },
  {
    id: "openai",
    name: "OpenAI",
    icon: "◉",
    country: "United States",
    placeholder: "sk-...",
    helpUrl: "https://platform.openai.com/api-keys",
    helpText: "Get your API key from OpenAI Platform",
    models: [
      { id: "gpt-5.5", name: "GPT-5.5", description: "Newest flagship, frontier reasoning" },
      { id: "gpt-5", name: "GPT-5", description: "All-rounder, multimodal" },
      { id: "gpt-5-mini", name: "GPT-5 Mini", description: "Cost-efficient strong performance" },
      { id: "gpt-4.1", name: "GPT-4.1", description: "Best 4.x coding model" },
      { id: "gpt-4o", name: "GPT-4o", description: "Legacy omni multimodal" },
      { id: "gpt-3.5-turbo", name: "GPT-3.5 Turbo", description: "Oldest available — classic ChatGPT API" },
    ],
  },
  {
    id: "anthropic",
    name: "Anthropic (Claude)",
    icon: "◎",
    country: "United States",
    placeholder: "sk-ant-...",
    helpUrl: "https://console.anthropic.com/settings/keys",
    helpText: "Get your API key from Anthropic Console",
    models: [
      { id: "claude-opus-4-5", name: "Claude Opus 4.5", description: "Newest flagship, smartest Claude" },
      { id: "claude-sonnet-4-5", name: "Claude Sonnet 4.5", description: "Best agentic + coding, 1M context" },
      { id: "claude-haiku-4-5", name: "Claude Haiku 4.5", description: "Fastest 4.x" },
      { id: "claude-3-5-sonnet", name: "Claude 3.5 Sonnet", description: "Legacy" },
      { id: "claude-2.1", name: "Claude 2.1", description: "Oldest available — 200K context legacy" },
    ],
  },
  {
    id: "xai",
    name: "xAI (Grok)",
    icon: "◌",
    country: "United States",
    placeholder: "xai-...",
    helpUrl: "https://console.x.ai/",
    helpText: "Get your API key from xAI Console",
    models: [
      { id: "grok-5", name: "Grok 5", description: "Newest frontier reasoning + real-time" },
      { id: "grok-4-1", name: "Grok 4.1", description: "Refined reasoning" },
      { id: "grok-3", name: "Grok 3", description: "Reliable mid-tier" },
      { id: "grok-2", name: "Grok 2", description: "Legacy" },
      { id: "grok-beta", name: "Grok Beta", description: "Oldest available — original Grok API" },
    ],
  },
  {
    id: "meta",
    name: "Meta AI (Llama)",
    icon: "◇",
    country: "United States",
    placeholder: "Your Llama API key...",
    helpUrl: "https://llama.developer.meta.com/",
    helpText: "Access via Llama API, Together, or Groq",
    models: [
      { id: "llama-4-behemoth", name: "Llama 4 Behemoth", description: "Newest 2T param frontier" },
      { id: "llama-4-maverick", name: "Llama 4 Maverick", description: "MoE flagship multimodal" },
      { id: "llama-3.3-70b", name: "Llama 3.3 70B", description: "Strong open-weight" },
      { id: "llama-3.1-405b", name: "Llama 3.1 405B", description: "Largest classic Llama" },
      { id: "llama-2-70b", name: "Llama 2 70B", description: "Oldest available — original open Llama API" },
    ],
  },
  {
    id: "perplexity",
    name: "Perplexity AI",
    icon: "◈",
    country: "United States",
    placeholder: "pplx-...",
    helpUrl: "https://www.perplexity.ai/settings/api",
    helpText: "Get your API key from Perplexity Settings",
    models: [
      { id: "sonar-pro", name: "Sonar Pro", description: "Newest multi-step search reasoning" },
      { id: "sonar-reasoning-pro", name: "Sonar Reasoning Pro", description: "R1-based reasoning + search" },
      { id: "sonar", name: "Sonar", description: "Fast search-grounded" },
      { id: "pplx-7b-online", name: "PPLX 7B Online", description: "Oldest available — legacy online model" },
    ],
  },
  {
    id: "venice",
    name: "Venice AI",
    icon: "◆",
    country: "United States",
    placeholder: "Your Venice API key...",
    helpUrl: "https://venice.ai/",
    helpText: "Uncensored, no-logging API",
    models: [
      // ── text + vision (reads images) ──
      { id: "gemini-3-6-flash", name: "Gemini 3.6 Flash", description: "1M context · reasoning · tools · reads images", vision: true },
      { id: "gemini-3-7-flash", name: "Gemini 3.7 Flash", description: "1M context · reasoning · tools · reads images", vision: true },
      { id: "gemini-3-8-flash", name: "Gemini 3.8 Flash", description: "1M context · reasoning · tools · reads images", vision: true },
      { id: "gemini-3-5-flash-lite", name: "Gemini 3.5 Flash-Lite", description: "1M context · reasoning · tools · reads images", vision: true },
      { id: "z-ai-glm-5-3-flash", name: "GLM 5.3 Flash", description: "1.04858M context · reasoning · tools · reads images", vision: true },
      { id: "z-ai-glm-5v-turbo", name: "GLM 5V Turbo", description: "200K context · reasoning · tools · reads images", vision: true },
      { id: "venice-uncensored-1-2", name: "Venice Uncensored 1.2", description: "128K context · tools · reads images", vision: true },
      { id: "venice-uncensored-role-play", name: "Venice Role Play Uncensored", description: "128K context · tools · reads images", vision: true },
      { id: "qwen-3-8-max", name: "Qwen 3.8 Max", description: "1M context · reasoning · tools · reads images", vision: true },
      { id: "qwen-3-8-27b", name: "Qwen 3.8 27B", description: "262K context · reasoning · tools · reads images", vision: true },
      { id: "qwen-3-8-flash", name: "Qwen 3.8 Flash", description: "1M context · reasoning · tools · reads images", vision: true },
      { id: "qwen-3-7-max", name: "Qwen 3.7 Max", description: "1M context · reasoning · tools · reads images", vision: true },
      { id: "qwen-3-7-plus", name: "Qwen 3.7 Plus", description: "1M context · reasoning · tools · reads images", vision: true },
      { id: "qwen-3-6-plus", name: "Qwen 3.6 Plus Uncensored", description: "1M context · reasoning · tools · reads images", vision: true },
      { id: "qwen3-6-27b", name: "Qwen 3.6 27B", description: "256K context · reasoning · tools · reads images", vision: true },
      { id: "qwen3-6-35b-a3b", name: "Qwen 3.6 35B A3B", description: "256K context · reasoning · tools · reads images", vision: true },
      { id: "qwen3-5-9b", name: "Qwen 3.5 9B", description: "256K context · reasoning · tools · reads images", vision: true },
      { id: "qwen3-5-397b-a17b", name: "Qwen 3.5 397B", description: "128K context · reasoning · tools · reads images", vision: true },
      { id: "qwen3-5-35b-a3b", name: "Qwen 3.5 35B A3B", description: "256K context · reasoning · tools · reads images", vision: true },
      { id: "qwen3-vl-235b-a22b", name: "Qwen3 VL 235B", description: "128K context · tools · reads images", vision: true },
      { id: "google-gemma-4-26b-a4b-it", name: "Google Gemma 4 26B A4B Instruct", description: "256K context · reasoning · tools · reads images", vision: true },
      { id: "google-gemma-4-31b-it", name: "Google Gemma 4 31B Instruct", description: "256K context · reasoning · tools · reads images", vision: true },
      { id: "gemma-4-uncensored", name: "Gemma 4 Uncensored", description: "256K context · tools · reads images", vision: true },
      { id: "google-gemma-3-27b-it", name: "Google Gemma 3 27B Instruct", description: "198K context · tools · reads images", vision: true },
      { id: "grok-4-3", name: "Grok 4.3", description: "1M context · reasoning · tools · reads images", vision: true },
      { id: "grok-4-5", name: "Grok 4.5", description: "500K context · reasoning · tools · reads images", vision: true },
      { id: "grok-4-6", name: "Grok 4.6", description: "500K context · reasoning · tools · reads images", vision: true },
      { id: "grok-4-20", name: "Grok 4.20", description: "2M context · reasoning · tools · reads images", vision: true },
      { id: "grok-4-20-multi-agent", name: "Grok 4.20 Multi-Agent", description: "2M context · reasoning · reads images", vision: true },
      { id: "grok-build-0-1", name: "Grok Build 0.1", description: "256K context · reasoning · tools · reads images", vision: true },
      { id: "mistral-small-3-2-24b-instruct", name: "Mistral Small 3.2 24B Instruct", description: "256K context · tools · reads images", vision: true },
      { id: "mistral-small-2603", name: "Mistral Small 4", description: "256K context · reasoning · tools · reads images", vision: true },
      { id: "gemini-3-1-pro-preview", name: "Gemini 3.1 Pro Preview", description: "1M context · reasoning · tools · reads images", vision: true },
      { id: "gemini-3-5-flash", name: "Gemini 3.5 Flash", description: "1M context · reasoning · tools · reads images", vision: true },
      { id: "gemini-3-flash-preview", name: "Gemini 3 Flash Preview", description: "256K context · reasoning · tools · reads images", vision: true },
      { id: "claude-fable-5", name: "Claude Fable 5", description: "1M context · reasoning · tools · reads images", vision: true },
      { id: "claude-fable-5-1", name: "Claude Fable 5.1", description: "1M context · reasoning · tools · reads images", vision: true },
      { id: "claude-opus-5", name: "Claude Opus 5", description: "1M context · reasoning · tools · reads images", vision: true },
      { id: "claude-opus-5-fast", name: "Claude Opus 5 Fast", description: "1M context · reasoning · tools · reads images", vision: true },
      { id: "claude-opus-4-8", name: "Claude Opus 4.8", description: "1M context · reasoning · tools · reads images", vision: true },
      { id: "claude-opus-4-8-fast", name: "Claude Opus 4.8 Fast", description: "1M context · reasoning · tools · reads images", vision: true },
      { id: "claude-opus-4-7", name: "Claude Opus 4.7", description: "1M context · reasoning · tools · reads images", vision: true },
      { id: "claude-opus-4-6", name: "Claude Opus 4.6", description: "1M context · reasoning · tools · reads images", vision: true },
      { id: "claude-opus-4-5", name: "Claude Opus 4.5", description: "198K context · reasoning · tools · reads images", vision: true },
      { id: "claude-sonnet-5", name: "Claude Sonnet 5", description: "1M context · reasoning · tools · reads images", vision: true },
      { id: "claude-sonnet-4-6", name: "Claude Sonnet 4.6", description: "1M context · reasoning · tools · reads images", vision: true },
      { id: "claude-sonnet-4-5", name: "Claude Sonnet 4.5", description: "198K context · reasoning · tools · reads images", vision: true },
      { id: "kimi-k2-6", name: "Kimi K2.6", description: "256K context · reasoning · tools · reads images", vision: true },
      { id: "kimi-k2-7-code", name: "Kimi K2.7 Code", description: "256K context · reasoning · tools · reads images", vision: true },
      { id: "kimi-k2-5", name: "Kimi K2.5", description: "256K context · reasoning · tools · reads images", vision: true },
      { id: "kimi-k3", name: "Kimi K3", description: "1M context · reasoning · tools · reads images", vision: true },
      { id: "inkling", name: "Inkling", description: "524K context · reasoning · tools · reads images", vision: true },
      { id: "xiaomi-mimo-v2-5", name: "MiMo-V2.5", description: "1M context · reasoning · tools · reads images", vision: true },
      { id: "deepseek-v4-1-flash", name: "DeepSeek V4.1 Flash", description: "1M context · reasoning · tools · reads images", vision: true },
      { id: "seed-2-1-turbo", name: "Seed 2.1 Turbo", description: "256K context · reasoning · tools · reads images", vision: true },
      { id: "kimi-k3-fast-api", name: "Kimi K3 Fast", description: "1M context · reasoning · tools · reads images", vision: true },
      { id: "openai-gpt-53-codex", name: "GPT-5.3 Codex", description: "400K context · reasoning · tools · reads images", vision: true },
      { id: "openai-gpt-54", name: "GPT-5.4", description: "1M context · reasoning · tools · reads images", vision: true },
      { id: "openai-gpt-54-pro", name: "GPT-5.4 Pro", description: "1M context · reasoning · tools · reads images", vision: true },
      { id: "openai-gpt-54-mini", name: "GPT-5.4 Mini", description: "400K context · reasoning · tools · reads images", vision: true },
      { id: "openai-gpt-55", name: "GPT-5.5", description: "1M context · reasoning · tools · reads images", vision: true },
      { id: "openai-gpt-55-pro", name: "GPT-5.5 Pro", description: "1M context · reasoning · tools · reads images", vision: true },
      { id: "openai-gpt-56-luna", name: "GPT-5.6 Luna", description: "1M context · reasoning · tools · reads images", vision: true },
      { id: "openai-gpt-56-luna-pro", name: "GPT-5.6 Luna Pro", description: "1M context · reasoning · tools · reads images", vision: true },
      { id: "openai-gpt-56-terra", name: "GPT-5.6 Terra", description: "1M context · reasoning · tools · reads images", vision: true },
      { id: "openai-gpt-56-terra-pro", name: "GPT-5.6 Terra Pro", description: "1M context · reasoning · tools · reads images", vision: true },
      { id: "openai-gpt-56-sol", name: "GPT-5.6 Sol", description: "1M context · reasoning · tools · reads images", vision: true },
      { id: "openai-gpt-56-sol-pro", name: "GPT-5.6 Sol Pro", description: "1M context · reasoning · tools · reads images", vision: true },
      { id: "openai-gpt-6-astra", name: "GPT-6 Astra", description: "1.05M context · reasoning · tools · reads images", vision: true },
      { id: "openai-gpt-6-astra-pro", name: "GPT-6 Astra Pro", description: "1.05M context · reasoning · tools · reads images", vision: true },
      { id: "openai-gpt-4o-2024-11-20", name: "GPT-4o", description: "128K context · tools · reads images", vision: true },
      { id: "openai-gpt-4o-mini-2024-07-18", name: "GPT-4o Mini", description: "128K context · tools · reads images", vision: true },
      { id: "minimax-m3-preview", name: "MiniMax M3 Preview", description: "524K context · reasoning · tools · reads images", vision: true },
      { id: "e2ee-kimi-k3-p", name: "Kimi K3", description: "1M context · reasoning · tools · reads images", vision: true },
      { id: "e2ee-qwen3-vl-30b-a3b-p", name: "Qwen3 VL 30B A3B", description: "128K context · tools · reads images", vision: true },
      { id: "e2ee-glm-5-3-flash", name: "GLM 5.3 Flash", description: "1M context · reasoning · tools · reads images", vision: true },
      { id: "e2ee-qwen3-8-27b", name: "Qwen 3.8 27B", description: "262K context · reasoning · tools · reads images", vision: true },
      { id: "e2ee-kimi-k2-6", name: "Kimi K2.6", description: "262K context · reasoning · tools · reads images", vision: true },
      // ── text only ──
      { id: "z-ai-glm-5-3", name: "GLM 5.3", description: "1M context · reasoning · tools" },
      { id: "zai-org-glm-5-2", name: "GLM 5.2", description: "1M context · reasoning · tools" },
      { id: "zai-org-glm-5-1", name: "GLM 5.1", description: "200K context · reasoning · tools" },
      { id: "zai-org-glm-5", name: "GLM 5", description: "198K context · reasoning · tools" },
      { id: "z-ai-glm-5-turbo", name: "GLM 5 Turbo", description: "200K context · reasoning · tools" },
      { id: "olafangensan-glm-4.7-flash-heretic", name: "GLM 4.7 Flash Heretic", description: "200K context · reasoning · tools" },
      { id: "zai-org-glm-4.7-flash", name: "GLM 4.7 Flash", description: "128K context · reasoning · tools" },
      { id: "zai-org-glm-4.6", name: "GLM 4.6", description: "198K context · reasoning · tools" },
      { id: "zai-org-glm-4.7", name: "GLM 4.7", description: "198K context · reasoning · tools" },
      { id: "qwen-3-8-2-4t-a95b", name: "Qwen 3.8 2.4T", description: "262K context · reasoning · tools" },
      { id: "qwen3-235b-a22b-thinking-2507", name: "Qwen 3 235B A22B Thinking 2507", description: "128K context · reasoning · tools" },
      { id: "qwen3-235b-a22b-instruct-2507", name: "Qwen 3 235B A22B Instruct 2507", description: "128K context · tools" },
      { id: "qwen3-next-80b", name: "Qwen 3 Next 80b", description: "256K context · tools" },
      { id: "qwen3-coder-480b-a35b-instruct-turbo", name: "Qwen 3 Coder 480B Turbo", description: "256K context · tools" },
      { id: "hermes-3-llama-3.1-405b", name: "Hermes 3 Llama 3.1 405b", description: "128K context" },
      { id: "openai-gpt-oss-120b", name: "OpenAI GPT OSS 120B", description: "128K context · reasoning · tools" },
      { id: "deepseek-v4-pro", name: "DeepSeek V4 Pro", description: "1M context · reasoning · tools" },
      { id: "deepseek-v4-flash", name: "DeepSeek V4 Flash 0423", description: "1M context · reasoning · tools" },
      { id: "deepseek-v4-flash-0731", name: "DeepSeek V4 Flash 0731", description: "1M context · reasoning · tools" },
      { id: "deepseek-v3.2", name: "DeepSeek V3.2", description: "160K context · reasoning · tools" },
      { id: "deepseek-v4-pro-0813", name: "DeepSeek V4 Pro 0813", description: "1M context · reasoning · tools" },
      { id: "deepseek-v4-flash-0731-fast", name: "DeepSeek V4 Flash 0731 Fast", description: "1M context · reasoning · tools" },
      { id: "aion-labs-aion-3-0", name: "Aion 3.0", description: "128K context · reasoning · tools" },
      { id: "aion-labs-aion-3-0-mini", name: "Aion 3.0 Mini", description: "128K context · reasoning · tools" },
      { id: "llama-3.2-3b", name: "Llama 3.2 3B", description: "128K context · tools" },
      { id: "llama-3.3-70b", name: "Llama 3.3 70B", description: "128K context · tools" },
      { id: "openai-gpt-52", name: "GPT-5.2", description: "256K context · reasoning · tools" },
      { id: "minimax-m25", name: "MiniMax M2.5", description: "198K context · reasoning · tools" },
      { id: "minimax-m27", name: "MiniMax M2.7", description: "198K context · reasoning · tools" },
      { id: "mercury-2", name: "Mercury 2", description: "128K context · reasoning · tools" },
      { id: "mercury-2-5", name: "Mercury 2.5", description: "260K context · reasoning · tools" },
      { id: "nvidia-nemotron-3-nano-30b-a3b", name: "NVIDIA Nemotron 3 Nano 30B", description: "128K context · tools" },
      { id: "nvidia-nemotron-3-ultra-550b-a55b", name: "NVIDIA Nemotron 3 Ultra", description: "256K context · reasoning · tools" },
      { id: "e2ee-gemma-4-26b-a4b-uncensored-p", name: "Gemma 4 26B A4B Uncensored", description: "64K context" },
      { id: "e2ee-glm-5-2-p", name: "GLM 5.2", description: "524K context · reasoning · tools" },
      { id: "e2ee-glm-5-3-p", name: "GLM 5.3", description: "1M context · reasoning · tools" },
      { id: "e2ee-gpt-oss-120b-p", name: "GPT OSS 120B", description: "128K context · reasoning" },
      { id: "e2ee-qwen-2-5-7b-p", name: "Qwen 2.5 7B", description: "32K context" },
      { id: "e2ee-qwen3-6-35b-a3b", name: "Qwen 3.6 35B A3B FP8", description: "32K context · reasoning · tools" },
      { id: "e2ee-deepseek-v4-flash", name: "DeepSeek V4 Flash", description: "1M context · reasoning · tools" },
    ],
  },
  {
    id: "ibm",
    name: "IBM watsonx (Granite)",
    icon: "◰",
    country: "United States",
    placeholder: "Your watsonx API key...",
    helpUrl: "https://cloud.ibm.com/iam/apikeys",
    helpText: "Get your API key from IBM Cloud",
    models: [
      { id: "granite-3.1-8b-instruct", name: "Granite 3.1 8B", description: "Newest enterprise instruct" },
      { id: "granite-3.0-2b-instruct", name: "Granite 3.0 2B", description: "Compact enterprise" },
      { id: "granite-13b-chat-v2", name: "Granite 13B v2", description: "Oldest available — original Granite chat" },
    ],
  },
  {
    id: "amazon",
    name: "Amazon Bedrock (Nova)",
    icon: "◱",
    country: "United States",
    placeholder: "AWS access key...",
    helpUrl: "https://console.aws.amazon.com/bedrock/",
    helpText: "Configure access in AWS Bedrock console",
    models: [
      { id: "amazon.nova-pro-v1", name: "Nova Pro", description: "Newest multimodal flagship" },
      { id: "amazon.nova-lite-v1", name: "Nova Lite", description: "Fast cost-efficient multimodal" },
      { id: "amazon.nova-micro-v1", name: "Nova Micro", description: "Cheapest text-only" },
      { id: "amazon.titan-text-express-v1", name: "Titan Text Express", description: "Oldest available — original Titan API" },
    ],
  },
  {
    id: "nvidia",
    name: "NVIDIA NIM (Nemotron)",
    icon: "◲",
    country: "United States",
    placeholder: "nvapi-...",
    helpUrl: "https://build.nvidia.com/",
    helpText: "Get your API key from NVIDIA Build",
    models: [
      { id: "nemotron-4-340b-instruct", name: "Nemotron 4 340B", description: "Newest open frontier" },
      { id: "llama-3.1-nemotron-70b", name: "Llama 3.1 Nemotron 70B", description: "Tuned reasoning" },
      { id: "nemotron-3-8b-chat", name: "Nemotron 3 8B", description: "Oldest available — original Nemotron API" },
    ],
  },
  {
    id: "openrouter",
    name: "OpenRouter (OX Alpha)",
    icon: "◐",
    country: "United States",
    placeholder: "sk-or-v1-...",
    helpUrl: "https://openrouter.ai/keys",
    helpText: "One key, every routed model — includes the stealth OX Alpha release",
    models: [
      { id: "stealth/ox-alpha", name: "OX Alpha", description: "Newest stealth release routed via OpenRouter" },
      { id: "openai/gpt-5.5", name: "GPT-5.5 (routed)", description: "OpenAI flagship through OpenRouter" },
      { id: "anthropic/claude-opus-4.5", name: "Claude Opus 4.5 (routed)", description: "Anthropic flagship through OpenRouter" },
      { id: "google/gemini-3-pro-preview", name: "Gemini 3 Pro (routed)", description: "Google frontier through OpenRouter" },
      { id: "openai/gpt-4o-mini", name: "GPT-4o Mini (routed)", description: "Cheap fallback — oldest kept here" },
    ],
  },



  // ───────────────────────── UNITED KINGDOM ─────────────────────────
  {
    id: "stability",
    name: "Stability AI",
    icon: "◳",
    country: "United Kingdom",
    placeholder: "sk-...",
    helpUrl: "https://platform.stability.ai/account/keys",
    helpText: "Get your API key from Stability Platform",
    models: [
      { id: "stable-diffusion-3.5-large", name: "Stable Diffusion 3.5 Large", description: "Newest image flagship" },
      { id: "stable-image-ultra", name: "Stable Image Ultra", description: "Highest-fidelity render" },
      { id: "stable-diffusion-xl-1024", name: "SDXL 1.0", description: "Oldest available — classic SDXL API" },
    ],
  },
  {
    id: "reka",
    name: "Reka AI",
    icon: "◴",
    country: "United Kingdom",
    placeholder: "Your Reka API key...",
    helpUrl: "https://platform.reka.ai/",
    helpText: "Get your API key from Reka Platform",
    models: [
      { id: "reka-core", name: "Reka Core", description: "Newest multimodal flagship" },
      { id: "reka-flash", name: "Reka Flash", description: "Fast multimodal" },
      { id: "reka-edge", name: "Reka Edge", description: "Oldest available — original Reka API" },
    ],
  },

  // ───────────────────────── CANADA ─────────────────────────
  {
    id: "cohere",
    name: "Cohere (Command)",
    icon: "◵",
    country: "Canada",
    placeholder: "Your Cohere API key...",
    helpUrl: "https://dashboard.cohere.com/api-keys",
    helpText: "Get your API key from Cohere Dashboard",
    models: [
      { id: "command-a-03-2025", name: "Command A", description: "Newest agentic flagship, 256K context" },
      { id: "command-r-plus", name: "Command R+", description: "RAG-tuned production model" },
      { id: "command-r", name: "Command R", description: "Balanced RAG model" },
      { id: "command", name: "Command", description: "Oldest available — original Command API" },
    ],
  },

  // ───────────────────────── FRANCE ─────────────────────────
  {
    id: "mistral",
    name: "Mistral AI",
    icon: "◐",
    country: "France",
    placeholder: "Your Mistral API key...",
    helpUrl: "https://console.mistral.ai/api-keys/",
    helpText: "Get your API key from Mistral Console",
    models: [
      { id: "mistral-large-3", name: "Mistral Large 3", description: "Newest frontier flagship" },
      { id: "magistral-medium", name: "Magistral Medium", description: "Reasoning specialist" },
      { id: "codestral-25", name: "Codestral 25", description: "Latest dedicated code model" },
      { id: "ministral-8b", name: "Ministral 8B", description: "Fast edge model" },
      { id: "mistral-7b-instruct", name: "Mistral 7B Instruct", description: "Oldest available — original Mistral API" },
    ],
  },

  // ───────────────────────── INDIA ─────────────────────────
  {
    id: "sarvam",
    name: "Sarvam AI",
    icon: "◶",
    country: "India",
    placeholder: "Your Sarvam API key...",
    helpUrl: "https://dashboard.sarvam.ai/",
    helpText: "Get your API key from Sarvam Dashboard — Indic-tuned",
    models: [
      { id: "sarvam-m", name: "Sarvam-M", description: "Newest 24B Indic reasoning flagship" },
      { id: "sarvam-2b", name: "Sarvam-2B", description: "Compact bilingual Indic model" },
      { id: "sarvam-1", name: "Sarvam-1", description: "Oldest available — original Sarvam API" },
    ],
  },
  {
    id: "krutrim",
    name: "Krutrim (Ola)",
    icon: "◷",
    country: "India",
    placeholder: "Your Krutrim API key...",
    helpUrl: "https://cloud.olakrutrim.com/",
    helpText: "Get your API key from Ola Krutrim Cloud",
    models: [
      { id: "krutrim-2-instruct", name: "Krutrim-2 Instruct", description: "Newest 12B Indic multilingual" },
      { id: "krutrim-spectre-v2", name: "Krutrim Spectre v2", description: "Production chat" },
      { id: "krutrim-1", name: "Krutrim-1", description: "Oldest available — original Krutrim API" },
    ],
  },
  {
    id: "twoai",
    name: "TWO AI (SUTRA)",
    icon: "◸",
    country: "India",
    placeholder: "Your TWO AI API key...",
    helpUrl: "https://www.two.ai/sutra",
    helpText: "Get your API key from TWO AI / SUTRA",
    models: [
      { id: "sutra-v2", name: "SUTRA-V2", description: "Newest multilingual flagship (50+ langs)" },
      { id: "sutra-pro", name: "SUTRA Pro", description: "Strong multilingual chat" },
      { id: "sutra-light", name: "SUTRA Light", description: "Oldest available — original SUTRA API" },
    ],
  },

  // ───────────────────────── CHINA ─────────────────────────
  {
    id: "deepseek",
    name: "DeepSeek",
    icon: "◔",
    country: "China",
    placeholder: "sk-...",
    helpUrl: "https://platform.deepseek.com/",
    helpText: "Get your API key from DeepSeek Platform",
    models: [
      { id: "deepseek-v3.2", name: "DeepSeek V3.2", description: "Newest flagship chat" },
      { id: "deepseek-r1", name: "DeepSeek R1", description: "Frontier open reasoning" },
      { id: "deepseek-chat", name: "DeepSeek V3", description: "Stable production chat" },
      { id: "deepseek-coder-v2", name: "DeepSeek Coder V2", description: "Code-specialized MoE" },
      { id: "deepseek-llm-67b-chat", name: "DeepSeek LLM 67B", description: "Oldest available — original DeepSeek API" },
    ],
  },
  {
    id: "qwen",
    name: "Alibaba Qwen",
    icon: "◉",
    country: "China",
    placeholder: "sk-...",
    helpUrl: "https://dashscope.console.aliyun.com/apiKey",
    helpText: "Get your API key from Alibaba Cloud DashScope",
    models: [
      { id: "qwen3-max", name: "Qwen3 Max", description: "Newest trillion-param MoE flagship" },
      { id: "qwen3-235b-a22b", name: "Qwen3 235B", description: "Top open MoE reasoning" },
      { id: "qwen3-coder-plus", name: "Qwen3 Coder Plus", description: "Agentic coding specialist" },
      { id: "qwen-turbo", name: "Qwen Turbo", description: "Fast, low-cost tier" },
      { id: "qwen-7b-chat", name: "Qwen 7B Chat", description: "Oldest available — original Qwen API" },
    ],
  },
  {
    id: "zhipu",
    name: "Zhipu AI (GLM)",
    icon: "◍",
    country: "China",
    placeholder: "Your Zhipu API key...",
    helpUrl: "https://open.bigmodel.cn/usercenter/apikeys",
    helpText: "Get your API key from Zhipu BigModel",
    models: [
      { id: "glm-4.6", name: "GLM-4.6", description: "Newest flagship reasoning + coding" },
      { id: "glm-4.5", name: "GLM-4.5", description: "Strong agentic + tool use" },
      { id: "glm-4.5-air", name: "GLM-4.5 Air", description: "Fast, cost-efficient" },
      { id: "chatglm-6b", name: "ChatGLM 6B", description: "Oldest available — original ChatGLM API" },
    ],
  },
  {
    id: "moonshot",
    name: "Moonshot (Kimi)",
    icon: "◗",
    country: "China",
    placeholder: "sk-...",
    helpUrl: "https://platform.moonshot.cn/console/api-keys",
    helpText: "Get your API key from Moonshot Platform",
    models: [
      { id: "kimi-k2", name: "Kimi K2", description: "Newest trillion-param MoE flagship" },
      { id: "kimi-k2-turbo", name: "Kimi K2 Turbo", description: "High-speed K2 tier" },
      { id: "moonshot-v1-128k", name: "Moonshot v1 128K", description: "Long-context chat" },
      { id: "moonshot-v1-8k", name: "Moonshot v1 8K", description: "Oldest available — original Moonshot API" },
    ],
  },
  {
    id: "baidu",
    name: "Baidu ERNIE",
    icon: "◖",
    country: "China",
    placeholder: "Your Qianfan API key...",
    helpUrl: "https://qianfan.cloud.baidu.com/",
    helpText: "Get your API key from Baidu Qianfan",
    models: [
      { id: "ernie-5.0", name: "ERNIE 5.0", description: "Newest flagship multimodal" },
      { id: "ernie-4.5-turbo", name: "ERNIE 4.5 Turbo", description: "Fast reasoning tier" },
      { id: "ernie-x1", name: "ERNIE X1", description: "Deep reasoning specialist" },
      { id: "ernie-bot", name: "ERNIE Bot 1.0", description: "Oldest available — original ERNIE API" },
    ],
  },
  {
    id: "minimax",
    name: "MiniMax",
    icon: "◙",
    country: "China",
    placeholder: "Your MiniMax API key...",
    helpUrl: "https://www.minimaxi.com/user-center/basic-information/interface-key",
    helpText: "Get your API key from MiniMax",
    models: [
      { id: "minimax-m2", name: "MiniMax M2", description: "Newest agentic flagship" },
      { id: "abab7-chat-preview", name: "Abab 7 Chat", description: "Long-context chat" },
      { id: "abab5-chat", name: "Abab 5 Chat", description: "Oldest available — original MiniMax API" },
    ],
  },

  // ───────────────────────── BRAZIL ─────────────────────────
  {
    id: "maritaca",
    name: "Maritaca AI (Sabiá)",
    icon: "◹",
    country: "Brazil",
    placeholder: "Your Maritaca API key...",
    helpUrl: "https://plataforma.maritaca.ai/",
    helpText: "Get your API key from Maritaca Plataforma — Portuguese-tuned",
    models: [
      { id: "sabia-3", name: "Sabiá-3", description: "Newest Portuguese flagship" },
      { id: "sabia-2-medium", name: "Sabiá-2 Medium", description: "Balanced PT chat" },
      { id: "sabia-2-small", name: "Sabiá-2 Small", description: "Fast PT tier" },
      { id: "sabia-7b", name: "Sabiá-7B", description: "Oldest available — original Sabiá API" },
    ],
  },
  {
    id: "widelabs",
    name: "Widelabs (Amazônia)",
    icon: "◺",
    country: "Brazil",
    placeholder: "Your Widelabs API key...",
    helpUrl: "https://widelabs.com.br/",
    helpText: "Get your API key from Widelabs",
    models: [
      { id: "amazonia-ia-2", name: "Amazônia IA 2", description: "Newest Brazilian sovereign LLM" },
      { id: "amazonia-ia-1", name: "Amazônia IA 1", description: "Oldest available — original Amazônia API" },
    ],
  },

  // ───────────────────────── AUSTRALIA ─────────────────────────
  {
    id: "maincode",
    name: "Maincode (Matrix)",
    icon: "◿",
    country: "Australia",
    placeholder: "Your Maincode API key...",
    helpUrl: "https://maincode.com/",
    helpText: "Get your API key from Maincode — Australian sovereign AI",
    models: [
      { id: "matrix-1", name: "Matrix-1", description: "Newest Australian-built foundation model" },
      { id: "matrix-mini", name: "Matrix Mini", description: "Oldest available — original Matrix API" },
    ],
  },
  {
    id: "leonardo",
    name: "Leonardo AI",
    icon: "◊",
    country: "Australia",
    placeholder: "Your Leonardo API key...",
    helpUrl: "https://app.leonardo.ai/api",
    helpText: "Get your API key from Leonardo AI",
    models: [
      { id: "phoenix-1.0", name: "Phoenix 1.0", description: "Newest in-house image flagship" },
      { id: "leonardo-anime-xl", name: "Leonardo Anime XL", description: "Stylized art generator" },
      { id: "leonardo-diffusion", name: "Leonardo Diffusion", description: "Oldest available — original Leonardo API" },
    ],
  },

  // ───────────────────────── NIGERIA ─────────────────────────
  {
    id: "awarri",
    name: "Awarri (LAM-1)",
    icon: "◊",
    country: "Nigeria",
    placeholder: "Your Awarri API key...",
    helpUrl: "https://awarri.com/",
    helpText: "Get your API key from Awarri — Nigerian LLM",
    models: [
      { id: "lam-1", name: "LAM-1", description: "Newest large African model (Yoruba, Igbo, Hausa, English)" },
      { id: "lam-1-base", name: "LAM-1 Base", description: "Oldest available — base LAM API" },
    ],
  },
  {
    id: "lelapa",
    name: "Lelapa AI (Vulavula)",
    icon: "◊",
    country: "Nigeria",
    placeholder: "Your Lelapa API key...",
    helpUrl: "https://lelapa.ai/",
    helpText: "Get your API key from Lelapa AI — African languages",
    models: [
      { id: "vulavula", name: "Vulavula", description: "Newest African multilingual API" },
      { id: "inkuba-0.4b", name: "InkubaLM 0.4B", description: "Oldest available — original African open model" },
    ],
  },

  // ───────────────────────── PERU ─────────────────────────
  {
    id: "latamgpt",
    name: "Latam-GPT",
    icon: "◊",
    country: "Peru",
    placeholder: "Your Latam-GPT API key...",
    helpUrl: "https://www.latamgpt.org/",
    helpText: "Get your API key from the Latam-GPT consortium (Peru / LatAm)",
    models: [
      { id: "latam-gpt-1", name: "Latam-GPT 1", description: "Newest Spanish/Portuguese/Quechua flagship" },
      { id: "latam-gpt-base", name: "Latam-GPT Base", description: "Oldest available — base Latam-GPT API" },
    ],
  },
];
