// asherin.health — deep anatomy catalogue. finer-grained structures than the base atlas
// systems: sublayers, microanatomy, functional subdivisions. every entry maps to territory
// keys resolved against the reference geometry (base territories or the extras in
// territoryExtra.ts); where nothing plausibly exists as a mesh, the referenced territory
// carries a `note` explaining that, and this file never claims otherwise.
import type { SystemId } from "./systems";

export interface DeepStructure {
  id: string;
  name: string;
  group: string;
  system: SystemId;
  sex?: "male" | "female";
  summary: string;
  whatItDoes: string;
  whenItGoesWrong: string[];
  territoryKeys: string[];
}

export interface DeepGroup {
  id: string;
  label: string;
  blurb: string;
}

export const DEEP_GROUPS: DeepGroup[] = [
  { id: "integument", label: "skin, layer by layer", blurb: "the epidermis, dermis and the fat and glands beneath them." },
  { id: "adipose", label: "fat depots", blurb: "where fat is stored and why location changes what it does metabolically." },
  { id: "fascia", label: "fascia", blurb: "the connective sheets that wrap muscle, transmit force and separate compartments." },
  { id: "meninges-csf", label: "meninges and csf spaces", blurb: "the membranes around the brain and cord, and the fluid that cushions and cleans them." },
  { id: "microcirculation", label: "portal and microcirculation", blurb: "the small vessels and portal drainage that finish what the named arteries and veins start." },
  { id: "joints", label: "joints and connective detail", blurb: "synovium, cartilage, ligament and the disc — how a joint stays smooth and stable." },
  { id: "bone", label: "bone, inside out", blurb: "cortical shell, trabecular mesh, marrow and the growth plate." },
  { id: "cavities", label: "body cavities", blurb: "the potential spaces that let organs move against each other without friction." },
  { id: "autonomic-enteric", label: "autonomic and enteric nervous system", blurb: "the nerves that run the body automatically, including the gut's own nervous system." },
  { id: "cranial-nerves", label: "the twelve cranial nerves", blurb: "each nerve leaving the brain directly, with what it carries." },
  { id: "brain", label: "brain, region by region", blurb: "functional parcellation: what each area is thought to contribute." },
  { id: "spinal-cord", label: "spinal cord", blurb: "the tracts running up and down the cord, and its segmental levels." },
  { id: "dental-oral", label: "teeth and mouth", blurb: "tooth structure, the tissues holding it in the jaw, and the tongue." },
  { id: "ear", label: "ear", blurb: "outer, middle and inner ear, from eardrum to hair cell." },
  { id: "eye", label: "eye", blurb: "the layered globe, from cornea to retina." },
  { id: "renal", label: "kidney microanatomy", blurb: "the nephron and the vessels that let it filter blood." },
  { id: "biliary", label: "biliary tree", blurb: "the ducts carrying bile from liver to duodenum." },
  { id: "lymphatic-drainage", label: "lymphatic drainage", blurb: "the chains fluid moves through on its way back to the blood." },
  { id: "immune", label: "immune tissue", blurb: "where immune cells are made, mature and stand watch." },
  { id: "endocrine-axes", label: "endocrine axes", blurb: "the glands that answer to each other in a feedback loop." },
  { id: "mammary", label: "mammary system", blurb: "breast structure across the lobules, ducts and drainage." },
  { id: "female-reproductive", label: "female reproductive anatomy", blurb: "ovary to vulva, and the ligaments that hold them." },
  { id: "male-reproductive", label: "male reproductive anatomy", blurb: "testis to penis, and the ducts that connect them." },
];

export const DEEP_STRUCTURES: DeepStructure[] = [
  // ---------- integumentary ----------
  { id: "epidermis-stratum-corneum", name: "stratum corneum", group: "integument", system: "integumentary",
    summary: "the outermost, dead, keratin-packed layer of skin.",
    whatItDoes: "flattened, dead corneocytes packed with keratin and lipid form the main water and microbial barrier.",
    whenItGoesWrong: ["dryness and cracking when the barrier lipid is depleted", "thickened in calluses and some chronic eczema", "breached, it opens the door to infection"],
    territoryKeys: ["skin"] },
  { id: "epidermis-stratum-lucidum", name: "stratum lucidum", group: "integument", system: "integumentary",
    summary: "a thin clear layer seen only in thick skin (palms, soles).",
    whatItDoes: "adds extra shear resistance under load-bearing skin.",
    whenItGoesWrong: ["contributes to callus formation under chronic pressure"],
    territoryKeys: ["skin"] },
  { id: "epidermis-stratum-granulosum", name: "stratum granulosum", group: "integument", system: "integumentary",
    summary: "the layer where keratinocytes release lipid granules and begin to die.",
    whatItDoes: "lamellar bodies here secrete the lipids that cement the outer barrier together.",
    whenItGoesWrong: ["disrupted lipid processing underlies some ichthyoses"],
    territoryKeys: ["skin"] },
  { id: "epidermis-stratum-spinosum", name: "stratum spinosum", group: "integument", system: "integumentary",
    summary: "the spiny layer, held together by desmosomes.",
    whatItDoes: "provides mechanical cohesion and houses langerhans cells for immune surveillance.",
    whenItGoesWrong: ["desmosome autoantibodies here cause pemphigus blistering"],
    territoryKeys: ["skin"] },
  { id: "epidermis-stratum-basale", name: "stratum basale", group: "integument", system: "integumentary",
    summary: "the single deepest epidermal layer, sitting on the basement membrane.",
    whatItDoes: "dividing keratinocytes and melanocytes here continually renew the epidermis above.", 
    whenItGoesWrong: ["basal cell carcinoma arises from this layer", "melanocyte disruption changes pigmentation"],
    territoryKeys: ["skin"] },
  { id: "dermis-papillary", name: "papillary dermis", group: "integument", system: "integumentary",
    summary: "the thin upper dermis that interdigitates with the epidermis.",
    whatItDoes: "loose connective tissue with capillary loops feeds the avascular epidermis and forms fingerprint ridges.",
    whenItGoesWrong: ["flattens with age, weakening the epidermal-dermal junction and making skin fragile"],
    territoryKeys: ["skin"] },
  { id: "dermis-reticular", name: "reticular dermis", group: "integument", system: "integumentary",
    summary: "the thicker deep dermis of dense collagen and elastin.",
    whatItDoes: "gives skin its tensile strength and elastic recoil; houses most glands, follicles and deep vessels.",
    whenItGoesWrong: ["collagen and elastin breakdown here produces wrinkling and stretch marks", "scarring after deep injury"],
    territoryKeys: ["skin"] },
  { id: "hypodermis", name: "hypodermis (subcutaneous layer)", group: "integument", system: "integumentary",
    summary: "the fat and connective tissue layer beneath the dermis.",
    whatItDoes: "insulates, cushions and anchors skin to underlying fascia; a major energy reserve.",
    whenItGoesWrong: ["lipohypertrophy from repeated injections", "loss of this layer with age increases skin fragility and bruising"],
    territoryKeys: ["adipose-subcutaneous", "skin"] },
  { id: "hair-follicle", name: "hair follicle", group: "integument", system: "integumentary",
    summary: "the tube-shaped structure producing a hair shaft.",
    whatItDoes: "cycles through growth, regression and rest phases; the bulge region holds follicle stem cells.",
    whenItGoesWrong: ["androgenic miniaturisation causes pattern hair loss", "autoimmune attack causes alopecia areata"],
    territoryKeys: ["hair-follicle"] },
  { id: "sebaceous-gland", name: "sebaceous gland", group: "integument", system: "integumentary",
    summary: "an oil gland usually opening into a hair follicle.",
    whatItDoes: "secretes sebum that lubricates hair and skin and contributes to the barrier.",
    whenItGoesWrong: ["overactivity with follicular blockage produces acne", "underactivity contributes to dry skin"],
    territoryKeys: ["sebaceous-gland"] },
  { id: "eccrine-gland", name: "eccrine sweat gland", group: "integument", system: "integumentary",
    summary: "a coiled gland found over nearly the whole body surface.",
    whatItDoes: "secretes watery sweat for evaporative cooling, under sympathetic cholinergic control.",
    whenItGoesWrong: ["excess activity causes hyperhidrosis", "loss of function impairs heat tolerance"],
    territoryKeys: ["eccrine-gland"] },
  { id: "apocrine-gland", name: "apocrine sweat gland", group: "integument", system: "integumentary",
    summary: "a scent gland concentrated in the axilla, groin and areola.",
    whatItDoes: "secretes a protein-rich fluid that skin bacteria metabolise into body odour; becomes active at puberty.",
    whenItGoesWrong: ["chronic follicular occlusion here causes hidradenitis suppurativa"],
    territoryKeys: ["apocrine-gland"] },
  { id: "nail-unit", name: "nail unit", group: "integument", system: "integumentary",
    summary: "the nail plate, matrix, bed and surrounding folds.",
    whatItDoes: "the matrix produces the keratinised plate that protects the fingertip and aids fine touch and grip.",
    whenItGoesWrong: ["matrix damage causes permanent ridging or splitting", "fungal infection of the bed thickens and discolours the plate", "clubbing of the nail bed can signal chronic hypoxia"],
    territoryKeys: ["nail-unit"] },

  // ---------- adipose ----------
  { id: "adipose-subcutaneous", name: "subcutaneous fat", group: "adipose", system: "integumentary",
    summary: "fat stored just under the skin over most of the body.",
    whatItDoes: "insulation, cushioning and the body's largest single energy store; metabolically less active than visceral fat.",
    whenItGoesWrong: ["gluteofemoral loss with visceral gain shifts risk toward metabolic disease"],
    territoryKeys: ["adipose-subcutaneous"] },
  { id: "adipose-visceral", name: "visceral fat", group: "adipose", system: "digestive",
    summary: "fat packed around the abdominal organs and mesentery.",
    whatItDoes: "metabolically active, releasing free fatty acids and inflammatory signals directly toward the portal vein.",
    whenItGoesWrong: ["excess visceral fat is closely tied to insulin resistance, fatty liver and cardiovascular risk independent of overall weight"],
    territoryKeys: ["adipose-visceral"] },
  { id: "adipose-epicardial", name: "epicardial fat", group: "adipose", system: "cardiac",
    summary: "fat directly on the surface of the heart, inside the pericardium.",
    whatItDoes: "buffers the coronary arteries mechanically and metabolically; shares blood supply with the myocardium.",
    whenItGoesWrong: ["increased epicardial fat volume correlates with coronary atherosclerosis and atrial fibrillation risk"],
    territoryKeys: ["adipose-epicardial"] },
  { id: "adipose-perirenal", name: "perirenal fat", group: "adipose", system: "urinary",
    summary: "fat encasing each kidney within its fascial capsule.",
    whatItDoes: "cushions and stabilises the kidney's position.",
    whenItGoesWrong: ["marked expansion is associated with hypertension via mechanical renal compression"],
    territoryKeys: ["adipose-perirenal"] },
  { id: "adipose-brown", name: "brown fat", group: "adipose", system: "integumentary",
    summary: "thermogenic fat found around the neck, supraclavicular region and along the spine.",
    whatItDoes: "mitochondria-dense tissue that burns fuel directly to make heat rather than atp, activated by cold.",
    whenItGoesWrong: ["brown fat activity declines with age, contributing to reduced cold tolerance and metabolic rate"],
    territoryKeys: ["adipose-brown"] },
  { id: "bone-marrow-fat", name: "bone marrow adipose tissue", group: "adipose", system: "skeletal",
    summary: "fat cells that increasingly replace red marrow with age.",
    whatItDoes: "fills marrow space as haematopoietic demand falls; also secretes hormones affecting bone turnover.",
    whenItGoesWrong: ["expansion correlates with osteoporosis and reduced marrow reserve"],
    territoryKeys: ["marrow-yellow"] },

  // ---------- fascia ----------
  { id: "fascia-superficial", name: "superficial fascia", group: "fascia", system: "connective",
    summary: "the fibrous-fatty layer just under the dermis.",
    whatItDoes: "connects skin loosely to deeper structures while allowing it to glide.",
    whenItGoesWrong: ["fibrosis here contributes to cellulite appearance and lymphoedema texture changes"],
    territoryKeys: ["fascia-superficial"] },
  { id: "fascia-deep", name: "deep fascia", group: "fascia", system: "connective",
    summary: "the dense fibrous envelope wrapping muscle groups.",
    whatItDoes: "compartmentalises muscle, transmits force between muscles, and resists swelling.",
    whenItGoesWrong: ["a tight deep fascial compartment with swelling causes compartment syndrome, a surgical emergency"],
    territoryKeys: ["fascia-deep"] },
  { id: "fascia-thoracolumbar", name: "thoracolumbar fascia", group: "fascia", system: "connective",
    summary: "the broad fascial sheet of the lower back.",
    whatItDoes: "links latissimus dorsi, gluteus maximus and abdominal muscles across the low back, stabilising the spine during lifting.",
    whenItGoesWrong: ["a frequently cited but hard-to-isolate contributor to nonspecific low back pain"],
    territoryKeys: ["fascia-thoracolumbar"] },
  { id: "fascia-plantar", name: "plantar fascia", group: "fascia", system: "connective",
    summary: "the thick fibrous band along the sole of the foot.",
    whatItDoes: "supports the arch and stores elastic energy during walking and running.",
    whenItGoesWrong: ["repetitive strain causes plantar fasciitis, felt as heel pain on first steps"],
    territoryKeys: ["fascia-plantar"] },
  { id: "iliotibial-band", name: "iliotibial band", group: "fascia", system: "connective",
    summary: "a thickened fascial band running down the outside of the thigh.",
    whatItDoes: "stabilises the knee and hip during walking and running by transmitting tension from hip muscles to the shin.",
    whenItGoesWrong: ["friction against the lateral femoral condyle causes iliotibial band syndrome in runners and cyclists"],
    territoryKeys: ["iliotibial-band"] },
  { id: "epimysium", name: "epimysium", group: "fascia", system: "muscular",
    summary: "the connective tissue sheath around a whole muscle.",
    whatItDoes: "separates muscles from each other and transmits contractile force to tendon.",
    whenItGoesWrong: ["inflammation here contributes to some myofascial pain presentations"],
    territoryKeys: ["muscle"] },
  { id: "perimysium", name: "perimysium", group: "fascia", system: "muscular",
    summary: "the connective tissue wrapping bundles (fascicles) of muscle fibres.",
    whatItDoes: "carries the larger blood vessels and nerves into the muscle belly.",
    whenItGoesWrong: ["fibrosis here after injury can stiffen a muscle's normal glide"],
    territoryKeys: ["muscle"] },
  { id: "endomysium", name: "endomysium", group: "fascia", system: "muscular",
    summary: "the delicate connective tissue around each individual muscle fibre.",
    whatItDoes: "carries capillaries directly to each fibre and transmits its force outward.",
    whenItGoesWrong: ["inflammatory myopathies often show endomysial infiltration on biopsy"],
    territoryKeys: ["muscle"] },

  // ---------- meninges & csf ----------
  { id: "dura-mater", name: "dura mater", group: "meninges-csf", system: "nervous",
    summary: "the tough outer membrane covering brain and spinal cord.",
    whatItDoes: "protects neural tissue and anchors the venous sinuses that drain the brain.",
    whenItGoesWrong: ["torn bridging veins under the dura cause subdural haematoma", "dural tears cause low-pressure headache from csf leak"],
    territoryKeys: ["meninges-dura"] },
  { id: "arachnoid-mater", name: "arachnoid mater", group: "meninges-csf", system: "nervous",
    summary: "the thin middle meningeal layer, web-like against the dura.",
    whatItDoes: "bounds the subarachnoid space and its arachnoid granulations return csf to venous blood.",
    whenItGoesWrong: ["bleeding into the space beneath it is a subarachnoid haemorrhage"],
    territoryKeys: ["meninges-arachnoid"] },
  { id: "pia-mater", name: "pia mater", group: "meninges-csf", system: "nervous",
    summary: "the delicate innermost membrane hugging the brain and cord surface.",
    whatItDoes: "follows every fold of the brain surface and helps form the blood-brain barrier at its vessels.",
    whenItGoesWrong: ["meningitis inflames all three meningeal layers, pia included"],
    territoryKeys: ["meninges-pia"] },
  { id: "subarachnoid-space", name: "subarachnoid space", group: "meninges-csf", system: "nervous",
    summary: "the fluid-filled gap between arachnoid and pia.",
    whatItDoes: "holds circulating cerebrospinal fluid that cushions the brain and cord.",
    whenItGoesWrong: ["aneurysm rupture here causes a sudden, severe 'thunderclap' headache"],
    territoryKeys: ["subarachnoid-space"] },
  { id: "cerebral-ventricles", name: "cerebral ventricles", group: "meninges-csf", system: "nervous",
    summary: "the four connected cavities inside the brain that make and carry csf.",
    whatItDoes: "choroid plexus in the ventricles secretes csf, which flows out to bathe brain and cord.",
    whenItGoesWrong: ["obstruction of flow causes hydrocephalus and raised intracranial pressure"],
    territoryKeys: ["ventricles"] },
  { id: "choroid-plexus", name: "choroid plexus", group: "meninges-csf", system: "nervous",
    summary: "specialised tissue inside the ventricles that secretes cerebrospinal fluid.",
    whatItDoes: "filters blood plasma to produce csf and forms part of the blood-csf barrier.",
    whenItGoesWrong: ["rare choroid plexus tumours can overproduce csf and cause hydrocephalus"],
    territoryKeys: ["choroid-plexus"] },
  { id: "glymphatic-pathway", name: "glymphatic pathway", group: "meninges-csf", system: "nervous",
    summary: "a perivascular clearance route that flushes waste from brain tissue, most active during sleep.",
    whatItDoes: "csf is driven along perivascular spaces around vessels, exchanging with interstitial fluid to clear metabolic waste including amyloid-beta.",
    whenItGoesWrong: ["reduced glymphatic clearance, particularly with poor sleep, is an active research link to neurodegenerative risk — not itself diagnostic of anything"],
    territoryKeys: ["glymphatic"] },

  // ---------- microcirculation ----------
  { id: "portal-vein-tributaries", name: "portal vein tributaries", group: "microcirculation", system: "venous",
    summary: "the splenic, superior and inferior mesenteric veins that join to form the portal vein.",
    whatItDoes: "collect nutrient-rich blood from the gut and spleen and deliver it to the liver before it reaches general circulation.",
    whenItGoesWrong: ["obstruction anywhere in this system raises portal pressure, causing varices and ascites"],
    territoryKeys: ["portal-vein"] },
  { id: "hepatic-sinusoids", name: "hepatic sinusoids", group: "microcirculation", system: "digestive",
    summary: "the fenestrated capillary-like channels running between liver cell plates.",
    whatItDoes: "let plasma directly contact hepatocytes for exchange, while kupffer cells here filter blood-borne debris and microbes.",
    whenItGoesWrong: ["capillarisation of sinusoids in fibrosis restricts this exchange and raises portal pressure"],
    territoryKeys: ["liver"] },
  { id: "capillary-beds", name: "capillary beds", group: "microcirculation", system: "arterial",
    summary: "the smallest vessels, one cell layer thick, where exchange with tissue happens.",
    whatItDoes: "oxygen, nutrients and waste cross between blood and tissue only here, nowhere else in the circulation.",
    whenItGoesWrong: ["capillary rarefaction is an early feature of hypertension and diabetes-related microvascular disease"],
    territoryKeys: ["peripheral-arteries"] },
  { id: "arterioles-venules", name: "arterioles and venules", group: "microcirculation", system: "arterial",
    summary: "the smallest named vessels feeding and draining capillary beds.",
    whatItDoes: "arteriolar smooth muscle tone is the main lever the body uses to control blood pressure and local blood flow.",
    whenItGoesWrong: ["chronic arteriolar narrowing underlies essential hypertension's vascular resistance"],
    territoryKeys: ["peripheral-arteries", "veins"] },
  { id: "lymph-capillaries", name: "lymphatic capillaries", group: "microcirculation", system: "lymphatic",
    summary: "blind-ended, highly permeable vessels that begin lymph drainage in tissue.",
    whatItDoes: "pick up excess interstitial fluid, proteins and immune cells that blood capillaries leave behind.",
    whenItGoesWrong: ["their failure or damage causes localised lymphoedema"],
    territoryKeys: ["lymphatic"] },

  // ---------- joints ----------
  { id: "synovium", name: "synovium", group: "joints", system: "connective",
    summary: "the membrane lining the inside of a joint capsule.",
    whatItDoes: "secretes synovial fluid and removes debris from the joint space.",
    whenItGoesWrong: ["autoimmune inflammation here (synovitis) drives rheumatoid arthritis"],
    territoryKeys: ["joint-synovium"] },
  { id: "synovial-fluid", name: "synovial fluid", group: "joints", system: "connective",
    summary: "the viscous fluid filling the joint cavity.",
    whatItDoes: "lubricates the joint and delivers nutrients to avascular articular cartilage.",
    whenItGoesWrong: ["excess fluid (effusion) signals irritation or injury inside the joint", "crystal or infected fluid causes gout or septic arthritis"],
    territoryKeys: ["joint-synovium"] },
  { id: "articular-cartilage", name: "articular cartilage", group: "joints", system: "connective",
    summary: "the smooth cartilage cap on the ends of bones inside a joint.",
    whatItDoes: "distributes load and lets bone surfaces glide against each other nearly without friction.",
    whenItGoesWrong: ["progressive wear and thinning is the hallmark of osteoarthritis", "has almost no capacity to heal once damaged"],
    territoryKeys: ["articular-cartilage"] },
  { id: "meniscus", name: "meniscus", group: "joints", system: "connective",
    summary: "the c-shaped fibrocartilage pads inside the knee.",
    whatItDoes: "deepen the joint surface, distribute load and absorb shock between femur and tibia.",
    whenItGoesWrong: ["a tear from twisting injury or degeneration can cause locking, catching or swelling"],
    territoryKeys: ["meniscus", "knee"] },
  { id: "labrum", name: "labrum", group: "joints", system: "connective",
    summary: "the fibrocartilage rim deepening the hip and shoulder sockets.",
    whatItDoes: "increases joint stability and contact area, and seals synovial fluid within the joint.",
    whenItGoesWrong: ["tears cause catching, instability or deep joint pain, common in the hip and shoulder"],
    territoryKeys: ["labrum"] },
  { id: "bursae", name: "bursae", group: "joints", system: "connective",
    summary: "small fluid-filled sacs cushioning friction points near joints.",
    whatItDoes: "reduce friction between tendon, muscle and bone where they slide across each other.",
    whenItGoesWrong: ["inflammation (bursitis) from overuse or pressure causes localised swelling and pain"],
    territoryKeys: ["bursa"] },
  { id: "tendon-sheath", name: "tendon sheath", group: "joints", system: "connective",
    summary: "the synovial-lined tunnel some tendons run through.",
    whatItDoes: "reduces friction as the tendon slides during movement, especially in the hand and wrist.",
    whenItGoesWrong: ["inflammation causes tenosynovitis, including trigger finger and de quervain's"],
    territoryKeys: ["tendon-sheath"] },
  { id: "ligaments", name: "ligaments", group: "joints", system: "connective",
    summary: "dense fibrous bands connecting bone to bone across a joint.",
    whatItDoes: "limit and guide joint motion and provide passive stability.",
    whenItGoesWrong: ["sprains (partial or complete tears) cause instability and pain, common at ankle, knee and wrist"],
    territoryKeys: ["cartilage"] },
  { id: "iv-disc-nucleus", name: "intervertebral disc nucleus pulposus", group: "joints", system: "connective",
    summary: "the gel-like centre of each intervertebral disc.",
    whatItDoes: "absorbs and distributes compressive load between vertebrae.",
    whenItGoesWrong: ["it can herniate through a weakened annulus and press on a nerve root, causing radiating pain"],
    territoryKeys: ["intervertebral-disc"] },
  { id: "iv-disc-annulus", name: "intervertebral disc annulus fibrosus", group: "joints", system: "connective",
    summary: "the tough fibrous ring surrounding the disc's nucleus.",
    whatItDoes: "contains the nucleus pulposus under load and resists twisting forces on the spine.",
    whenItGoesWrong: ["tears here allow disc material to bulge or herniate and are a source of discogenic back pain themselves"],
    territoryKeys: ["intervertebral-disc"] },
  { id: "vertebral-endplates", name: "vertebral endplates", group: "joints", system: "skeletal",
    summary: "the thin cartilage-bone interface between disc and vertebral body.",
    whatItDoes: "the main route for nutrients to diffuse into the disc, which has little direct blood supply.",
    whenItGoesWrong: ["endplate damage and sclerosis (modic changes) are linked to chronic discogenic low back pain"],
    territoryKeys: ["vertebra", "intervertebral-disc"] },

  // ---------- bone ----------
  { id: "bone-cortical", name: "cortical (compact) bone", group: "bone", system: "skeletal",
    summary: "the dense outer shell of every bone.",
    whatItDoes: "provides most of a bone's mechanical strength and protects the marrow within.",
    whenItGoesWrong: ["cortical thinning with age raises fracture risk, especially at the hip"],
    territoryKeys: ["bone"] },
  { id: "bone-trabecular", name: "trabecular (spongy) bone", group: "bone", system: "skeletal",
    summary: "the honeycomb-like internal bone mesh, concentrated at bone ends and vertebrae.",
    whatItDoes: "distributes load efficiently for its weight and houses much of the red marrow.",
    whenItGoesWrong: ["loses density fastest in early osteoporosis, especially in the spine"],
    territoryKeys: ["bone", "vertebra"] },
  { id: "periosteum", name: "periosteum", group: "bone", system: "skeletal",
    summary: "the fibrous membrane covering the outer surface of bone (not at joint surfaces).",
    whatItDoes: "carries the blood vessels and nerves that supply the bone shaft and drives bone repair after fracture.",
    whenItGoesWrong: ["richly innervated, so periosteal irritation (shin splints, stress reaction) is often sharply localised and tender"],
    territoryKeys: ["bone"] },
  { id: "epiphyseal-plate", name: "epiphyseal (growth) plate", group: "bone", system: "skeletal",
    summary: "the cartilage disc near the ends of long bones in children and adolescents.",
    whatItDoes: "produces new bone length until it fuses at skeletal maturity.",
    whenItGoesWrong: ["injury here in childhood can disturb future bone growth", "closure timing marks skeletal maturity on imaging"],
    territoryKeys: ["bone"], },
  { id: "marrow-red", name: "red bone marrow", group: "bone", system: "skeletal",
    summary: "blood-forming marrow, concentrated in the axial skeleton in adults.",
    whatItDoes: "produces red cells, most white cells and platelets throughout life.",
    whenItGoesWrong: ["marrow failure or replacement by disease reduces blood cell production, causing anaemia, infection risk or bleeding"],
    territoryKeys: ["marrow-axial"] },
  { id: "marrow-yellow", name: "yellow bone marrow", group: "bone", system: "skeletal",
    summary: "fat-predominant marrow filling long bone shafts in adults.",
    whatItDoes: "serves as an energy reserve and can partly convert back to red marrow if blood cell demand rises sharply.",
    whenItGoesWrong: ["proportion of yellow marrow increases with age as haematopoietic reserve falls"],
    territoryKeys: ["marrow-yellow"] },

  // ---------- cavities ----------
  { id: "peritoneal-cavity", name: "peritoneal cavity", group: "cavities", system: "digestive",
    summary: "the potential space between the two peritoneal layers lining the abdomen.",
    whatItDoes: "a thin fluid film lets abdominal organs slide against each other during digestion and movement.",
    whenItGoesWrong: ["fluid accumulation here is ascites", "infection of this space is peritonitis, a surgical emergency"],
    territoryKeys: ["peritoneum"] },
  { id: "retroperitoneum", name: "retroperitoneal space", group: "cavities", system: "urinary",
    summary: "the space behind the peritoneum holding the kidneys, aorta, and pancreas among others.",
    whatItDoes: "organs here are fixed against the back wall rather than suspended by mesentery.",
    whenItGoesWrong: ["bleeding here from trauma or aneurysm rupture can be extensive before it is externally visible"],
    territoryKeys: ["retroperitoneum"] },
  { id: "pleural-cavity", name: "pleural cavity", group: "cavities", system: "respiratory",
    summary: "the thin fluid-filled space between the two pleural layers around each lung.",
    whatItDoes: "negative pressure here holds the lung expanded against the chest wall during breathing.",
    whenItGoesWrong: ["air entering it collapses the lung (pneumothorax)", "fluid accumulation (pleural effusion) restricts breathing"],
    territoryKeys: ["pleura"] },
  { id: "pericardial-cavity", name: "pericardial cavity", group: "cavities", system: "cardiac",
    summary: "the fluid-filled space between the two layers of the pericardium around the heart.",
    whatItDoes: "lets the beating heart move with minimal friction inside its fibrous sac.",
    whenItGoesWrong: ["rapid fluid accumulation here (tamponade) compresses the heart and is a medical emergency"],
    territoryKeys: ["pericardial-space"] },
  { id: "mediastinum", name: "mediastinum", group: "cavities", system: "cardiac",
    summary: "the central chest compartment between the two lungs.",
    whatItDoes: "contains the heart, great vessels, trachea, oesophagus, thymus and central lymph nodes.",
    whenItGoesWrong: ["masses here can compress the airway or great vessels regardless of which structure they arise from"],
    territoryKeys: ["mediastinum"] },

  // ---------- autonomic & enteric ----------
  { id: "sympathetic-chain-detail", name: "sympathetic chain ganglia", group: "autonomic-enteric", system: "nervous",
    summary: "the paired chain of nerve cell clusters running beside the spine.",
    whatItDoes: "relays the 'fight or flight' signal to blood vessels, sweat glands, heart and airway smooth muscle.",
    whenItGoesWrong: ["chronic overactivation is implicated in sustained hypertension and some chronic pain states"],
    territoryKeys: ["sympathetic-chain"] },
  { id: "splanchnic-nerves", name: "splanchnic nerves", group: "autonomic-enteric", system: "nervous",
    summary: "sympathetic nerves carrying signal from the chain to abdominal organs.",
    whatItDoes: "carry pain and vasomotor signal from the gut, and are a target for pain-blocking procedures in chronic pancreatitis.",
    whenItGoesWrong: ["visceral pain from abdominal organs travels these poorly-localised pathways, which is why gut pain is often felt diffusely"],
    territoryKeys: ["sympathetic-chain"] },
  { id: "vagal-branches", name: "vagal branches", group: "autonomic-enteric", system: "nervous",
    summary: "the extensive branching of the vagus nerve through neck, chest and abdomen.",
    whatItDoes: "carries most parasympathetic output to the heart, lungs and gut down to the splenic flexure, plus sensory information back to the brainstem.",
    whenItGoesWrong: ["vagal overactivity can trigger fainting (vasovagal syncope)", "damage affects voice, swallowing, heart rate or gut motility depending on the branch"],
    territoryKeys: ["vagus"] },
  { id: "myenteric-plexus", name: "myenteric (auerbach) plexus", group: "autonomic-enteric", system: "digestive",
    summary: "a nerve network between the muscle layers of the gut wall.",
    whatItDoes: "coordinates the rhythmic contractions that move contents through the digestive tract.",
    whenItGoesWrong: ["its absence in a segment of colon causes hirschsprung disease"],
    territoryKeys: ["small-intestine", "colon"], },
  { id: "submucosal-plexus", name: "submucosal (meissner) plexus", group: "autonomic-enteric", system: "digestive",
    summary: "a nerve network within the submucosa of the gut wall.",
    whatItDoes: "regulates local blood flow, secretion and the muscle of the mucosa itself.",
    whenItGoesWrong: ["dysfunction here is implicated in some functional gut disorders"],
    territoryKeys: ["small-intestine", "colon"] },
  { id: "celiac-ganglion", name: "celiac and mesenteric ganglia", group: "autonomic-enteric", system: "nervous",
    summary: "large sympathetic ganglia in the upper abdomen around the celiac artery origin.",
    whatItDoes: "relay sympathetic control to stomach, liver, pancreas, spleen and intestines.",
    whenItGoesWrong: ["a target for nerve block procedures used to relieve severe upper abdominal cancer pain"],
    territoryKeys: ["celiac-ganglion"] },

  // ---------- cranial nerves ----------
  { id: "cn1-olfactory", name: "CN I — olfactory nerve", group: "cranial-nerves", system: "nervous",
    summary: "carries smell signal from the nasal lining to the brain.",
    whatItDoes: "olfactory receptor neurons project directly into the olfactory bulb, bypassing the thalamus.",
    whenItGoesWrong: ["loss of smell can follow viral infection, head trauma, or precede some neurodegenerative disease by years"],
    territoryKeys: ["olfactory-nerve"] },
  { id: "cn2-optic", name: "CN II — optic nerve", group: "cranial-nerves", system: "sensory",
    summary: "carries visual signal from the retina to the brain.",
    whatItDoes: "over a million axons from retinal ganglion cells bundle here and cross partially at the optic chiasm.",
    whenItGoesWrong: ["raised intracranial pressure or glaucoma can damage it, sometimes visibly on eye exam as disc swelling or cupping"],
    territoryKeys: ["optic-nerve"] },
  { id: "cn3-oculomotor", name: "CN III — oculomotor nerve", group: "cranial-nerves", system: "nervous",
    summary: "controls most eye movement, eyelid opening and pupil constriction.",
    whatItDoes: "supplies four of the six eye muscles, the lid-raising muscle and parasympathetic fibres to the pupil.",
    whenItGoesWrong: ["compression (e.g. by an aneurysm) classically causes a dilated pupil with a drooping eyelid and outward-deviated eye"],
    territoryKeys: ["cranial-nerve-oculomotor"] },
  { id: "cn4-trochlear", name: "CN IV — trochlear nerve", group: "cranial-nerves", system: "nervous",
    summary: "the thinnest cranial nerve, supplying one eye muscle.",
    whatItDoes: "controls the superior oblique muscle, which helps the eye look down and in.",
    whenItGoesWrong: ["damage causes vertical double vision, worse looking down (as when reading or on stairs)"],
    territoryKeys: ["cranial-nerve-trochlear"] },
  { id: "cn5-trigeminal", name: "CN V — trigeminal nerve", group: "cranial-nerves", system: "nervous",
    summary: "carries facial sensation and drives the muscles of chewing.",
    whatItDoes: "three divisions cover the forehead, midface and jaw for touch, pain and temperature; a motor branch drives mastication.",
    whenItGoesWrong: ["trigeminal neuralgia causes brief, severe facial pain along one of its branches"],
    territoryKeys: ["trigeminal"] },
  { id: "cn6-abducens", name: "CN VI — abducens nerve", group: "cranial-nerves", system: "nervous",
    summary: "controls outward eye movement.",
    whatItDoes: "supplies the lateral rectus muscle, which turns the eye away from the nose.",
    whenItGoesWrong: ["its long intracranial course makes it vulnerable to raised intracranial pressure, causing inward-turning double vision"],
    territoryKeys: ["cranial-nerve-abducens"] },
  { id: "cn7-facial", name: "CN VII — facial nerve", group: "cranial-nerves", system: "nervous",
    summary: "controls facial expression, taste on the front of the tongue, and some glands.",
    whatItDoes: "drives every muscle of facial expression, carries taste fibres and supplies the lacrimal and salivary glands.",
    whenItGoesWrong: ["acute one-sided weakness of the whole face (bell's palsy) reflects damage to this nerve, distinguishing it from a stroke, which usually spares the forehead"],
    territoryKeys: ["facial-nerve"] },
  { id: "cn8-vestibulocochlear", name: "CN VIII — vestibulocochlear nerve", group: "cranial-nerves", system: "sensory",
    summary: "carries hearing and balance signal from the inner ear.",
    whatItDoes: "the cochlear branch carries sound, the vestibular branch carries head position and motion signal.",
    whenItGoesWrong: ["a tumour on this nerve (vestibular schwannoma) causes one-sided hearing loss and unsteadiness"],
    territoryKeys: ["vestibulocochlear"] },
  { id: "cn9-glossopharyngeal", name: "CN IX — glossopharyngeal nerve", group: "cranial-nerves", system: "nervous",
    summary: "carries taste and sensation from the throat and back of the tongue, and helps swallowing.",
    whatItDoes: "also carries signal from the carotid body and sinus, monitoring blood oxygen and pressure.",
    whenItGoesWrong: ["glossopharyngeal neuralgia causes severe throat pain triggered by swallowing"],
    territoryKeys: ["cranial-nerve-glossopharyngeal"] },
  { id: "cn10-vagus-cn", name: "CN X — vagus nerve", group: "cranial-nerves", system: "nervous",
    summary: "the longest cranial nerve, reaching the abdomen.",
    whatItDoes: "the main parasympathetic supply to heart, lungs and much of the gut, plus voice box motor control.",
    whenItGoesWrong: ["damage affects voice (hoarseness), swallowing, or heart rate and gut motility depending where it is injured"],
    territoryKeys: ["vagus"] },
  { id: "cn11-accessory", name: "CN XI — accessory nerve", group: "cranial-nerves", system: "nervous",
    summary: "controls two neck and shoulder muscles.",
    whatItDoes: "supplies sternocleidomastoid and trapezius, driving head turning and shoulder shrug.",
    whenItGoesWrong: ["injury (including during neck surgery) causes a drooping shoulder and weak shrug"],
    territoryKeys: ["cranial-nerve-accessory"] },
  { id: "cn12-hypoglossal", name: "CN XII — hypoglossal nerve", group: "cranial-nerves", system: "nervous",
    summary: "controls tongue movement.",
    whatItDoes: "drives nearly all the intrinsic and extrinsic muscles of the tongue.",
    whenItGoesWrong: ["one-sided damage causes the tongue to deviate toward the weak side on protrusion"],
    territoryKeys: ["cranial-nerve-hypoglossal"] },

  // ---------- brain ----------
  { id: "primary-motor-cortex", name: "primary motor cortex", group: "brain", system: "nervous",
    summary: "the strip of frontal cortex directly commanding voluntary movement.",
    whatItDoes: "organised as a body map ('motor homunculus'); its output travels down the corticospinal tract.",
    whenItGoesWrong: ["stroke or lesion here causes weakness on the opposite side of the body"],
    territoryKeys: ["frontal-lobe"] },
  { id: "primary-somatosensory-cortex", name: "primary somatosensory cortex", group: "brain", system: "nervous",
    summary: "the strip of parietal cortex receiving touch, pressure and position sense.",
    whatItDoes: "maps sensation from the opposite side of the body in proportion to its sensitivity, not its size.",
    whenItGoesWrong: ["lesions cause numbness or sensory neglect on the opposite side"],
    territoryKeys: ["parietal-lobe"] },
  { id: "primary-visual-cortex", name: "primary visual cortex", group: "brain", system: "nervous",
    summary: "the region at the back of the brain that first processes visual input.",
    whatItDoes: "maps the visual field point-for-point from the retina via the optic radiations.",
    whenItGoesWrong: ["damage causes a blind area (scotoma) in the corresponding part of vision, occipital strokes being a classic cause"],
    territoryKeys: ["occipital-lobe"] },
  { id: "primary-auditory-cortex", name: "primary auditory cortex", group: "brain", system: "nervous",
    summary: "the region in the temporal lobe that first processes sound.",
    whatItDoes: "maps sound frequency; feeds into surrounding areas for speech and music recognition.",
    whenItGoesWrong: ["bilateral damage is a rare cause of cortical deafness despite intact ears"],
    territoryKeys: ["temporal-lobe"] },
  { id: "brocas-area", name: "broca's area", group: "brain", system: "nervous",
    summary: "a frontal lobe region central to producing fluent speech.",
    whatItDoes: "coordinates the motor planning of speech and grammar.",
    whenItGoesWrong: ["damage causes broca's (expressive) aphasia: effortful, non-fluent speech with preserved comprehension"],
    territoryKeys: ["frontal-lobe"] },
  { id: "wernickes-area", name: "wernicke's area", group: "brain", system: "nervous",
    summary: "a temporal lobe region central to understanding language.",
    whatItDoes: "links heard or read words to meaning.",
    whenItGoesWrong: ["damage causes wernicke's (receptive) aphasia: fluent but nonsensical speech with poor comprehension"],
    territoryKeys: ["temporal-lobe"] },
  { id: "prefrontal-cortex", name: "prefrontal cortex", group: "brain", system: "nervous",
    summary: "the frontmost cortex, central to planning, judgement and impulse control.",
    whatItDoes: "integrates information for decision-making, working memory and social behaviour; matures last, into the mid-20s.",
    whenItGoesWrong: ["injury or disease here can change personality and judgement before it changes obvious cognition"],
    territoryKeys: ["frontal-lobe"] },
  { id: "insula", name: "insula", group: "brain", system: "nervous",
    summary: "cortex folded deep within the lateral sulcus.",
    whatItDoes: "integrates internal bodily sensation (interoception) with emotion, and contributes to taste and pain processing.",
    whenItGoesWrong: ["implicated in some forms of chronic pain and in craving states in addiction research"],
    territoryKeys: ["cerebral-cortex"] },
  { id: "cingulate-cortex", name: "cingulate cortex", group: "brain", system: "nervous",
    summary: "a band of cortex wrapping around the corpus callosum.",
    whatItDoes: "the anterior part contributes to error monitoring and the emotional aspect of pain; the posterior part supports memory and self-referential thought.",
    whenItGoesWrong: ["altered activity here is studied in chronic pain, depression and anxiety, without being diagnostic on its own"],
    territoryKeys: ["cerebral-cortex"] },
  { id: "default-mode-network", name: "default mode network", group: "brain", system: "nervous",
    summary: "a set of connected regions most active during rest and inward-directed thought.",
    whatItDoes: "supports mind-wandering, autobiographical memory and imagining the future; quiets during focused external tasks.",
    whenItGoesWrong: ["altered connectivity in this network is studied in depression and alzheimer's disease, but is a research finding, not an individual diagnostic test"],
    territoryKeys: ["cerebral-cortex"] },
  { id: "limbic-system", name: "limbic system", group: "brain", system: "nervous",
    summary: "an interconnected set of structures (hippocampus, amygdala, cingulate, hypothalamus and others) supporting emotion and memory.",
    whatItDoes: "links memory formation, emotional salience and autonomic and hormonal response together.",
    whenItGoesWrong: ["temporal lobe seizures often start in limbic structures and can produce intense emotion or déjà vu"],
    territoryKeys: ["hippocampus", "amygdala"] },
  { id: "basal-ganglia-loops", name: "basal ganglia motor loops", group: "brain", system: "nervous",
    summary: "circuits linking cortex, basal ganglia and thalamus that shape movement initiation.",
    whatItDoes: "select and scale intended movements while suppressing competing ones.",
    whenItGoesWrong: ["dopamine loss in this circuit produces the slowness and tremor of parkinson's disease"],
    territoryKeys: ["basal-ganglia"] },
  { id: "cerebellar-zones", name: "cerebellar functional zones", group: "brain", system: "nervous",
    summary: "the cerebellum's medial, intermediate and lateral zones, each with distinct roles.",
    whatItDoes: "the medial zone (vermis) coordinates posture and gait, the intermediate zone fine-tunes limb movement, and the lateral hemispheres contribute to motor planning and some cognition.",
    whenItGoesWrong: ["vermis damage causes a wide-based, unsteady gait; hemisphere damage causes limb incoordination on the same side"],
    territoryKeys: ["cerebellum"] },
  { id: "locus-coeruleus", name: "locus coeruleus", group: "brain", system: "nervous",
    summary: "a small brainstem nucleus that is the brain's main source of noradrenaline.",
    whatItDoes: "drives arousal, attention and the stress response broadly across the brain.",
    whenItGoesWrong: ["among the earliest sites of pathological change in some neurodegenerative disease, well before clinical symptoms"],
    territoryKeys: ["brainstem"] },
  { id: "raphe-nuclei", name: "raphe nuclei", group: "brain", system: "nervous",
    summary: "a chain of brainstem nuclei that are the brain's main source of serotonin.",
    whatItDoes: "modulate mood, sleep-wake cycling and pain processing broadly.",
    whenItGoesWrong: ["a target of ssri antidepressant action, though the full mechanism of depression is not fully understood"],
    territoryKeys: ["brainstem"] },
  { id: "nucleus-tractus-solitarius", name: "nucleus tractus solitarius", group: "brain", system: "nervous",
    summary: "a brainstem relay for visceral sensory information.",
    whatItDoes: "receives signal from the vagus and glossopharyngeal nerves about blood pressure, blood gases and gut state, and relays it into reflex circuits.",
    whenItGoesWrong: ["central to the reflex arcs behind vomiting, blood pressure control and breathing rate adjustment"],
    territoryKeys: ["brainstem"] },

  // ---------- spinal cord ----------
  { id: "corticospinal-tract", name: "corticospinal tract", group: "spinal-cord", system: "nervous",
    summary: "the main descending pathway for voluntary movement.",
    whatItDoes: "carries motor commands from motor cortex down to spinal motor neurons, crossing sides mostly at the medulla.",
    whenItGoesWrong: ["damage above the crossing causes opposite-side weakness; damage below causes same-side weakness"],
    territoryKeys: ["spinal-cord"] },
  { id: "dorsal-columns", name: "dorsal columns", group: "spinal-cord", system: "nervous",
    summary: "ascending tracts carrying fine touch, vibration and joint position sense.",
    whatItDoes: "carry precise, well-localised sensory information upward without crossing until the medulla.",
    whenItGoesWrong: ["damage causes loss of vibration and position sense with a wide-based, unsteady gait, classically from vitamin b12 deficiency or ms"],
    territoryKeys: ["spinal-cord"] },
  { id: "spinothalamic-tract", name: "spinothalamic tract", group: "spinal-cord", system: "nervous",
    summary: "ascending tract carrying pain and temperature sense.",
    whatItDoes: "crosses to the opposite side within a couple of spinal levels of entry, then ascends to the thalamus.",
    whenItGoesWrong: ["a lesion on one side of the cord can cause pain and temperature loss on the opposite side of the body below the lesion"],
    territoryKeys: ["spinal-cord"] },
  { id: "spinal-levels-cervical", name: "cervical spinal levels (C1–C8)", group: "spinal-cord", system: "nervous",
    summary: "the neck segment of the cord, supplying the diaphragm, arms and hands.",
    whatItDoes: "c3-c5 roots largely drive the diaphragm; lower cervical roots supply the arm and hand.",
    whenItGoesWrong: ["injury above c4 threatens independent breathing; lower cervical injury spares breathing but affects arm and hand function"],
    territoryKeys: ["spinal-cord", "vertebra"] },
  { id: "spinal-levels-thoracic", name: "thoracic spinal levels (T1–T12)", group: "spinal-cord", system: "nervous",
    summary: "the trunk segment of the cord, supplying chest and abdominal wall and sympathetic outflow.",
    whatItDoes: "carries the entire sympathetic outflow to the body, which exits only at these levels.",
    whenItGoesWrong: ["injury here typically spares arm function but affects trunk control and leg function below the level"],
    territoryKeys: ["spinal-cord", "vertebra"] },
  { id: "spinal-levels-lumbosacral", name: "lumbosacral spinal levels (L1–S5)", group: "spinal-cord", system: "nervous",
    summary: "the lower segment supplying the legs, bladder, bowel and pelvic floor.",
    whatItDoes: "the cord itself ends around L1-L2 in adults; these roots continue down as the cauda equina.",
    whenItGoesWrong: ["compression of the cauda equina causing saddle numbness or new bladder/bowel dysfunction is a surgical emergency"],
    territoryKeys: ["spinal-cord", "vertebra"] },

  // ---------- dental & oral ----------
  { id: "tooth-enamel", name: "tooth enamel", group: "dental-oral", system: "skeletal",
    summary: "the hardest tissue in the body, covering the crown of each tooth.",
    whatItDoes: "protects the tooth from mechanical and chemical wear; has no living cells and cannot regenerate once lost.",
    whenItGoesWrong: ["acid demineralisation causes cavities and, without decay, erosion"],
    territoryKeys: ["teeth"] },
  { id: "tooth-dentin", name: "dentin", group: "dental-oral", system: "skeletal",
    summary: "the layer beneath enamel making up most of the tooth's bulk.",
    whatItDoes: "living, tubular tissue that transmits sensation and can lay down secondary dentin defensively.",
    whenItGoesWrong: ["exposure (from receding gums or worn enamel) causes sensitivity to hot, cold and sweet"],
    territoryKeys: ["teeth"] },
  { id: "tooth-pulp", name: "dental pulp", group: "dental-oral", system: "nervous",
    summary: "the innermost living tissue of the tooth, with nerve and blood supply.",
    whatItDoes: "provides sensation and nourishes the tooth from within.",
    whenItGoesWrong: ["infection reaching here causes severe toothache and typically requires root canal treatment or extraction"],
    territoryKeys: ["teeth"] },
  { id: "periodontium", name: "periodontium", group: "dental-oral", system: "connective",
    summary: "the supporting apparatus of the tooth: gingiva, periodontal ligament, cementum and alveolar bone.",
    whatItDoes: "the periodontal ligament suspends the tooth in its socket and absorbs chewing forces.",
    whenItGoesWrong: ["chronic gum inflammation (periodontitis) destroys this support and is a leading cause of adult tooth loss; linked epidemiologically to cardiovascular risk"],
    territoryKeys: ["teeth"] },
  { id: "tongue-papillae", name: "tongue papillae", group: "dental-oral", system: "sensory",
    summary: "the small projections covering the tongue surface, some housing taste buds.",
    whatItDoes: "fungiform, foliate and circumvallate papillae carry taste buds; filiform papillae provide texture for manipulating food.",
    whenItGoesWrong: ["smoothing or inflammation of the tongue surface can signal nutritional deficiency (e.g. b12, iron)"],
    territoryKeys: ["upper-airway"] },
  { id: "salivary-ducts", name: "salivary gland ducts", group: "dental-oral", system: "digestive",
    summary: "the ducts carrying saliva from the parotid, submandibular and sublingual glands into the mouth.",
    whatItDoes: "deliver saliva for digestion, lubrication and antimicrobial protection of the mouth.",
    whenItGoesWrong: ["a stone lodged in a duct (sialolithiasis) causes painful gland swelling, worse with eating"],
    territoryKeys: ["salivary"] },

  // ---------- ear ----------
  { id: "outer-ear-canal", name: "external auditory canal", group: "ear", system: "sensory",
    summary: "the canal carrying sound from the outer ear to the eardrum.",
    whatItDoes: "amplifies certain sound frequencies through its resonant shape and protects the eardrum with wax and hair.",
    whenItGoesWrong: ["wax impaction or infection (otitis externa) causes conductive hearing loss or pain"],
    territoryKeys: ["middle-ear"] },
  { id: "tympanic-membrane", name: "tympanic membrane (eardrum)", group: "ear", system: "sensory",
    summary: "the thin membrane separating outer and middle ear.",
    whatItDoes: "vibrates with sound pressure and transmits that vibration to the ossicles.",
    whenItGoesWrong: ["perforation from infection or trauma causes hearing loss and risk of middle ear infection"],
    territoryKeys: ["middle-ear"] },
  { id: "ossicles", name: "ossicles (malleus, incus, stapes)", group: "ear", system: "sensory",
    summary: "the three smallest bones in the body, spanning the middle ear.",
    whatItDoes: "mechanically amplify eardrum vibration before delivering it to the fluid-filled inner ear.",
    whenItGoesWrong: ["fixation (otosclerosis) or disruption causes conductive hearing loss"],
    territoryKeys: ["middle-ear"] },
  { id: "eustachian-tube", name: "eustachian tube", group: "ear", system: "sensory",
    summary: "the tube connecting the middle ear to the back of the nose and throat.",
    whatItDoes: "equalises middle ear pressure with the atmosphere and drains middle ear secretions.",
    whenItGoesWrong: ["dysfunction causes ear fullness, popping, and predisposes to middle ear infection, common with colds and on flights"],
    territoryKeys: ["eustachian-tube"] },
  { id: "cochlea-turns", name: "cochlear turns", group: "ear", system: "sensory",
    summary: "the coiled, fluid-filled inner ear structure, wound about two and three-quarter turns.",
    whatItDoes: "the base of the coil senses high frequencies, the apex low frequencies, mapping sound tonotopically.",
    whenItGoesWrong: ["noise damage typically affects the base first, causing high-frequency hearing loss first"],
    territoryKeys: ["cochlea"] },
  { id: "cochlear-hair-cells", name: "cochlear hair cells", group: "ear", system: "sensory",
    summary: "the sensory cells of the organ of corti that convert sound vibration to nerve signal.",
    whatItDoes: "inner hair cells transmit the auditory signal; outer hair cells actively amplify and sharpen it.",
    whenItGoesWrong: ["they do not regenerate in humans once lost — the main reason noise-induced and age-related hearing loss are permanent"],
    territoryKeys: ["cochlea"] },
  { id: "vestibular-organs", name: "vestibular organs (semicircular canals, utricle, saccule)", group: "ear", system: "sensory",
    summary: "the inner ear's balance-sensing structures.",
    whatItDoes: "semicircular canals sense rotation; utricle and saccule sense linear acceleration and head tilt relative to gravity.",
    whenItGoesWrong: ["displaced calcium crystals in these structures cause benign positional vertigo; infection or inflammation causes vestibular neuritis"],
    territoryKeys: ["vestibular"] },

  // ---------- eye ----------
  { id: "cornea", name: "cornea", group: "eye", system: "sensory",
    summary: "the clear, curved front window of the eye.",
    whatItDoes: "provides most of the eye's focusing power and, with the tear film, its first protective barrier.",
    whenItGoesWrong: ["scarring or irregular shape (keratoconus) distorts vision; it is densely innervated, so injury here is very painful"],
    territoryKeys: ["eye"] },
  { id: "lens", name: "lens", group: "eye", system: "sensory",
    summary: "the transparent, adjustable structure behind the iris.",
    whatItDoes: "fine-tunes focus for near and distance vision by changing shape (accommodation).",
    whenItGoesWrong: ["progressive clouding (cataract) is near-universal with age and is treated by surgical replacement"],
    territoryKeys: ["eye"] },
  { id: "retina-layers", name: "retinal layers", group: "eye", system: "sensory",
    summary: "the ten-layered light-sensing tissue lining the back of the eye.",
    whatItDoes: "photoreceptors convert light to signal; successive layers process and relay it toward the optic nerve.",
    whenItGoesWrong: ["detachment of these layers from the underlying tissue is a sight-threatening emergency"],
    territoryKeys: ["retina"] },
  { id: "macula", name: "macula", group: "eye", system: "sensory",
    summary: "the small central area of the retina responsible for sharp, detailed vision.",
    whatItDoes: "densely packed cone photoreceptors here provide the vision used for reading and faces.",
    whenItGoesWrong: ["age-related macular degeneration damages central vision while sparing peripheral vision"],
    territoryKeys: ["retina"] },
  { id: "optic-disc", name: "optic disc", group: "eye", system: "sensory",
    summary: "the point where the optic nerve exits the retina.",
    whatItDoes: "contains no photoreceptors, creating a natural blind spot; its appearance is examined for pressure and nerve health.",
    whenItGoesWrong: ["swelling (papilloedema) can signal raised intracranial pressure; cupping is characteristic of glaucoma"],
    territoryKeys: ["retina", "optic-nerve"] },
  { id: "aqueous-humor", name: "aqueous humor", group: "eye", system: "sensory",
    summary: "the clear fluid filling the front chamber of the eye.",
    whatItDoes: "maintains eye shape and pressure and nourishes the cornea and lens, continuously produced and drained.",
    whenItGoesWrong: ["impaired drainage raises intraocular pressure, the main modifiable risk factor in glaucoma"],
    territoryKeys: ["eye"] },
  { id: "vitreous-humor", name: "vitreous humor", group: "eye", system: "sensory",
    summary: "the clear gel filling the back chamber of the eye.",
    whatItDoes: "maintains the eye's shape and keeps the retina pressed against the back wall.",
    whenItGoesWrong: ["age-related shrinkage causes floaters and can tug on and detach the retina"],
    territoryKeys: ["eye"] },
  { id: "extraocular-muscles", name: "extraocular muscles", group: "eye", system: "muscular",
    summary: "the six muscles moving each eyeball.",
    whatItDoes: "work in coordinated pairs across both eyes to allow smooth, tracked, binocular gaze.",
    whenItGoesWrong: ["imbalance causes double vision or misalignment (strabismus); autoimmune enlargement occurs in thyroid eye disease"],
    territoryKeys: ["eye"] },

  // ---------- renal ----------
  { id: "nephron", name: "nephron", group: "renal", system: "urinary",
    summary: "the kidney's basic filtering unit, about a million per kidney.",
    whatItDoes: "filters blood plasma and then reclaims most of the water, salt and nutrients as fluid moves along its length.",
    whenItGoesWrong: ["progressive nephron loss underlies chronic kidney disease, largely irreversible once lost in bulk"],
    territoryKeys: ["nephron"] },
  { id: "glomerulus", name: "glomerulus", group: "renal", system: "urinary",
    summary: "a tuft of capillaries where blood filtration begins in each nephron.",
    whatItDoes: "filters plasma under pressure, holding back blood cells and most protein while letting water and small solutes through.",
    whenItGoesWrong: ["inflammation here (glomerulonephritis) or diabetic damage lets protein and blood leak into urine"],
    territoryKeys: ["glomerulus"] },
  { id: "renal-tubules", name: "renal tubules (proximal, loop of henle, distal)", group: "renal", system: "urinary",
    summary: "the segments of the nephron beyond the glomerulus.",
    whatItDoes: "reclaim most filtered water, glucose and salt, and fine-tune the final urine's concentration and composition.",
    whenItGoesWrong: ["specific segment damage (e.g. from toxins) produces recognisable electrolyte or concentrating disturbances"],
    territoryKeys: ["nephron"] },
  { id: "collecting-duct", name: "collecting duct", group: "renal", system: "urinary",
    summary: "the final shared tube through which urine from many nephrons passes.",
    whatItDoes: "under hormonal control (antidiuretic hormone), fine-tunes final urine concentration.",
    whenItGoesWrong: ["resistance to that hormone here causes diabetes insipidus, with large volumes of dilute urine"],
    territoryKeys: ["collecting-duct"] },
  { id: "juxtaglomerular-apparatus", name: "juxtaglomerular apparatus", group: "renal", system: "urinary",
    summary: "a specialised cluster of cells where the nephron's tubule meets its own arterioles.",
    whatItDoes: "senses blood pressure and salt delivery and releases renin, starting the hormone cascade that regulates blood pressure.",
    whenItGoesWrong: ["a key target of several classes of blood pressure medication"],
    territoryKeys: ["juxtaglomerular-apparatus"] },

  // ---------- biliary ----------
  { id: "intrahepatic-bile-ducts", name: "intrahepatic bile ducts", group: "biliary", system: "digestive",
    summary: "the small ducts collecting bile from liver cells inside the liver.",
    whatItDoes: "merge progressively into larger ducts that eventually leave the liver.",
    whenItGoesWrong: ["autoimmune destruction of small ducts causes primary biliary cholangitis"],
    territoryKeys: ["gallbladder", "liver"] },
  { id: "common-bile-duct", name: "common bile duct", group: "biliary", system: "digestive",
    summary: "the duct carrying bile from liver and gallbladder to the duodenum.",
    whatItDoes: "joins the pancreatic duct just before entering the duodenum at the sphincter of oddi.",
    whenItGoesWrong: ["a gallstone lodged here causes obstructive jaundice and can trigger pancreatitis"],
    territoryKeys: ["gallbladder", "duodenum"] },
  { id: "gallbladder-detail", name: "gallbladder", group: "biliary", system: "digestive",
    summary: "a small sac beneath the liver that stores and concentrates bile.",
    whatItDoes: "releases stored, concentrated bile into the duodenum in response to a fatty meal.",
    whenItGoesWrong: ["gallstones form when bile composition favours crystallisation, causing pain after fatty food or acute inflammation"],
    territoryKeys: ["gallbladder"] },

  // ---------- lymphatic drainage / immune ----------
  { id: "lymph-node-cortex", name: "lymph node cortex", group: "immune", system: "lymphatic",
    summary: "the outer region of a lymph node, packed with b-cell follicles.",
    whatItDoes: "b lymphocytes here mature and mount antibody responses to antigens filtered from lymph.",
    whenItGoesWrong: ["reactive enlargement is a normal response to nearby infection; persistent, painless enlargement warrants evaluation"],
    territoryKeys: ["lymph-nodes"] },
  { id: "thymus-detail", name: "thymus", group: "immune", system: "lymphatic",
    summary: "a gland behind the sternum, most active in childhood.",
    whatItDoes: "trains developing t-cells to recognise the body's own tissue as safe before releasing them into circulation.",
    whenItGoesWrong: ["shrinks (involutes) with age, one reason immune response weakens later in life"],
    territoryKeys: ["thymus"] },
  { id: "splenic-white-pulp", name: "splenic white pulp", group: "immune", system: "lymphatic",
    summary: "the immune tissue component of the spleen, distinct from its red, blood-filtering pulp.",
    whatItDoes: "mounts antibody responses to blood-borne antigens, particularly encapsulated bacteria.",
    whenItGoesWrong: ["after splenectomy, susceptibility to certain bacterial infections rises, which is why vaccination is recommended beforehand"],
    territoryKeys: ["spleen"] },
  { id: "malt-galt", name: "mucosa-associated lymphoid tissue (MALT/GALT)", group: "immune", system: "lymphatic",
    summary: "immune tissue embedded directly in the gut, airway and other mucosal linings.",
    whatItDoes: "provides the first line of adaptive immune response where the body meets the outside world in greatest volume — the gut.",
    whenItGoesWrong: ["a site of origin for certain lymphomas (e.g. gastric malt lymphoma), often linked to chronic infection"],
    territoryKeys: ["small-intestine", "colon"] },
  { id: "tonsils", name: "tonsils (palatine, pharyngeal, lingual)", group: "immune", system: "lymphatic",
    summary: "a ring of lymphoid tissue at the back of the throat.",
    whatItDoes: "samples inhaled and swallowed antigens early, especially important in childhood immune development.",
    whenItGoesWrong: ["recurrent bacterial infection or marked enlargement obstructing breathing are the usual reasons for removal"],
    territoryKeys: ["upper-airway"] },
  { id: "axillary-node-chain", name: "axillary lymph node chain", group: "lymphatic-drainage", system: "lymphatic",
    summary: "the lymph nodes in the armpit draining the breast and arm.",
    whatItDoes: "the primary drainage route for the breast, meaning it is examined closely in breast cancer staging.",
    whenItGoesWrong: ["node enlargement here can reflect infection, or be the first sign of breast cancer spread"],
    territoryKeys: ["lymph-nodes"] },
  { id: "inguinal-node-chain", name: "inguinal lymph node chain", group: "lymphatic-drainage", system: "lymphatic",
    summary: "the lymph nodes in the groin draining the leg, lower abdominal wall and external genitalia.",
    whatItDoes: "the first filtering point for infection or spread from the leg and external genital region.",
    whenItGoesWrong: ["reactive swelling here is common and usually benign, tracking a leg or genital source"],
    territoryKeys: ["lymph-nodes"] },
  { id: "cervical-node-chain", name: "cervical lymph node chain", group: "lymphatic-drainage", system: "lymphatic",
    summary: "the lymph nodes of the neck draining the head, throat and thyroid.",
    whatItDoes: "the first filtering point for most head and neck infection.",
    whenItGoesWrong: ["tender enlargement usually tracks a throat or ear infection; painless, firm enlargement warrants closer evaluation"],
    territoryKeys: ["lymph-nodes"] },

  // ---------- endocrine axes ----------
  { id: "hpa-axis-tissue", name: "hypothalamic-pituitary-adrenal axis", group: "endocrine-axes", system: "endocrine",
    summary: "the hypothalamus, pituitary and adrenal glands acting as one feedback loop.",
    whatItDoes: "governs the body's cortisol-driven stress response, with each gland monitoring and adjusting the one before it.",
    whenItGoesWrong: ["chronic activation is linked to sleep disruption, blood pressure and metabolic changes; primary failure at any level causes distinct patterns of adrenal insufficiency"],
    territoryKeys: ["hypothalamus", "pituitary", "adrenal"] },
  { id: "hpt-axis-tissue", name: "hypothalamic-pituitary-thyroid axis", group: "endocrine-axes", system: "endocrine",
    summary: "the hypothalamus, pituitary and thyroid gland acting as one feedback loop.",
    whatItDoes: "governs metabolic rate; the pituitary raises or lowers thyroid-stimulating hormone in response to circulating thyroid hormone levels.",
    whenItGoesWrong: ["dysfunction at the thyroid itself is far more common clinically than dysfunction at the pituitary or hypothalamic level"],
    territoryKeys: ["hypothalamus", "pituitary", "thyroid"] },
  { id: "hpg-axis-tissue", name: "hypothalamic-pituitary-gonadal axis", group: "endocrine-axes", system: "endocrine",
    summary: "the hypothalamus, pituitary and ovaries or testes acting as one feedback loop.",
    whatItDoes: "governs puberty, the menstrual cycle and reproductive hormone levels through pulsatile signalling.",
    whenItGoesWrong: ["disruption anywhere in the loop can cause irregular cycles, infertility or abnormal puberty timing"],
    territoryKeys: ["hypothalamus", "pituitary"] },
  { id: "pancreatic-islets", name: "pancreatic islets (islets of langerhans)", group: "endocrine-axes", system: "endocrine",
    summary: "clusters of hormone-producing cells scattered through the pancreas.",
    whatItDoes: "beta cells release insulin and alpha cells release glucagon, jointly setting blood glucose.",
    whenItGoesWrong: ["autoimmune destruction of beta cells causes type 1 diabetes; progressive beta cell exhaustion contributes to type 2"],
    territoryKeys: ["pancreas"] },

  // ---------- mammary ----------
  { id: "mammary-lobules", name: "mammary lobules", group: "mammary", system: "reproductive", sex: "female",
    summary: "the milk-producing units of the breast, clustered in lobes.",
    whatItDoes: "produce milk during lactation under hormonal control, largely inactive otherwise.",
    whenItGoesWrong: ["most breast cancers arise from the cells lining these lobules or their ducts"],
    territoryKeys: ["mammary-gland"] },
  { id: "mammary-ducts", name: "mammary ducts", group: "mammary", system: "reproductive", sex: "female",
    summary: "the branching tubes carrying milk from lobules to the nipple.",
    whatItDoes: "converge toward the nipple, widening into small reservoirs just beneath it.",
    whenItGoesWrong: ["duct dilation and inflammation can cause nipple discharge; ductal carcinoma in situ is contained within this system"],
    territoryKeys: ["mammary-gland"] },
  { id: "nipple-areolar-complex", name: "nipple-areolar complex", group: "mammary", system: "reproductive", sex: "female",
    summary: "the pigmented nipple and surrounding areola.",
    whatItDoes: "delivers milk during breastfeeding; the areola's small glands lubricate and protect the skin during nursing.",
    whenItGoesWrong: ["new nipple retraction, discharge or skin change warrants prompt clinical evaluation"],
    territoryKeys: ["nipple-areolar-complex"] },
  { id: "axillary-tail-breast", name: "axillary tail of the breast", group: "mammary", system: "reproductive", sex: "female",
    summary: "an extension of breast tissue reaching toward the armpit.",
    whatItDoes: "normal breast tissue that can be mistaken for a lump if not recognised.",
    whenItGoesWrong: ["shares the same drainage and cancer risk as the rest of the breast"],
    territoryKeys: ["mammary-gland", "lymph-nodes"] },

  // ---------- female reproductive ----------
  { id: "ovary", name: "ovary", group: "female-reproductive", system: "reproductive", sex: "female",
    summary: "the paired organ producing eggs and the hormones estrogen and progesterone.",
    whatItDoes: "releases one egg roughly monthly during reproductive years and drives the hormonal cycle behind menstruation.",
    whenItGoesWrong: ["cysts are common and usually benign; declining function marks the transition to menopause"],
    territoryKeys: ["ovary"] },
  { id: "ovarian-follicles", name: "ovarian follicles", group: "female-reproductive", system: "reproductive", sex: "female",
    summary: "the fluid-filled structures within the ovary, each containing a developing egg.",
    whatItDoes: "a cohort matures each cycle; typically one dominant follicle ovulates while the rest regress.",
    whenItGoesWrong: ["polycystic ovary syndrome is associated with many small follicles that fail to mature and ovulate regularly"],
    territoryKeys: ["ovary"] },
  { id: "fallopian-tube", name: "fallopian tube", group: "female-reproductive", system: "reproductive", sex: "female",
    summary: "the paired tube connecting each ovary to the uterus.",
    whatItDoes: "sweeps the released egg inward and is the usual site of fertilisation.",
    whenItGoesWrong: ["scarring from infection can block it, causing infertility or raising ectopic pregnancy risk"],
    territoryKeys: ["fallopian-tube"] },
  { id: "uterus-endometrium", name: "endometrium", group: "female-reproductive", system: "reproductive", sex: "female",
    summary: "the inner lining of the uterus.",
    whatItDoes: "thickens each cycle to prepare for possible implantation, and sheds as the menstrual period if pregnancy does not occur.",
    whenItGoesWrong: ["endometriosis occurs when similar tissue grows outside the uterus; endometrial thickening after menopause warrants evaluation"],
    territoryKeys: ["uterus"] },
  { id: "uterus-myometrium", name: "myometrium", group: "female-reproductive", system: "reproductive", sex: "female",
    summary: "the thick muscular wall of the uterus.",
    whatItDoes: "contracts during labour and menstruation and holds the uterus's structural shape.",
    whenItGoesWrong: ["benign fibroids growing within this muscle are extremely common and can cause heavy bleeding or pressure"],
    territoryKeys: ["uterus"] },
  { id: "cervix", name: "cervix", group: "female-reproductive", system: "reproductive", sex: "female",
    summary: "the narrow lower part of the uterus opening into the vagina.",
    whatItDoes: "its mucus changes through the cycle to control sperm passage, and it dilates during labour.",
    whenItGoesWrong: ["hpv-driven changes here are why cervical screening exists; it is one of the most preventable cancers when screened"],
    territoryKeys: ["cervix"] },
  { id: "vagina", name: "vagina", group: "female-reproductive", system: "reproductive", sex: "female",
    summary: "the muscular canal connecting the cervix to the external genitalia.",
    whatItDoes: "maintains an acidic, lactobacillus-dominated environment that resists infection; the birth canal.",
    whenItGoesWrong: ["disruption of its normal flora (e.g. after antibiotics) predisposes to bacterial vaginosis or yeast overgrowth"],
    territoryKeys: ["vagina"] },
  { id: "vulva", name: "vulva (labia, clitoris, vestibule)", group: "female-reproductive", system: "reproductive", sex: "female",
    summary: "the external female genital structures.",
    whatItDoes: "the labia and vestibule protect the vaginal and urethral openings; the clitoris is densely innervated erectile tissue.",
    whenItGoesWrong: ["chronic skin conditions (e.g. lichen sclerosus) can affect this area and merit dedicated evaluation, not self-diagnosis"],
    territoryKeys: ["vulva"] },
  { id: "pelvic-floor-female", name: "pelvic floor", group: "female-reproductive", system: "muscular", sex: "female",
    summary: "the sling of muscles supporting the pelvic organs from below.",
    whatItDoes: "supports bladder, uterus and rectum, and controls continence, stretched significantly during vaginal delivery.",
    whenItGoesWrong: ["weakness contributes to pelvic organ prolapse and stress urinary incontinence"],
    territoryKeys: ["pelvic-floor"] },
  { id: "broad-ligament", name: "broad ligament", group: "female-reproductive", system: "reproductive", sex: "female",
    summary: "a fold of peritoneum draping over the uterus, tubes and ovaries.",
    whatItDoes: "provides a passive fold of support and a conduit for the vessels and nerves reaching these organs.",
    whenItGoesWrong: ["not itself a common site of primary disease, but relevant surgical landmark for pelvic procedures"],
    territoryKeys: ["broad-ligament"] },
  { id: "round-ligament", name: "round ligament of the uterus", group: "female-reproductive", system: "reproductive", sex: "female",
    summary: "a fibromuscular cord running from the uterus to the labia majora.",
    whatItDoes: "helps hold the uterus in its forward-tilted position.",
    whenItGoesWrong: ["stretching of this ligament in pregnancy causes a common sharp groin pain (round ligament pain)"],
    territoryKeys: ["round-ligament"] },

  // ---------- male reproductive ----------
  { id: "testis-detail", name: "testis", group: "male-reproductive", system: "reproductive", sex: "male",
    summary: "the paired organ producing sperm and testosterone.",
    whatItDoes: "seminiferous tubules produce sperm continuously; leydig cells between them produce testosterone.",
    whenItGoesWrong: ["sudden severe pain can indicate testicular torsion, a time-critical surgical emergency"],
    territoryKeys: ["testis"] },
  { id: "epididymis", name: "epididymis", group: "male-reproductive", system: "reproductive", sex: "male",
    summary: "a coiled tube sitting against each testis.",
    whatItDoes: "stores and matures sperm, giving them the ability to swim and fertilise, before ejaculation.",
    whenItGoesWrong: ["infection here (epididymitis) causes gradual-onset scrotal pain and swelling, distinguishing it from torsion's sudden onset"],
    territoryKeys: ["testis"] },
  { id: "vas-deferens", name: "vas deferens", group: "male-reproductive", system: "reproductive", sex: "male",
    summary: "the muscular tube carrying sperm from epididymis toward the urethra.",
    whatItDoes: "propels sperm forward by peristaltic contraction during ejaculation.",
    whenItGoesWrong: ["surgically cut and sealed in a vasectomy for permanent contraception"],
    territoryKeys: ["vas-deferens"] },
  { id: "seminal-vesicles", name: "seminal vesicles", group: "male-reproductive", system: "reproductive", sex: "male",
    summary: "paired glands behind the bladder contributing most of the fluid volume of semen.",
    whatItDoes: "secrete a fructose-rich fluid that nourishes and helps transport sperm.",
    whenItGoesWrong: ["inflammation can contribute to pelvic pain syndromes and occasionally blood in semen"],
    territoryKeys: ["seminal-vesicle"] },
  { id: "prostate-zones", name: "prostate zones", group: "male-reproductive", system: "reproductive", sex: "male",
    summary: "the peripheral, transition and central zones of the prostate gland.",
    whatItDoes: "adds fluid to semen; the transition zone tends to enlarge with age, the peripheral zone is where most cancers arise.",
    whenItGoesWrong: ["benign transition-zone enlargement causes urinary symptoms with age; peripheral zone cancers are often silent until advanced, which is why screening discussions matter"],
    territoryKeys: ["prostate"] },
  { id: "penis-structures", name: "penis (corpora cavernosa, corpus spongiosum, urethra)", group: "male-reproductive", system: "reproductive", sex: "male",
    summary: "the external male organ, containing erectile tissue and the urethra.",
    whatItDoes: "the paired corpora cavernosa engorge with blood for erection; the corpus spongiosum surrounds and protects the urethra during erection.",
    whenItGoesWrong: ["erectile dysfunction can be an early marker of vascular disease elsewhere in the body, not only a local issue"],
    territoryKeys: ["penis"] },
  { id: "scrotum", name: "scrotum", group: "male-reproductive", system: "reproductive", sex: "male",
    summary: "the skin and muscle pouch holding the testes outside the body cavity.",
    whatItDoes: "its muscle (cremaster, dartos) adjusts testicular position to keep sperm production a few degrees below core body temperature.",
    whenItGoesWrong: ["any new painless lump here should be evaluated promptly to rule out testicular cancer, most curable when caught early"],
    territoryKeys: ["scrotum"] },
];
