// herbal and supplement layer. every entry carries an evidence tier, the tissue it acts on,
// and the interactions that make it unsafe alongside common medication. nothing here is a
// prescription, and a herb with thin evidence is labelled as such rather than dressed up.
import type { Finding } from "./model";
import { findDrug } from "./medications";

export type EvidenceTier = "clinical-trials" | "mixed" | "traditional-only";

export type Tradition =
  | "western herbal"
  | "ayurveda"
  | "traditional chinese"
  | "unani"
  | "indigenous north american"
  | "african traditional"
  | "japanese kampo";

export interface HerbDef {
  key: string;
  label: string;
  latin: string;
  tradition: Tradition;
  /** active constituents thought to carry the effect. */
  constituents: string[];
  territoryKeys: string[];
  /** what it is traditionally or clinically used for. */
  uses: string[];
  mechanism: string;
  evidence: EvidenceTier;
  evidenceNote: string;
  /** drug keys from medications.ts that interact. */
  interactsWith: string[];
  interactionNote?: string;
  contraindications: string[];
  typicalForm: string;
}

export const HERBS: HerbDef[] = [
  {
    key: "turmeric",
    label: "turmeric",
    latin: "curcuma longa",
    tradition: "western herbal",
    constituents: ["curcumin", "demethoxycurcumin", "bisdemethoxycurcumin"],
    territoryKeys: ["liver", "cartilage", "colon"],
    uses: ["joint discomfort", "digestive comfort"],
    mechanism: "curcuminoids modulate nf-κb signalling; oral bioavailability is low without piperine or a lipid carrier.",
    evidence: "mixed",
    evidenceNote: "small trials show modest joint symptom benefit; effect sizes are inconsistent across preparations.",
    interactsWith: ["warfarin", "apixaban"],
    interactionNote: "mild antiplatelet effect adds to anticoagulants.",
    contraindications: ["active gallstone obstruction", "planned surgery within two weeks"],
    typicalForm: "standardised extract with a bioavailability enhancer.",
  },
  {
    key: "ginger",
    label: "ginger",
    latin: "zingiber officinale",
    tradition: "western herbal",
    constituents: ["gingerols", "shogaols"],
    territoryKeys: ["stomach", "small-intestine", "vestibular"],
    uses: ["nausea", "motion sickness", "digestive comfort"],
    mechanism: "gingerols accelerate gastric emptying and dampen vagal nausea signalling.",
    evidence: "clinical-trials",
    evidenceNote: "consistent benefit for pregnancy and postoperative nausea in randomised trials.",
    interactsWith: ["warfarin"],
    contraindications: ["active peptic ulcer"],
    typicalForm: "dried root, capsule or tea.",
  },
  {
    key: "ashwagandha",
    label: "ashwagandha",
    latin: "withania somnifera",
    tradition: "western herbal",
    constituents: ["withanolides", "withaferin a"],
    territoryKeys: ["adrenal", "hypothalamus", "thyroid"],
    uses: ["stress tolerance", "sleep onset"],
    mechanism: "withanolides modulate hpa axis output; several trials show reduced evening cortisol.",
    evidence: "mixed",
    evidenceNote: "short trials show cortisol and stress-scale changes; long-term safety data is limited, and liver injury case reports exist.",
    interactsWith: ["levothyroxine", "sertraline"],
    interactionNote: "can raise thyroid hormone levels and add sedation.",
    contraindications: ["pregnancy", "autoimmune thyroid disease", "existing liver disease"],
    typicalForm: "root extract, evening dose.",
  },
  {
    key: "st-johns-wort",
    label: "st john's wort",
    latin: "hypericum perforatum",
    tradition: "western herbal",
    constituents: ["hyperforin", "hypericin"],
    territoryKeys: ["liver", "brainstem", "hippocampus"],
    uses: ["low mood"],
    mechanism: "hyperforin inhibits monoamine reuptake and strongly induces cyp3a4 and p-glycoprotein in the liver.",
    evidence: "clinical-trials",
    evidenceNote: "effective for mild to moderate depression in trials — and the single most dangerous interacting herb in common use.",
    interactsWith: ["sertraline", "warfarin", "apixaban", "atorvastatin"],
    interactionNote: "induces hepatic clearance of many drugs, including contraceptives, transplant immunosuppressants and anticoagulants, and stacks serotonergically with ssris.",
    contraindications: ["any prescription medication without pharmacist review", "pregnancy"],
    typicalForm: "standardised hypericin extract.",
  },
  {
    key: "valerian",
    label: "valerian",
    latin: "valeriana officinalis",
    tradition: "western herbal",
    constituents: ["valerenic acid", "valepotriates"],
    territoryKeys: ["brainstem", "hypothalamus"],
    uses: ["sleep onset"],
    mechanism: "valerenic acid modulates gaba-a receptor signalling.",
    evidence: "mixed",
    evidenceNote: "subjective sleep improvement in some trials, little objective change in sleep architecture.",
    interactsWith: ["gabapentin", "sertraline"],
    contraindications: ["driving after dosing", "combination with alcohol or sedatives"],
    typicalForm: "root extract taken 60 minutes before bed.",
  },
  {
    key: "chamomile",
    label: "chamomile",
    latin: "matricaria chamomilla",
    tradition: "western herbal",
    constituents: ["apigenin", "bisabolol"],
    territoryKeys: ["stomach", "small-intestine", "brainstem"],
    uses: ["digestive settling", "mild anxiety"],
    mechanism: "apigenin binds benzodiazepine sites weakly; local antispasmodic effect on gut smooth muscle.",
    evidence: "mixed",
    evidenceNote: "modest anxiolytic signal in small trials.",
    interactsWith: ["warfarin"],
    contraindications: ["asteraceae allergy"],
    typicalForm: "infusion of the dried flower.",
  },
  {
    key: "peppermint",
    label: "peppermint oil",
    latin: "mentha × piperita",
    tradition: "western herbal",
    constituents: ["menthol", "menthone"],
    territoryKeys: ["colon", "small-intestine", "oesophagus"],
    uses: ["irritable bowel cramping"],
    mechanism: "menthol blocks calcium channels in intestinal smooth muscle, reducing spasm.",
    evidence: "clinical-trials",
    evidenceNote: "enteric-coated peppermint oil has repeatedly beaten placebo for ibs abdominal pain.",
    interactsWith: ["omeprazole"],
    interactionNote: "acid suppression can dissolve enteric coating early, causing reflux.",
    contraindications: ["hiatus hernia with reflux", "gallstone obstruction"],
    typicalForm: "enteric-coated capsule before meals.",
  },
  {
    key: "milk-thistle",
    label: "milk thistle",
    latin: "silybum marianum",
    tradition: "western herbal",
    constituents: ["silymarin", "silybin"],
    territoryKeys: ["liver", "gallbladder"],
    uses: ["liver support"],
    mechanism: "silymarin stabilises hepatocyte membranes and raises intracellular glutathione in laboratory models.",
    evidence: "mixed",
    evidenceNote: "no convincing effect on hard liver outcomes in humans despite strong laboratory rationale.",
    interactsWith: ["atorvastatin", "warfarin"],
    contraindications: ["asteraceae allergy"],
    typicalForm: "standardised silymarin extract.",
  },
  {
    key: "hawthorn",
    label: "hawthorn",
    latin: "crataegus monogyna",
    tradition: "western herbal",
    constituents: ["oligomeric proanthocyanidins", "vitexin"],
    territoryKeys: ["heart", "coronary", "peripheral-arteries"],
    uses: ["cardiac tonic in traditional use"],
    mechanism: "flavonoids show mild positive inotropic and vasodilatory activity.",
    evidence: "mixed",
    evidenceNote: "symptomatic benefit in mild heart failure trials; not a replacement for cardiac medication.",
    interactsWith: ["metoprolol", "lisinopril", "amlodipine"],
    interactionNote: "adds to blood pressure lowering.",
    contraindications: ["diagnosed heart failure without cardiology oversight"],
    typicalForm: "leaf and flower extract.",
  },
  {
    key: "ginkgo",
    label: "ginkgo",
    latin: "ginkgo biloba",
    tradition: "western herbal",
    constituents: ["ginkgolides", "bilobalide", "flavone glycosides"],
    territoryKeys: ["cerebral-arteries", "cochlea", "peripheral-arteries"],
    uses: ["circulation", "tinnitus", "memory"],
    mechanism: "terpene lactones inhibit platelet activating factor and modestly increase microvascular flow.",
    evidence: "mixed",
    evidenceNote: "large prevention trials found no cognitive protection; small tinnitus and claudication signals persist.",
    interactsWith: ["warfarin", "apixaban", "ibuprofen"],
    interactionNote: "raises bleeding risk, including intracranial bleeding in case reports.",
    contraindications: ["anticoagulation", "seizure disorder", "surgery within two weeks"],
    typicalForm: "standardised 24% flavone glycoside extract.",
  },
  {
    key: "garlic",
    label: "garlic",
    latin: "allium sativum",
    tradition: "western herbal",
    constituents: ["allicin", "ajoene"],
    territoryKeys: ["peripheral-arteries", "coronary", "liver"],
    uses: ["blood pressure", "lipids"],
    mechanism: "allicin derivatives promote nitric oxide availability and mildly inhibit platelet aggregation.",
    evidence: "mixed",
    evidenceNote: "small but real blood pressure reductions in meta-analyses; lipid effects are marginal.",
    interactsWith: ["warfarin", "apixaban"],
    contraindications: ["surgery within two weeks"],
    typicalForm: "aged extract or fresh clove.",
  },
  {
    key: "echinacea",
    label: "echinacea",
    latin: "echinacea purpurea",
    tradition: "western herbal",
    constituents: ["alkylamides", "cichoric acid"],
    territoryKeys: ["lymph-nodes", "upper-airway", "lymphatic"],
    uses: ["upper respiratory infection duration"],
    mechanism: "alkylamides modulate innate immune cell signalling.",
    evidence: "mixed",
    evidenceNote: "meta-analyses show at best a modest reduction in cold duration; preparation quality varies enormously.",
    interactsWith: ["prednisone"],
    interactionNote: "theoretical opposition to immunosuppressive therapy.",
    contraindications: ["autoimmune disease on immunosuppression", "asteraceae allergy"],
    typicalForm: "aerial part tincture at symptom onset.",
  },
  {
    key: "elderberry",
    label: "elderberry",
    latin: "sambucus nigra",
    tradition: "western herbal",
    constituents: ["anthocyanins", "flavonoids"],
    territoryKeys: ["upper-airway", "lymphatic"],
    uses: ["cold and influenza symptoms"],
    mechanism: "anthocyanins show antiviral activity in vitro; clinical mechanism is not established.",
    evidence: "mixed",
    evidenceNote: "small trials suggest shorter symptom duration; independent replication is thin.",
    interactsWith: ["prednisone"],
    contraindications: ["raw or unripe berries are toxic"],
    typicalForm: "prepared syrup or extract.",
  },
  {
    key: "rhodiola",
    label: "rhodiola",
    latin: "rhodiola rosea",
    tradition: "western herbal",
    constituents: ["rosavins", "salidroside"],
    territoryKeys: ["adrenal", "frontal-lobe", "muscle"],
    uses: ["fatigue", "stress tolerance"],
    mechanism: "rosavins and salidroside influence monoamine turnover and cellular stress response.",
    evidence: "mixed",
    evidenceNote: "small fatigue trials are positive but methodologically weak.",
    interactsWith: ["sertraline"],
    contraindications: ["bipolar disorder", "pregnancy"],
    typicalForm: "standardised root extract, morning dose.",
  },
  {
    key: "berberine",
    label: "berberine",
    latin: "berberis vulgaris",
    tradition: "western herbal",
    constituents: ["berberine alkaloid"],
    territoryKeys: ["liver", "pancreas", "colon", "small-intestine"],
    uses: ["glucose regulation", "lipids"],
    mechanism: "activates ampk and alters the gut microbiome; the metabolic effect is genuinely pharmacological.",
    evidence: "clinical-trials",
    evidenceNote: "meaningful hba1c and lipid reductions in trials — which is exactly why it must not be stacked casually with diabetes medication.",
    interactsWith: ["metformin", "insulin", "atorvastatin", "warfarin"],
    interactionNote: "additive glucose lowering, and cyp3a4 inhibition raises other drug levels.",
    contraindications: ["pregnancy", "breastfeeding", "neonates"],
    typicalForm: "divided doses with meals.",
  },
  {
    key: "cinnamon",
    label: "cinnamon (cassia)",
    latin: "cinnamomum cassia",
    tradition: "western herbal",
    constituents: ["cinnamaldehyde", "coumarin"],
    territoryKeys: ["liver", "pancreas"],
    uses: ["glucose regulation"],
    mechanism: "polyphenols mildly improve insulin sensitivity in some studies.",
    evidence: "mixed",
    evidenceNote: "inconsistent glucose effects; cassia contains coumarin, which is hepatotoxic at high sustained intake.",
    interactsWith: ["metformin", "warfarin"],
    contraindications: ["liver disease", "high-dose long-term use of cassia rather than ceylon"],
    typicalForm: "ceylon cinnamon preferred for regular use.",
  },
  {
    key: "saw-palmetto",
    label: "saw palmetto",
    latin: "serenoa repens",
    tradition: "western herbal",
    constituents: ["fatty acids", "phytosterols"],
    territoryKeys: ["prostate", "bladder"],
    uses: ["urinary symptoms of prostate enlargement"],
    mechanism: "weak 5-alpha reductase inhibition and anti-inflammatory activity in prostatic tissue.",
    evidence: "clinical-trials",
    evidenceNote: "the largest well-designed trials found no benefit over placebo, despite widespread use.",
    interactsWith: ["warfarin", "apixaban"],
    contraindications: ["it lowers psa, which can mask a rising trend — tell whoever orders your psa"],
    typicalForm: "lipidosterolic extract.",
  },
  {
    key: "nettle",
    label: "nettle root",
    latin: "urtica dioica",
    tradition: "western herbal",
    constituents: ["lignans", "scopoletin"],
    territoryKeys: ["prostate", "kidney", "cartilage"],
    uses: ["urinary flow", "joint discomfort"],
    mechanism: "lignans bind sex hormone binding globulin; mild diuretic activity.",
    evidence: "traditional-only",
    evidenceNote: "long traditional use, little controlled evidence.",
    interactsWith: ["furosemide", "lisinopril"],
    interactionNote: "additive diuresis and potassium shift.",
    contraindications: ["advanced kidney disease"],
    typicalForm: "root extract or infusion.",
  },
  {
    key: "dandelion",
    label: "dandelion",
    latin: "taraxacum officinale",
    tradition: "western herbal",
    constituents: ["taraxasterol", "chicoric acid"],
    territoryKeys: ["liver", "gallbladder", "kidney"],
    uses: ["bile flow", "mild diuresis"],
    mechanism: "bitter compounds stimulate bile secretion; high potassium content accompanies the diuretic effect.",
    evidence: "traditional-only",
    evidenceNote: "traditional use only; no meaningful clinical trial base.",
    interactsWith: ["furosemide", "lisinopril"],
    contraindications: ["biliary obstruction", "advanced kidney disease"],
    typicalForm: "leaf infusion or root decoction.",
  },
  {
    key: "licorice",
    label: "liquorice root",
    latin: "glycyrrhiza glabra",
    tradition: "western herbal",
    constituents: ["glycyrrhizin", "glabridin"],
    territoryKeys: ["stomach", "adrenal", "kidney", "heart"],
    uses: ["gastric mucosal comfort", "adrenal support in traditional use"],
    mechanism: "glycyrrhizin inhibits 11-beta-hsd2, producing sodium retention, potassium loss and hypertension with sustained intake.",
    evidence: "mixed",
    evidenceNote: "deglycyrrhizinated forms avoid the mineralocorticoid effect; standard liquorice does not.",
    interactsWith: ["furosemide", "prednisone", "lisinopril", "metoprolol"],
    interactionNote: "potassium depletion compounds with diuretics and steroids.",
    contraindications: ["hypertension", "heart failure", "low potassium", "pregnancy"],
    typicalForm: "deglycyrrhizinated chewable for gastric use.",
  },
  {
    key: "aloe",
    label: "aloe vera (inner leaf)",
    latin: "aloe barbadensis",
    tradition: "western herbal",
    constituents: ["acemannan", "polysaccharides"],
    territoryKeys: ["stomach", "colon", "skin"],
    uses: ["gastric comfort", "topical skin repair"],
    mechanism: "polysaccharides support mucosal repair; whole-leaf latex is a stimulant laxative and is a different product entirely.",
    evidence: "mixed",
    evidenceNote: "reasonable topical evidence; oral evidence is weak and latex-containing products cause electrolyte loss.",
    interactsWith: ["furosemide", "warfarin"],
    contraindications: ["pregnancy", "inflammatory bowel disease"],
    typicalForm: "inner leaf gel, latex-free.",
  },
  {
    key: "green-tea",
    label: "green tea extract",
    latin: "camellia sinensis",
    tradition: "western herbal",
    constituents: ["egcg", "catechins"],
    territoryKeys: ["liver", "peripheral-arteries", "colon"],
    uses: ["metabolic support", "antioxidant intake"],
    mechanism: "egcg modulates lipid handling and endothelial function.",
    evidence: "mixed",
    evidenceNote: "drinking the tea is well tolerated; concentrated egcg extracts have caused idiosyncratic liver injury.",
    interactsWith: ["warfarin", "atorvastatin"],
    contraindications: ["existing liver disease", "high-dose extract on an empty stomach"],
    typicalForm: "brewed tea preferred over concentrated extract.",
  },
  {
    key: "red-yeast-rice",
    label: "red yeast rice",
    latin: "monascus purpureus",
    tradition: "western herbal",
    constituents: ["monacolin k"],
    territoryKeys: ["liver", "muscle", "coronary"],
    uses: ["cholesterol"],
    mechanism: "contains monacolin k, which is chemically identical to lovastatin.",
    evidence: "clinical-trials",
    evidenceNote: "it lowers ldl because it is a statin; the dose is unregulated and varies between batches.",
    interactsWith: ["atorvastatin", "warfarin"],
    interactionNote: "taking it with a prescribed statin is a double dose of the same drug class.",
    contraindications: ["existing statin therapy", "liver disease", "pregnancy"],
    typicalForm: "avoid unless a clinician is monitoring liver enzymes and ck.",
  },
  {
    key: "magnesium-glycinate",
    label: "magnesium glycinate",
    latin: "supplement",
    tradition: "western herbal",
    constituents: ["magnesium bisglycinate"],
    territoryKeys: ["muscle", "heart", "peripheral-nerve", "brainstem"],
    uses: ["muscle cramp", "sleep quality"],
    mechanism: "replaces a cation used in over 300 enzymatic reactions and in nmda channel gating.",
    evidence: "mixed",
    evidenceNote: "clear benefit when genuinely deficient; unremarkable otherwise.",
    interactsWith: ["furosemide"],
    contraindications: ["advanced kidney disease — magnesium accumulates"],
    typicalForm: "glycinate for tolerability, oxide for laxative effect.",
  },
  {
    key: "melatonin",
    label: "melatonin",
    latin: "supplement",
    tradition: "western herbal",
    constituents: ["melatonin"],
    territoryKeys: ["pineal", "hypothalamus", "retina"],
    uses: ["circadian phase shifting", "jet lag"],
    mechanism: "signals biological night to the suprachiasmatic nucleus; timing matters far more than dose.",
    evidence: "clinical-trials",
    evidenceNote: "strong evidence as a phase shifter, weak evidence as a sedative.",
    interactsWith: ["warfarin", "sertraline"],
    contraindications: ["driving after dosing", "pregnancy"],
    typicalForm: "low dose several hours before target sleep time.",
  },
  {
    key: "omega3-supp",
    label: "omega-3 (epa/dha)",
    latin: "supplement",
    tradition: "western herbal",
    constituents: ["epa", "dha"],
    territoryKeys: ["heart", "cerebral-cortex", "retina", "cartilage"],
    uses: ["triglycerides", "joint comfort"],
    mechanism: "epa and dha shift eicosanoid balance and membrane composition.",
    evidence: "clinical-trials",
    evidenceNote: "clear triglyceride lowering at high dose; cardiovascular outcome data is mixed by formulation.",
    interactsWith: ["warfarin", "apixaban"],
    contraindications: ["surgery within a week at high dose"],
    typicalForm: "epa-dominant formulation with food.",
  },
  {
    key: "probiotic",
    label: "multi-strain probiotic",
    latin: "supplement",
    tradition: "western herbal",
    constituents: ["live bacterial strains"],
    territoryKeys: ["colon", "small-intestine", "lymphatic"],
    uses: ["antibiotic-associated diarrhoea", "gut comfort"],
    mechanism: "transient colonisation competes with pathogens and modulates mucosal immunity.",
    evidence: "mixed",
    evidenceNote: "strain-specific: benefits proven for one strain do not transfer to another.",
    interactsWith: ["amoxicillin", "prednisone"],
    interactionNote: "avoid live cultures during significant immunosuppression.",
    contraindications: ["severe immunosuppression", "central venous line in place"],
    typicalForm: "strain-labelled product, taken away from antibiotic doses.",
  },
  {
    key: "dong-quai",
    label: "dong quai",
    latin: "angelica sinensis",
    tradition: "western herbal",
    constituents: ["ligustilide", "coumarins"],
    territoryKeys: ["liver", "peripheral-arteries"],
    uses: ["menstrual discomfort in traditional use"],
    mechanism: "coumarin derivatives with anticoagulant and photosensitising activity.",
    evidence: "traditional-only",
    evidenceNote: "no reliable controlled evidence; the interaction risk is real regardless.",
    interactsWith: ["warfarin", "apixaban"],
    contraindications: ["anticoagulation", "pregnancy"],
    typicalForm: "decoction in traditional formulas.",
  },

  {
    key: "boswellia",
    label: "boswellia",
    latin: "boswellia serrata",
    tradition: "ayurveda",
    constituents: ["boswellic acids"],
    territoryKeys: ["cartilage", "colon"],
    uses: ["joint discomfort", "inflammatory bowel symptom support"],
    mechanism: "boswellic acids inhibit 5-lipoxygenase, reducing leukotriene-driven inflammation.",
    evidence: "mixed",
    evidenceNote: "several small trials show reduced osteoarthritis pain; extract standardisation varies widely.",
    interactsWith: ["ibuprofen"],
    contraindications: ["pregnancy"],
    typicalForm: "standardised resin extract.",
  },
  {
    key: "triphala",
    label: "triphala",
    latin: "emblica officinalis / terminalia chebula / terminalia bellirica",
    tradition: "ayurveda",
    constituents: ["tannins", "gallic acid", "vitamin c"],
    territoryKeys: ["colon", "stomach"],
    uses: ["digestive regularity"],
    mechanism: "tannin-rich fruit blend with mild laxative and antioxidant activity in the gut.",
    evidence: "traditional-only",
    evidenceNote: "long traditional use; controlled trial base is thin.",
    interactsWith: ["warfarin"],
    contraindications: ["pregnancy", "active diarrhoea"],
    typicalForm: "powder or tablet before bed.",
  },
  {
    key: "guggul",
    label: "guggul",
    latin: "commiphora wightii",
    tradition: "ayurveda",
    constituents: ["guggulsterones"],
    territoryKeys: ["liver", "thyroid"],
    uses: ["lipid support in traditional use"],
    mechanism: "guggulsterones antagonise the farnesoid x receptor, altering hepatic cholesterol handling.",
    evidence: "mixed",
    evidenceNote: "some trials show ldl reduction, others show a paradoxical rise; monitoring matters.",
    interactsWith: ["atorvastatin", "levothyroxine", "warfarin"],
    interactionNote: "can alter absorption of thyroid hormone and statin metabolism.",
    contraindications: ["pregnancy", "oestrogen-sensitive conditions"],
    typicalForm: "standardised gum resin extract.",
  },
  {
    key: "brahmi",
    label: "brahmi (bacopa)",
    latin: "bacopa monnieri",
    tradition: "ayurveda",
    constituents: ["bacosides"],
    territoryKeys: ["hippocampus", "cerebral-cortex"],
    uses: ["memory and attention support"],
    mechanism: "bacosides modulate hippocampal synaptic signalling and reduce oxidative stress in animal models.",
    evidence: "mixed",
    evidenceNote: "modest cognitive improvements over weeks of use in small trials.",
    interactsWith: ["sertraline"],
    contraindications: ["thyroid disease without monitoring"],
    typicalForm: "standardised leaf extract, taken with food.",
  },
  {
    key: "gotu-kola",
    label: "gotu kola",
    latin: "centella asiatica",
    tradition: "ayurveda",
    constituents: ["asiaticoside", "madecassoside"],
    territoryKeys: ["skin", "veins", "deep-veins-leg"],
    uses: ["wound healing", "venous insufficiency"],
    mechanism: "triterpenes stimulate collagen synthesis and support venous wall tone.",
    evidence: "mixed",
    evidenceNote: "reasonable trial support for venous insufficiency symptoms.",
    interactsWith: ["atorvastatin"],
    contraindications: ["liver disease", "pregnancy"],
    typicalForm: "standardised leaf extract or topical preparation.",
  },
  {
    key: "shatavari",
    label: "shatavari",
    latin: "asparagus racemosus",
    tradition: "ayurveda",
    constituents: ["steroidal saponins"],
    territoryKeys: ["hypothalamus", "stomach"],
    uses: ["lactation support and reproductive tonic in traditional use"],
    mechanism: "saponins are proposed to have galactagogue and adaptogenic activity; the mechanism is not well characterised.",
    evidence: "traditional-only",
    evidenceNote: "traditional use is extensive; controlled human trials are sparse.",
    interactsWith: [],
    contraindications: ["oestrogen-sensitive conditions"],
    typicalForm: "root powder or decoction.",
  },
  {
    key: "neem",
    label: "neem",
    latin: "azadirachta indica",
    tradition: "ayurveda",
    constituents: ["nimbin", "azadirachtin"],
    territoryKeys: ["skin", "colon"],
    uses: ["skin conditions in traditional use"],
    mechanism: "limonoids show antimicrobial and anti-inflammatory activity in laboratory studies.",
    evidence: "traditional-only",
    evidenceNote: "mostly topical traditional use; oral use has caused toxicity in children.",
    interactsWith: ["metformin", "insulin"],
    interactionNote: "may lower blood glucose further.",
    contraindications: ["pregnancy", "young children taking oral neem oil"],
    typicalForm: "topical oil; oral use is not well studied for safety.",
  },
  {
    key: "fenugreek",
    label: "fenugreek",
    latin: "trigonella foenum-graecum",
    tradition: "ayurveda",
    constituents: ["4-hydroxyisoleucine", "soluble fibre"],
    territoryKeys: ["pancreas", "small-intestine"],
    uses: ["glucose regulation", "lactation support"],
    mechanism: "soluble fibre slows carbohydrate absorption and 4-hydroxyisoleucine may enhance insulin secretion.",
    evidence: "mixed",
    evidenceNote: "modest glucose-lowering signal in trials; seed odour affects sweat and urine.",
    interactsWith: ["metformin", "insulin", "warfarin"],
    contraindications: ["pregnancy at high dose"],
    typicalForm: "seed powder with meals.",
  },
  {
    key: "amla",
    label: "amla (indian gooseberry)",
    latin: "phyllanthus emblica",
    tradition: "ayurveda",
    constituents: ["vitamin c", "gallotannins"],
    territoryKeys: ["liver", "stomach"],
    uses: ["general tonic in traditional use"],
    mechanism: "high ascorbic acid and tannin content with antioxidant activity in vitro.",
    evidence: "mixed",
    evidenceNote: "small trials suggest lipid and glycaemic benefit; evidence base is limited.",
    interactsWith: ["warfarin"],
    contraindications: [],
    typicalForm: "fresh fruit, juice or powder.",
  },
  {
    key: "manjistha",
    label: "manjistha",
    latin: "rubia cordifolia",
    tradition: "ayurveda",
    constituents: ["anthraquinones"],
    territoryKeys: ["skin", "lymphatic"],
    uses: ["skin clarity in traditional use"],
    mechanism: "anthraquinone pigments are proposed to support lymphatic and skin clearance in traditional theory.",
    evidence: "traditional-only",
    evidenceNote: "essentially no controlled human trial evidence.",
    interactsWith: [],
    contraindications: ["kidney disease", "pregnancy"],
    typicalForm: "root powder or decoction.",
  },
  {
    key: "goji",
    label: "goji berry",
    latin: "lycium barbarum",
    tradition: "traditional chinese",
    constituents: ["zeaxanthin", "polysaccharides"],
    territoryKeys: ["retina", "liver"],
    uses: ["eye health in traditional use"],
    mechanism: "carotenoids concentrate in the macula; polysaccharides show antioxidant activity in vitro.",
    evidence: "mixed",
    evidenceNote: "small trials show increased macular pigment density.",
    interactsWith: ["warfarin"],
    interactionNote: "case reports of raised inr with concurrent warfarin.",
    contraindications: ["allergy to nightshade family fruit"],
    typicalForm: "dried berries or juice.",
  },
  {
    key: "astragalus",
    label: "astragalus",
    latin: "astragalus membranaceus",
    tradition: "traditional chinese",
    constituents: ["astragalosides", "polysaccharides"],
    territoryKeys: ["lymphatic", "upper-airway", "heart"],
    uses: ["immune tonic in traditional use", "fatigue"],
    mechanism: "polysaccharides modulate innate immune cell activity in laboratory studies.",
    evidence: "mixed",
    evidenceNote: "small trials suggest reduced cold frequency; larger confirmatory trials are lacking.",
    interactsWith: ["prednisone"],
    interactionNote: "theoretical opposition to immunosuppressive therapy.",
    contraindications: ["autoimmune disease on immunosuppression"],
    typicalForm: "root decoction or standardised extract.",
  },
  {
    key: "reishi",
    label: "reishi mushroom",
    latin: "ganoderma lucidum",
    tradition: "traditional chinese",
    constituents: ["triterpenoids", "beta-glucans"],
    territoryKeys: ["liver", "lymphatic"],
    uses: ["stress and immune support in traditional use"],
    mechanism: "beta-glucans engage innate immune receptors; triterpenoids show mild anti-inflammatory activity.",
    evidence: "mixed",
    evidenceNote: "modest fatigue benefit in small trials; some liver injury case reports at high dose.",
    interactsWith: ["warfarin", "apixaban"],
    contraindications: ["surgery within two weeks", "existing liver disease"],
    typicalForm: "spore extract or decoction.",
  },
  {
    key: "cordyceps",
    label: "cordyceps",
    latin: "cordyceps sinensis",
    tradition: "traditional chinese",
    constituents: ["cordycepin", "adenosine"],
    territoryKeys: ["muscle", "lung", "kidney"],
    uses: ["exercise tolerance in traditional use"],
    mechanism: "adenosine analogues are proposed to improve cellular energy handling; human mechanism is unconfirmed.",
    evidence: "mixed",
    evidenceNote: "small trials show modest exercise capacity gains; most commercial product is cultivated mycelium, not the wild fungus.",
    interactsWith: ["warfarin", "metformin"],
    contraindications: ["autoimmune disease on immunosuppression"],
    typicalForm: "cultivated mycelium extract.",
  },
  {
    key: "schisandra",
    label: "schisandra",
    latin: "schisandra chinensis",
    tradition: "traditional chinese",
    constituents: ["lignans (schisandrin)"],
    territoryKeys: ["liver", "adrenal"],
    uses: ["liver support and stress tolerance in traditional use"],
    mechanism: "lignans induce hepatic phase ii detoxification enzymes.",
    evidence: "traditional-only",
    evidenceNote: "enzyme induction is well documented in the lab; clinical outcome trials are minimal.",
    interactsWith: ["atorvastatin", "sertraline"],
    interactionNote: "enzyme induction can alter clearance of other medications.",
    contraindications: ["pregnancy"],
    typicalForm: "dried berry decoction or extract.",
  },
  {
    key: "dan-shen",
    label: "dan shen (red sage root)",
    latin: "salvia miltiorrhiza",
    tradition: "traditional chinese",
    constituents: ["tanshinones", "salvianolic acids"],
    territoryKeys: ["coronary", "heart", "peripheral-arteries"],
    uses: ["circulatory support in traditional use"],
    mechanism: "tanshinones show antiplatelet and coronary vasodilatory activity in laboratory studies.",
    evidence: "mixed",
    evidenceNote: "small trials in angina exist but are methodologically weak by modern standards.",
    interactsWith: ["warfarin", "apixaban"],
    interactionNote: "significantly potentiates warfarin — documented bleeding case reports.",
    contraindications: ["anticoagulation", "surgery within two weeks"],
    typicalForm: "root decoction or standardised extract.",
  },
  {
    key: "huang-qi-licorice",
    label: "chinese liquorice (gan cao)",
    latin: "glycyrrhiza uralensis",
    tradition: "traditional chinese",
    constituents: ["glycyrrhizin"],
    territoryKeys: ["stomach", "adrenal", "heart"],
    uses: ["harmonising herb in traditional formulas"],
    mechanism: "glycyrrhizin inhibits 11-beta-hsd2, the same mineralocorticoid mechanism as western liquorice.",
    evidence: "mixed",
    evidenceNote: "same sodium and potassium risk as western liquorice at sustained doses.",
    interactsWith: ["furosemide", "prednisone", "lisinopril"],
    contraindications: ["hypertension", "heart failure", "pregnancy"],
    typicalForm: "component of compound decoctions, rarely taken alone.",
  },
  {
    key: "gynostemma",
    label: "gynostemma (jiaogulan)",
    latin: "gynostemma pentaphyllum",
    tradition: "traditional chinese",
    constituents: ["gypenosides"],
    territoryKeys: ["liver", "coronary"],
    uses: ["metabolic and cardiovascular support in traditional use"],
    mechanism: "gypenosides show ampk activation similar to some metabolic drugs in laboratory models.",
    evidence: "mixed",
    evidenceNote: "small human trials suggest lipid and glucose benefit.",
    interactsWith: ["metformin", "warfarin"],
    contraindications: ["pregnancy"],
    typicalForm: "leaf tea or extract.",
  },
  {
    key: "poria",
    label: "poria (fu ling)",
    latin: "wolfiporia extensa",
    tradition: "traditional chinese",
    constituents: ["triterpenoids", "polysaccharides"],
    territoryKeys: ["kidney", "colon"],
    uses: ["fluid balance in traditional formulas"],
    mechanism: "traditionally used to move fluid; mild diuretic activity shown in animal studies.",
    evidence: "traditional-only",
    evidenceNote: "almost always used within a compound formula rather than alone.",
    interactsWith: ["furosemide"],
    contraindications: [],
    typicalForm: "component of compound decoctions.",
  },
  {
    key: "ho-shou-wu",
    label: "he shou wu (fo-ti)",
    latin: "polygonum multiflorum",
    tradition: "traditional chinese",
    constituents: ["stilbene glycosides", "anthraquinones"],
    territoryKeys: ["liver", "marrow-axial"],
    uses: ["hair and vitality tonic in traditional use"],
    mechanism: "unprocessed root contains anthraquinones associated with idiosyncratic hepatotoxicity.",
    evidence: "traditional-only",
    evidenceNote: "well-documented liver injury case series; processed (zhi) form is considered lower risk but data is limited.",
    interactsWith: ["atorvastatin"],
    contraindications: ["existing liver disease", "unprocessed raw root"],
    typicalForm: "processed (steamed) root only, with liver enzyme monitoring.",
  },
  {
    key: "ephedra-mahuang",
    label: "ma huang (ephedra)",
    latin: "ephedra sinica",
    tradition: "traditional chinese",
    constituents: ["ephedrine", "pseudoephedrine"],
    territoryKeys: ["heart", "upper-airway", "sympathetic-chain"],
    uses: ["historic use for wheeze and congestion"],
    mechanism: "ephedrine is a direct sympathomimetic raising heart rate and blood pressure.",
    evidence: "clinical-trials",
    evidenceNote: "effective as a stimulant and decongestant; banned in many weight-loss products after cardiac deaths.",
    interactsWith: ["metoprolol", "lisinopril", "sertraline"],
    interactionNote: "can precipitate hypertensive crisis and arrhythmia, especially with stimulants or maois.",
    contraindications: ["heart disease", "hypertension", "pregnancy", "any stimulant use"],
    typicalForm: "restricted; a clinician should be involved before any use.",
  },
  {
    key: "black-seed",
    label: "black seed (nigella)",
    latin: "nigella sativa",
    tradition: "unani",
    constituents: ["thymoquinone"],
    territoryKeys: ["liver", "pancreas", "upper-airway"],
    uses: ["metabolic and respiratory support in traditional use"],
    mechanism: "thymoquinone shows anti-inflammatory and mild insulin-sensitising activity in trials.",
    evidence: "mixed",
    evidenceNote: "small trials show glucose and lipid improvement with oil or seed powder.",
    interactsWith: ["metformin", "insulin", "warfarin"],
    contraindications: ["pregnancy", "surgery within two weeks"],
    typicalForm: "seed oil or powder.",
  },
  {
    key: "unani-senna",
    label: "senna",
    latin: "senna alexandrina",
    tradition: "unani",
    constituents: ["sennosides"],
    territoryKeys: ["colon"],
    uses: ["short-term constipation relief"],
    mechanism: "sennosides are converted by colonic bacteria into compounds that stimulate colonic motility.",
    evidence: "clinical-trials",
    evidenceNote: "effective short-term; chronic use is associated with dependence-like colonic changes.",
    interactsWith: ["furosemide", "warfarin"],
    interactionNote: "potassium loss from overuse potentiates diuretic effects.",
    contraindications: ["inflammatory bowel disease", "long-term daily use", "pregnancy"],
    typicalForm: "standardised tablet at night for short courses only.",
  },
  {
    key: "unani-myrrh",
    label: "myrrh",
    latin: "commiphora myrrha",
    tradition: "unani",
    constituents: ["sesquiterpenes"],
    territoryKeys: ["stomach", "skin"],
    uses: ["oral and topical antiseptic in traditional use"],
    mechanism: "resin sesquiterpenes show antimicrobial activity in vitro.",
    evidence: "traditional-only",
    evidenceNote: "mostly topical or oral rinse traditional use; systemic ingestion evidence is thin.",
    interactsWith: ["warfarin", "metformin", "insulin"],
    contraindications: ["pregnancy"],
    typicalForm: "tincture, diluted for topical or oral rinse use.",
  },
  {
    key: "unani-fennel",
    label: "fennel",
    latin: "foeniculum vulgare",
    tradition: "unani",
    constituents: ["anethole"],
    territoryKeys: ["stomach", "small-intestine"],
    uses: ["digestive comfort", "bloating"],
    mechanism: "anethole relaxes intestinal smooth muscle, reducing gas-related discomfort.",
    evidence: "mixed",
    evidenceNote: "reasonable evidence for infant colic and adult bloating in small trials.",
    interactsWith: [],
    contraindications: ["oestrogen-sensitive conditions at high dose", "pregnancy at high dose"],
    typicalForm: "seed infusion after meals.",
  },
  {
    key: "unani-saffron",
    label: "saffron",
    latin: "crocus sativus",
    tradition: "unani",
    constituents: ["crocin", "safranal"],
    territoryKeys: ["hippocampus", "retina"],
    uses: ["mood support", "eye health in traditional use"],
    mechanism: "crocin and safranal show serotonergic and antioxidant activity in trials.",
    evidence: "clinical-trials",
    evidenceNote: "several trials show a mood benefit comparable to low-dose ssris; more replication is needed.",
    interactsWith: ["sertraline"],
    interactionNote: "serotonergic load stacks with ssris.",
    contraindications: ["pregnancy at high dose", "bipolar disorder"],
    typicalForm: "standardised stigma extract.",
  },
  {
    key: "black-cohosh",
    label: "black cohosh",
    latin: "actaea racemosa",
    tradition: "indigenous north american",
    constituents: ["triterpene glycosides"],
    territoryKeys: ["hypothalamus", "liver"],
    uses: ["menopausal vasomotor symptoms"],
    mechanism: "proposed serotonergic and mild oestrogen-receptor-independent activity; mechanism is still debated.",
    evidence: "mixed",
    evidenceNote: "trial results are inconsistent; rare hepatotoxicity case reports exist.",
    interactsWith: ["atorvastatin"],
    contraindications: ["existing liver disease", "pregnancy", "oestrogen-sensitive cancer without oncology input"],
    typicalForm: "standardised rhizome extract.",
  },
  {
    key: "echinacea-purpurea-root",
    label: "wild indigo root",
    latin: "baptisia tinctoria",
    tradition: "indigenous north american",
    constituents: ["quinolizidine alkaloids"],
    territoryKeys: ["lymph-nodes", "upper-airway"],
    uses: ["immune support in traditional use"],
    mechanism: "traditional immune-stimulant; modern data is essentially absent.",
    evidence: "traditional-only",
    evidenceNote: "traditional use only; alkaloid content raises a caution rather than a clear risk.",
    interactsWith: ["prednisone"],
    contraindications: ["autoimmune disease on immunosuppression", "pregnancy"],
    typicalForm: "tincture.",
  },
  {
    key: "willow-bark",
    label: "white willow bark",
    latin: "salix alba",
    tradition: "indigenous north american",
    constituents: ["salicin"],
    territoryKeys: ["muscle", "cartilage"],
    uses: ["mild pain relief"],
    mechanism: "salicin is metabolised to salicylic acid, the same active principle behind aspirin, with a slower onset.",
    evidence: "clinical-trials",
    evidenceNote: "modest evidence for low back pain; it carries the same risks as low-dose aspirin.",
    interactsWith: ["warfarin", "apixaban", "ibuprofen"],
    interactionNote: "adds to bleeding risk and gastric irritation from other salicylates or nsaids.",
    contraindications: ["aspirin allergy", "children with viral illness (reye syndrome risk)", "peptic ulcer"],
    typicalForm: "standardised bark extract.",
  },
  {
    key: "black-walnut",
    label: "black walnut hull",
    latin: "juglans nigra",
    tradition: "indigenous north american",
    constituents: ["juglone", "tannins"],
    territoryKeys: ["skin", "colon"],
    uses: ["traditional topical and digestive use"],
    mechanism: "juglone has antimicrobial activity in vitro; systemic human data is minimal.",
    evidence: "traditional-only",
    evidenceNote: "traditional use with little modern trial evidence; can stain skin and cause contact reactions.",
    interactsWith: [],
    contraindications: ["tree nut allergy", "pregnancy"],
    typicalForm: "topical tincture; oral use is poorly studied.",
  },
  {
    key: "cats-claw",
    label: "cat's claw",
    latin: "uncaria tomentosa",
    tradition: "indigenous north american",
    constituents: ["oxindole alkaloids"],
    territoryKeys: ["cartilage", "lymphatic"],
    uses: ["joint discomfort in traditional use"],
    mechanism: "alkaloids show anti-inflammatory and mild immune-modulating activity in laboratory studies.",
    evidence: "mixed",
    evidenceNote: "small trials suggest reduced joint pain; larger trials are lacking.",
    interactsWith: ["warfarin", "prednisone"],
    contraindications: ["autoimmune disease on immunosuppression", "pregnancy"],
    typicalForm: "bark extract.",
  },
  {
    key: "yerba-mansa",
    label: "yerba mansa",
    latin: "anemopsis californica",
    tradition: "indigenous north american",
    constituents: ["essential oils", "tannins"],
    territoryKeys: ["upper-airway", "skin"],
    uses: ["traditional topical and respiratory use"],
    mechanism: "aromatic oils with traditional antimicrobial reputation; modern data is essentially absent.",
    evidence: "traditional-only",
    evidenceNote: "very little modern research exists on this plant.",
    interactsWith: [],
    contraindications: ["pregnancy"],
    typicalForm: "root tea or topical wash.",
  },
  {
    key: "usnea",
    label: "usnea (old man's beard lichen)",
    latin: "usnea barbata",
    tradition: "indigenous north american",
    constituents: ["usnic acid"],
    territoryKeys: ["upper-airway", "liver"],
    uses: ["traditional antimicrobial use"],
    mechanism: "usnic acid has documented antimicrobial activity, and also documented dose-dependent liver toxicity.",
    evidence: "mixed",
    evidenceNote: "the antimicrobial activity is real; usnic acid concentrate has caused acute liver failure in weight-loss products.",
    interactsWith: ["atorvastatin"],
    contraindications: ["existing liver disease", "concentrated usnic acid extracts"],
    typicalForm: "dilute tincture only; avoid concentrated extracts.",
  },
  {
    key: "rooibos",
    label: "rooibos",
    latin: "aspalathus linearis",
    tradition: "african traditional",
    constituents: ["aspalathin", "nothofagin"],
    territoryKeys: ["liver", "peripheral-arteries"],
    uses: ["general wellness tea"],
    mechanism: "aspalathin shows antioxidant and mild glucose-handling activity in laboratory studies.",
    evidence: "traditional-only",
    evidenceNote: "well tolerated; human outcome trials are minimal.",
    interactsWith: [],
    contraindications: [],
    typicalForm: "brewed tea.",
  },
  {
    key: "rooibos-honeybush",
    label: "honeybush",
    latin: "cyclopia intermedia",
    tradition: "african traditional",
    constituents: ["mangiferin", "hesperidin"],
    territoryKeys: ["liver", "hypothalamus"],
    uses: ["menopausal comfort in traditional use"],
    mechanism: "flavonoids with weak phytoestrogenic activity in laboratory models.",
    evidence: "traditional-only",
    evidenceNote: "limited controlled human evidence.",
    interactsWith: [],
    contraindications: ["oestrogen-sensitive conditions"],
    typicalForm: "brewed tea.",
  },
  {
    key: "african-potato",
    label: "african potato",
    latin: "hypoxis hemerocallidea",
    tradition: "african traditional",
    constituents: ["hypoxoside", "sterols"],
    territoryKeys: ["lymphatic", "prostate"],
    uses: ["immune support in traditional use"],
    mechanism: "plant sterols show immune-modulating activity in laboratory studies.",
    evidence: "traditional-only",
    evidenceNote: "case reports of drug interaction with antiretroviral therapy exist.",
    interactsWith: ["warfarin"],
    interactionNote: "documented interference with antiretroviral drug levels in case reports.",
    contraindications: ["hiv on antiretroviral therapy without pharmacist review"],
    typicalForm: "corm extract or decoction.",
  },
  {
    key: "devils-claw",
    label: "devil's claw",
    latin: "harpagophytum procumbens",
    tradition: "african traditional",
    constituents: ["harpagoside"],
    territoryKeys: ["cartilage", "muscle"],
    uses: ["joint and low back discomfort"],
    mechanism: "harpagoside shows anti-inflammatory activity comparable to mild nsaids in some trials.",
    evidence: "clinical-trials",
    evidenceNote: "reasonable trial support for low back and osteoarthritis pain.",
    interactsWith: ["warfarin", "omeprazole"],
    interactionNote: "can increase gastric acid secretion, opposing acid-suppressing medication.",
    contraindications: ["peptic ulcer disease", "gallstones", "pregnancy"],
    typicalForm: "standardised tuber extract.",
  },
  {
    key: "sutherlandia",
    label: "sutherlandia (cancer bush)",
    latin: "lessertia frutescens",
    tradition: "african traditional",
    constituents: ["cycloartane glycosides", "gaba"],
    territoryKeys: ["lymphatic", "adrenal"],
    uses: ["traditional tonic use"],
    mechanism: "proposed adaptogenic and immune-modulating activity; mechanism is not well characterised in humans.",
    evidence: "traditional-only",
    evidenceNote: "very limited controlled human data despite wide traditional use.",
    interactsWith: [],
    contraindications: ["pregnancy", "autoimmune disease on immunosuppression"],
    typicalForm: "leaf tea or capsule.",
  },
  {
    key: "baobab",
    label: "baobab fruit",
    latin: "adansonia digitata",
    tradition: "african traditional",
    constituents: ["vitamin c", "soluble fibre"],
    territoryKeys: ["colon", "liver"],
    uses: ["digestive and nutritional support"],
    mechanism: "high soluble fibre and vitamin c content support gut transit and antioxidant intake.",
    evidence: "traditional-only",
    evidenceNote: "primarily a food; nutritional rather than pharmacological evidence base.",
    interactsWith: [],
    contraindications: [],
    typicalForm: "fruit powder.",
  },
  {
    key: "kampo-shakuyaku",
    label: "peony root (shakuyaku)",
    latin: "paeonia lactiflora",
    tradition: "japanese kampo",
    constituents: ["paeoniflorin"],
    territoryKeys: ["muscle", "peripheral-nerve"],
    uses: ["muscle cramping in traditional kampo formulas"],
    mechanism: "paeoniflorin modulates smooth and skeletal muscle calcium handling in laboratory studies.",
    evidence: "mixed",
    evidenceNote: "the compound kampo formula shakuyaku-kanzo-to has trial support for leg cramps.",
    interactsWith: ["furosemide"],
    contraindications: ["pregnancy at high dose"],
    typicalForm: "usually combined with liquorice root in a compound decoction.",
  },
  {
    key: "kampo-kanzo",
    label: "kanzo (japanese liquorice)",
    latin: "glycyrrhiza uralensis",
    tradition: "japanese kampo",
    constituents: ["glycyrrhizin"],
    territoryKeys: ["stomach", "adrenal", "heart"],
    uses: ["harmonising herb in kampo formulas"],
    mechanism: "glycyrrhizin inhibits 11-beta-hsd2, producing the same mineralocorticoid risk at sustained dose.",
    evidence: "mixed",
    evidenceNote: "combined-formula trial support exists; the sodium and potassium risk is unchanged from other liquorice.",
    interactsWith: ["furosemide", "prednisone", "lisinopril"],
    contraindications: ["hypertension", "heart failure", "low potassium"],
    typicalForm: "component of compound kampo formulas.",
  },
  {
    key: "kampo-shoga",
    label: "shokyo (dried ginger)",
    latin: "zingiber officinale (processed)",
    tradition: "japanese kampo",
    constituents: ["shogaols", "gingerols"],
    territoryKeys: ["stomach", "peripheral-arteries"],
    uses: ["warming digestive support in kampo formulas"],
    mechanism: "drying converts gingerols to shogaols, which are more warming and circulatory in traditional theory.",
    evidence: "mixed",
    evidenceNote: "shares the underlying evidence base with fresh ginger for nausea.",
    interactsWith: ["warfarin"],
    contraindications: ["active peptic ulcer"],
    typicalForm: "dried rhizome, usually within a compound formula.",
  },
  {
    key: "kampo-saiko",
    label: "bupleurum (saiko)",
    latin: "bupleurum falcatum",
    tradition: "japanese kampo",
    constituents: ["saikosaponins"],
    territoryKeys: ["liver", "lymphatic"],
    uses: ["liver and stress support in kampo formulas"],
    mechanism: "saikosaponins modulate hepatic and adrenal signalling in laboratory studies.",
    evidence: "mixed",
    evidenceNote: "used almost exclusively in compound formulas; a rare interstitial pneumonitis has been reported with one such formula.",
    interactsWith: ["prednisone", "sertraline"],
    contraindications: ["interstitial lung disease", "pregnancy"],
    typicalForm: "component of compound kampo formulas only.",
  },
  {
    key: "kampo-keihi",
    label: "cinnamon twig (keihi)",
    latin: "cinnamomum cassia (twig)",
    tradition: "japanese kampo",
    constituents: ["cinnamaldehyde"],
    territoryKeys: ["peripheral-arteries", "stomach"],
    uses: ["circulatory warming in kampo formulas"],
    mechanism: "cinnamaldehyde has mild vasodilatory activity in laboratory studies.",
    evidence: "traditional-only",
    evidenceNote: "used almost exclusively within compound kampo formulas.",
    interactsWith: ["warfarin", "metformin"],
    contraindications: ["liver disease with sustained cassia intake"],
    typicalForm: "component of compound kampo formulas.",
  },
  {
    key: "spirulina",
    label: "spirulina",
    latin: "arthrospira platensis",
    tradition: "western herbal",
    constituents: ["phycocyanin", "beta-carotene"],
    territoryKeys: ["liver", "lymphatic"],
    uses: ["nutritional supplementation"],
    mechanism: "phycocyanin shows antioxidant activity in laboratory studies; the main value is nutritional density.",
    evidence: "mixed",
    evidenceNote: "modest lipid and blood pressure effects in small trials; contamination with heavy metals or microcystins is a real quality risk.",
    interactsWith: ["warfarin", "prednisone"],
    contraindications: ["autoimmune disease on immunosuppression", "phenylketonuria"],
    typicalForm: "powder or tablet from a tested source.",
  },
  {
    key: "chlorella",
    label: "chlorella",
    latin: "chlorella vulgaris",
    tradition: "western herbal",
    constituents: ["chlorophyll", "carotenoids"],
    territoryKeys: ["liver", "colon"],
    uses: ["nutritional supplementation"],
    mechanism: "high chlorophyll and micronutrient density; binding claims for heavy metals are not well substantiated in humans.",
    evidence: "traditional-only",
    evidenceNote: "small trials on lipids and blood pressure exist but are weak.",
    interactsWith: ["warfarin"],
    interactionNote: "vitamin k content can lower inr in people on warfarin.",
    contraindications: ["iodine sensitivity", "autoimmune thyroid disease"],
    typicalForm: "powder or tablet.",
  },
  {
    key: "curcumin-piperine",
    label: "curcumin with piperine",
    latin: "curcuma longa + piper nigrum",
    tradition: "ayurveda",
    constituents: ["curcumin", "piperine"],
    territoryKeys: ["liver", "cartilage"],
    uses: ["joint discomfort with improved absorption"],
    mechanism: "piperine inhibits hepatic and intestinal glucuronidation, raising curcumin bioavailability markedly.",
    evidence: "mixed",
    evidenceNote: "same evidence base as turmeric, with piperine also increasing the bioavailability — and blood level — of many co-administered drugs.",
    interactsWith: ["warfarin", "atorvastatin", "levothyroxine"],
    interactionNote: "piperine can raise blood levels of many prescription drugs by inhibiting their clearance.",
    contraindications: ["any prescription medication without pharmacist review", "planned surgery within two weeks"],
    typicalForm: "standardised extract with piperine.",
  },
  {
    key: "kudzu",
    label: "kudzu root",
    latin: "pueraria lobata",
    tradition: "traditional chinese",
    constituents: ["puerarin", "isoflavones"],
    territoryKeys: ["liver", "coronary"],
    uses: ["alcohol craving reduction in traditional use"],
    mechanism: "isoflavones are proposed to reduce alcohol consumption via central mechanisms not fully defined.",
    evidence: "mixed",
    evidenceNote: "small trials suggest reduced drinking episodes; larger confirmatory data is limited.",
    interactsWith: ["warfarin", "metformin"],
    contraindications: ["oestrogen-sensitive conditions", "pregnancy"],
    typicalForm: "root extract.",
  },
  {
    key: "maca",
    label: "maca",
    latin: "lepidium meyenii",
    tradition: "indigenous north american",
    constituents: ["macamides", "glucosinolates"],
    territoryKeys: ["hypothalamus", "testis"],
    uses: ["libido and energy support"],
    mechanism: "macamides are proposed to act on hypothalamic signalling; the human mechanism is not well defined.",
    evidence: "mixed",
    evidenceNote: "small trials show modest libido benefit without a clear hormonal mechanism.",
    interactsWith: ["levothyroxine"],
    interactionNote: "glucosinolate content can affect thyroid hormone synthesis at high sustained intake.",
    contraindications: ["thyroid disease without monitoring"],
    typicalForm: "root powder.",
  },
  {
    key: "passionflower",
    label: "passionflower",
    latin: "passiflora incarnata",
    tradition: "western herbal",
    constituents: ["flavonoids (chrysin, vitexin)"],
    territoryKeys: ["brainstem", "hypothalamus"],
    uses: ["anxiety and sleep onset"],
    mechanism: "flavonoids modulate gaba-a receptor signalling similarly to mild benzodiazepine-site activity.",
    evidence: "mixed",
    evidenceNote: "small trials show benefit for preoperative anxiety and mild generalised anxiety.",
    interactsWith: ["sertraline", "gabapentin"],
    contraindications: ["driving after dosing", "pregnancy"],
    typicalForm: "dried aerial parts as tea or extract.",
  },
  {
    key: "lemon-balm",
    label: "lemon balm",
    latin: "melissa officinalis",
    tradition: "western herbal",
    constituents: ["rosmarinic acid", "citral"],
    territoryKeys: ["stomach", "hypothalamus"],
    uses: ["mild anxiety", "digestive comfort"],
    mechanism: "rosmarinic acid modulates gaba transaminase activity, mildly raising gaba availability.",
    evidence: "mixed",
    evidenceNote: "small trials show calming effect and reduced bloating.",
    interactsWith: ["levothyroxine", "sertraline"],
    interactionNote: "theoretical anti-thyroid activity at high sustained dose.",
    contraindications: ["untreated hypothyroidism"],
    typicalForm: "leaf tea or standardised extract.",
  },
  {
    key: "california-poppy",
    label: "california poppy",
    latin: "eschscholzia californica",
    tradition: "indigenous north american",
    constituents: ["isoquinoline alkaloids"],
    territoryKeys: ["brainstem"],
    uses: ["sleep onset", "mild pain"],
    mechanism: "alkaloids interact mildly with opioid and gaba systems, distinct from and much weaker than the related opium poppy.",
    evidence: "traditional-only",
    evidenceNote: "traditional use with limited modern controlled trials.",
    interactsWith: ["gabapentin", "sertraline"],
    contraindications: ["driving after dosing", "pregnancy"],
    typicalForm: "tincture or tea before bed.",
  },
  {
    key: "skullcap",
    label: "skullcap",
    latin: "scutellaria lateriflora",
    tradition: "indigenous north american",
    constituents: ["baicalin", "scutellarin"],
    territoryKeys: ["brainstem"],
    uses: ["mild anxiety in traditional use"],
    mechanism: "flavonoids show mild gabaergic activity in laboratory studies.",
    evidence: "traditional-only",
    evidenceNote: "adulteration with germander (a hepatotoxin) has historically been a real quality problem.",
    interactsWith: ["sertraline"],
    contraindications: ["existing liver disease", "unverified source material"],
    typicalForm: "standardised extract from a verified source.",
  },
  {
    key: "feverfew",
    label: "feverfew",
    latin: "tanacetum parthenium",
    tradition: "western herbal",
    constituents: ["parthenolide"],
    territoryKeys: ["cerebral-arteries", "brainstem"],
    uses: ["migraine prevention"],
    mechanism: "parthenolide inhibits platelet serotonin release and nf-κb signalling, both implicated in migraine.",
    evidence: "mixed",
    evidenceNote: "several trials show reduced migraine frequency; effect size is modest.",
    interactsWith: ["warfarin", "ibuprofen"],
    contraindications: ["pregnancy", "asteraceae allergy"],
    typicalForm: "standardised leaf extract taken daily for prevention.",
  },
  {
    key: "butterbur",
    label: "butterbur",
    latin: "petasites hybridus",
    tradition: "western herbal",
    constituents: ["petasin", "isopetasin"],
    territoryKeys: ["cerebral-arteries"],
    uses: ["migraine prevention"],
    mechanism: "petasins reduce vascular smooth muscle spasm and leukotriene synthesis.",
    evidence: "clinical-trials",
    evidenceNote: "solid migraine prevention trial data, but only pyrrolizidine-alkaloid-free (PA-free) extract is safe to use.",
    interactsWith: ["atorvastatin"],
    contraindications: ["existing liver disease", "any extract not certified pa-free", "asteraceae allergy"],
    typicalForm: "certified pa-free standardised root extract only.",
  },
  {
    key: "cranberry",
    label: "cranberry",
    latin: "vaccinium macrocarpon",
    tradition: "indigenous north american",
    constituents: ["proanthocyanidins"],
    territoryKeys: ["bladder", "kidney"],
    uses: ["recurrent urinary tract infection prevention"],
    mechanism: "proanthocyanidins reduce bacterial adhesion to the bladder urothelium.",
    evidence: "mixed",
    evidenceNote: "modest preventive effect for recurrent infection in trials; it does not treat an active infection.",
    interactsWith: ["warfarin"],
    contraindications: ["kidney stone history at very high intake"],
    typicalForm: "standardised proanthocyanidin extract or unsweetened juice.",
  },
  {
    key: "uva-ursi",
    label: "uva ursi (bearberry)",
    latin: "arctostaphylos uva-ursi",
    tradition: "indigenous north american",
    constituents: ["arbutin"],
    territoryKeys: ["bladder", "kidney"],
    uses: ["urinary tract discomfort, short-term use"],
    mechanism: "arbutin is converted to hydroquinone in alkaline urine, which has antiseptic activity in the bladder.",
    evidence: "mixed",
    evidenceNote: "short courses only — hydroquinone exposure raises liver and carcinogenicity concerns with sustained use.",
    interactsWith: [],
    contraindications: ["pregnancy", "kidney disease", "use beyond one to two weeks"],
    typicalForm: "leaf extract, short course only.",
  },
  {
    key: "horse-chestnut",
    label: "horse chestnut seed",
    latin: "aesculus hippocastanum",
    tradition: "western herbal",
    constituents: ["aescin"],
    territoryKeys: ["veins", "deep-veins-leg"],
    uses: ["chronic venous insufficiency"],
    mechanism: "aescin reduces capillary permeability and improves venous tone.",
    evidence: "clinical-trials",
    evidenceNote: "solid trial evidence for leg swelling and heaviness in venous insufficiency.",
    interactsWith: ["warfarin", "apixaban"],
    contraindications: ["anticoagulation without review", "existing liver or kidney disease", "raw unprocessed seed is toxic"],
    typicalForm: "standardised seed extract only.",
  },
  {
    key: "bilberry",
    label: "bilberry",
    latin: "vaccinium myrtillus",
    tradition: "western herbal",
    constituents: ["anthocyanosides"],
    territoryKeys: ["retina", "veins"],
    uses: ["night vision and venous support in traditional use"],
    mechanism: "anthocyanosides support retinal microvascular integrity in laboratory studies.",
    evidence: "mixed",
    evidenceNote: "night vision benefit shown in older small trials has not been reliably replicated.",
    interactsWith: ["warfarin", "metformin"],
    contraindications: [],
    typicalForm: "standardised fruit extract.",
  },
  {
    key: "evening-primrose",
    label: "evening primrose oil",
    latin: "oenothera biennis",
    tradition: "western herbal",
    constituents: ["gamma-linolenic acid"],
    territoryKeys: ["skin", "hypothalamus"],
    uses: ["premenstrual and skin symptoms"],
    mechanism: "gamma-linolenic acid shifts prostaglandin balance toward less inflammatory series.",
    evidence: "mixed",
    evidenceNote: "trial evidence for premenstrual symptoms and eczema is inconsistent.",
    interactsWith: ["warfarin"],
    contraindications: ["seizure disorder", "pregnancy without clinical guidance"],
    typicalForm: "standardised seed oil capsule.",
  },
  {
    key: "black-tea-theanine",
    label: "l-theanine (green/black tea)",
    latin: "camellia sinensis (amino acid)",
    tradition: "japanese kampo",
    constituents: ["l-theanine"],
    territoryKeys: ["brainstem", "frontal-lobe"],
    uses: ["calm alertness"],
    mechanism: "l-theanine crosses the blood brain barrier and modulates alpha-wave activity alongside caffeine.",
    evidence: "clinical-trials",
    evidenceNote: "well-supported for reducing the jitteriness of caffeine while preserving alertness.",
    interactsWith: [],
    contraindications: [],
    typicalForm: "standardised capsule, often paired with caffeine.",
  },
  {
    key: "shiitake",
    label: "shiitake mushroom extract",
    latin: "lentinula edodes",
    tradition: "japanese kampo",
    constituents: ["lentinan", "beta-glucans"],
    territoryKeys: ["lymphatic", "liver"],
    uses: ["immune support"],
    mechanism: "lentinan is a beta-glucan that engages innate immune receptors; it is used as an adjunct cancer therapy in some countries by injection, not orally.",
    evidence: "mixed",
    evidenceNote: "the injectable form has trial data in oncology; the oral supplement form has much weaker evidence.",
    interactsWith: ["prednisone", "warfarin"],
    contraindications: ["autoimmune disease on immunosuppression"],
    typicalForm: "dried mushroom or standardised extract.",
  },
  {
    key: "kelp",
    label: "kelp (iodine supplement)",
    latin: "laminaria species",
    tradition: "japanese kampo",
    constituents: ["iodine", "fucoidan"],
    territoryKeys: ["thyroid"],
    uses: ["iodine supplementation"],
    mechanism: "delivers a highly variable, often very large iodine dose that can push the thyroid either way.",
    evidence: "mixed",
    evidenceNote: "iodine content is unpredictable between products, and both deficiency and excess disturb thyroid function.",
    interactsWith: ["levothyroxine"],
    interactionNote: "can precipitate hyper- or hypothyroidism depending on baseline thyroid status.",
    contraindications: ["autoimmune thyroid disease", "existing thyroid nodules"],
    typicalForm: "avoid unless iodine status has actually been measured.",
  },
  {
    key: "sam-e",
    label: "sam-e",
    latin: "s-adenosylmethionine (supplement)",
    tradition: "western herbal",
    constituents: ["s-adenosylmethionine"],
    territoryKeys: ["liver", "hippocampus", "cartilage"],
    uses: ["mood support", "joint discomfort"],
    mechanism: "a universal methyl donor involved in neurotransmitter synthesis and cartilage matrix formation.",
    evidence: "clinical-trials",
    evidenceNote: "reasonable trial support for depression augmentation and osteoarthritis; serotonergic stacking risk is real.",
    interactsWith: ["sertraline"],
    interactionNote: "can precipitate serotonin syndrome when combined with serotonergic antidepressants.",
    contraindications: ["bipolar disorder", "combination with an ssri or maoi without oversight"],
    typicalForm: "enteric-coated tablet on an empty stomach.",
  },
  {
    key: "5-htp",
    label: "5-htp",
    latin: "griffonia simplicifolia (extract)",
    tradition: "african traditional",
    constituents: ["5-hydroxytryptophan"],
    territoryKeys: ["hippocampus", "brainstem"],
    uses: ["mood and sleep support"],
    mechanism: "a direct serotonin precursor that crosses the blood brain barrier and raises central serotonin synthesis.",
    evidence: "mixed",
    evidenceNote: "some positive mood trials; the serotonergic stacking risk with prescription antidepressants is significant.",
    interactsWith: ["sertraline"],
    interactionNote: "directly additive serotonergic load — a recognised cause of serotonin syndrome when combined with an ssri.",
    contraindications: ["any serotonergic medication without oversight", "pregnancy"],
    typicalForm: "standardised seed extract, not combined with an ssri.",
  },
  {
    key: "l-arginine",
    label: "l-arginine",
    latin: "amino acid supplement",
    tradition: "western herbal",
    constituents: ["l-arginine"],
    territoryKeys: ["peripheral-arteries", "coronary"],
    uses: ["circulatory support"],
    mechanism: "substrate for nitric oxide synthase, raising vasodilatory nitric oxide production.",
    evidence: "mixed",
    evidenceNote: "some blood pressure benefit in trials; a large post-heart-attack trial showed increased mortality, so caution matters in cardiac disease.",
    interactsWith: ["lisinopril", "amlodipine"],
    interactionNote: "additive blood pressure lowering.",
    contraindications: ["recent heart attack", "low blood pressure"],
    typicalForm: "powder or capsule.",
  },
  {
    key: "coq10",
    label: "coenzyme q10",
    latin: "ubiquinone (supplement)",
    tradition: "western herbal",
    constituents: ["ubiquinone/ubiquinol"],
    territoryKeys: ["heart", "muscle"],
    uses: ["statin-associated muscle symptoms", "cardiac support"],
    mechanism: "a mitochondrial electron carrier that statins deplete as a side effect of blocking the same synthesis pathway as cholesterol.",
    evidence: "mixed",
    evidenceNote: "trial evidence for reducing statin-associated muscle pain is inconsistent but the mechanism is plausible.",
    interactsWith: ["warfarin"],
    interactionNote: "may mildly reduce warfarin effect.",
    contraindications: [],
    typicalForm: "ubiquinol form for better absorption in older adults.",
  },
  {
    key: "n-acetylcysteine",
    label: "n-acetylcysteine",
    latin: "amino acid derivative (supplement)",
    tradition: "western herbal",
    constituents: ["n-acetylcysteine"],
    territoryKeys: ["liver", "lung"],
    uses: ["mucolytic and antioxidant support"],
    mechanism: "replenishes intracellular glutathione and thins mucus by breaking disulfide bonds.",
    evidence: "clinical-trials",
    evidenceNote: "solid evidence as the antidote for paracetamol overdose and as a mucolytic; supplement-dose evidence for other uses is weaker.",
    interactsWith: ["prednisone"],
    contraindications: ["active peptic ulcer at high dose"],
    typicalForm: "oral capsule or effervescent tablet.",
  },
];

export function herbInteractionsFor(herbKeys: string[], drugKeys: string[]) {
  const out: { herb: HerbDef; drugKey: string }[] = [];
  for (const key of herbKeys) {
    const herb = HERBS.find((h) => h.key === key);
    if (!herb) continue;
    for (const drug of drugKeys) {
      if (herb.interactsWith.includes(drug)) out.push({ herb, drugKey: drug });
    }
  }
  return out;
}

export function herbFindings(herbKeys: string[]): Finding[] {
  const out: Finding[] = [];
  for (const key of herbKeys) {
    const herb = HERBS.find((h) => h.key === key);
    if (!herb) continue;
    out.push({
      id: `herb:${herb.key}`,
      layer: "herb",
      label: `${herb.label} · ${herb.evidence.replace("-", " ")}`,
      detail: herb.evidenceNote,
      mechanism: herb.mechanism,
      nextStep: herb.contraindications.length ? `avoid if: ${herb.contraindications.join("; ")}.` : "review with a pharmacist alongside your medication list.",
      territoryKeys: herb.territoryKeys,
      direction: "active",
      weight: 0.4,
      source: `herbal reference · ${herb.latin}`,
    });
  }
  return out;
}

export function herbsForTerritory(key: string): HerbDef[] {
  return HERBS.filter((h) => h.territoryKeys.includes(key));
}

export function herbsForTradition(t: Tradition): HerbDef[] {
  return HERBS.filter((h) => h.tradition === t);
}

export interface SafetyWarning {
  herb: string;
  severity: "blocking" | "caution";
  detail: string;
}

export interface SafetyReviewRecord {
  medications: { name: string; drugKey?: string }[];
  pregnant?: boolean;
  conditions?: string[];
}

/** cross-checks proposed herbs against medications, pregnancy and named conditions. never diagnostic. */
export function safetyReview(herbKeys: string[], record: SafetyReviewRecord): { blocking: SafetyWarning[]; cautions: SafetyWarning[] } {
  const blocking: SafetyWarning[] = [];
  const cautions: SafetyWarning[] = [];
  const conditions = (record.conditions ?? []).map((c) => c.toLowerCase());
  for (const key of herbKeys) {
    const herb = HERBS.find((h) => h.key === key);
    if (!herb) continue;
    for (const med of record.medications) {
      const drugKey = med.drugKey ?? findDrug(med.name)?.key;
      if (drugKey && herb.interactsWith.includes(drugKey)) {
        cautions.push({
          herb: herb.label,
          severity: "caution",
          detail: herb.interactionNote
            ? `with ${med.name}: ${herb.interactionNote}`
            : `${herb.label} is listed as interacting with ${med.name}; review with a pharmacist before combining.`,
        });
      }
    }
    if (record.pregnant && herb.contraindications.some((c) => c.toLowerCase().includes("pregnan"))) {
      blocking.push({ herb: herb.label, severity: "blocking", detail: `${herb.label} is contraindicated in pregnancy.` });
    }
    for (const cond of conditions) {
      const hit = herb.contraindications.find((c) => c.toLowerCase().includes(cond));
      if (hit) blocking.push({ herb: herb.label, severity: "blocking", detail: `${herb.label} is contraindicated with ${hit}.` });
    }
  }
  return { blocking, cautions };
}
