// spatially anchored pain interview. the person points at the body, the engine asks the
// questions a clinician would ask about that region, and reasons about which tissue class
// produces that pattern. it never names a disease and it always screens for red flags.
import type { Finding } from "./model";

export type PainQuality =
  | "burning"
  | "electric"
  | "deep-ache"
  | "sharp-movement"
  | "cramping"
  | "pressure"
  | "throbbing"
  | "stabbing"
  | "tight-band";

export type TissueClass = "nerve" | "muscle" | "joint" | "bone" | "viscera" | "vascular" | "referred" | "unclear";

export interface QualityRule {
  quality: PainQuality;
  label: string;
  tissue: TissueClass;
  reasoning: string;
}

export const QUALITY_RULES: QualityRule[] = [
  { quality: "burning", label: "burning", tissue: "nerve", reasoning: "burning that follows a strip or glove distribution is generated by the nerve itself rather than the tissue it supplies." },
  { quality: "electric", label: "electric or shooting", tissue: "nerve", reasoning: "shooting pain travelling along a line is a nerve root or trunk firing, not local tissue damage." },
  { quality: "deep-ache", label: "deep ache", tissue: "bone", reasoning: "a deep ache that is worse at night and unrelated to position points at bone or marrow rather than muscle." },
  { quality: "sharp-movement", label: "sharp on movement", tissue: "joint", reasoning: "pain that appears only through a specific arc is mechanical: joint surface, meniscus, tendon or capsule." },
  { quality: "cramping", label: "cramping or colicky", tissue: "viscera", reasoning: "waves of cramp are smooth muscle contracting against resistance — gut, ureter or biliary tree." },
  { quality: "pressure", label: "pressure or heaviness", tissue: "vascular", reasoning: "pressure and heaviness are how visceral and vascular structures report themselves; they are poorly localised by design." },
  { quality: "throbbing", label: "throbbing", tissue: "vascular", reasoning: "pulse-synchronous pain follows arterial pulsation or raised local pressure." },
  { quality: "stabbing", label: "stabbing", tissue: "muscle", reasoning: "brief stabs reproduced by palpation usually come from muscle, fascia or costal structures." },
  { quality: "tight-band", label: "tight band", tissue: "muscle", reasoning: "band-like tightness is sustained muscle tone, often postural or protective." },
];

export interface RedFlagRule {
  key: string;
  label: string;
  /** free-text answers or flags that trigger it. */
  triggers: string[];
  urgency: "urgent" | "same-day" | "prompt";
  action: string;
}

export const RED_FLAGS: RedFlagRule[] = [
  { key: "chest-radiating", label: "chest pain radiating to jaw or arm with sweating or breathlessness", triggers: ["chest-radiating"], urgency: "urgent", action: "call emergency services now. do not drive yourself." },
  { key: "thunderclap", label: "sudden worst-ever headache reaching peak within a minute", triggers: ["thunderclap"], urgency: "urgent", action: "emergency assessment now — this pattern needs imaging today." },
  { key: "cauda-equina", label: "back pain with numbness between the legs, or bladder or bowel loss", triggers: ["saddle-numbness", "bladder-loss"], urgency: "urgent", action: "emergency department now. this is a time-critical spinal presentation." },
  { key: "calf-swelling", label: "one-sided calf swelling with pain and warmth", triggers: ["calf-unilateral"], urgency: "same-day", action: "same-day assessment — a leg clot needs excluding before travel or massage." },
  { key: "sudden-vision", label: "sudden vision loss or a new curtain across vision", triggers: ["vision-loss"], urgency: "urgent", action: "emergency eye assessment now." },
  { key: "abdo-rigid", label: "severe abdominal pain with a rigid abdomen", triggers: ["abdo-rigid"], urgency: "urgent", action: "emergency assessment now; do not eat or drink until seen." },
  { key: "night-bone-pain", label: "unremitting bone pain at night with weight loss", triggers: ["night-pain", "weight-loss"], urgency: "prompt", action: "book a clinical review this week and mention both features together." },
  { key: "fever-focal", label: "focal pain with fever and feeling systemically unwell", triggers: ["fever"], urgency: "same-day", action: "same-day clinical review — infection needs locating." },
  { key: "new-neuro-deficit", label: "new weakness, facial droop or speech difficulty", triggers: ["neuro-deficit"], urgency: "urgent", action: "call emergency services now — treat as stroke until proven otherwise." },
];

export interface InterviewQuestion {
  id: string;
  prompt: string;
  type: "single" | "multi" | "scale" | "text";
  options?: { value: string; label: string; flag?: string }[];
}

export const CORE_QUESTIONS: InterviewQuestion[] = [
  {
    id: "quality",
    prompt: "what does it feel like?",
    type: "multi",
    options: QUALITY_RULES.map((q) => ({ value: q.quality, label: q.label })),
  },
  { id: "severity", prompt: "at its worst, how strong is it?", type: "scale" },
  {
    id: "onset",
    prompt: "how did it start?",
    type: "single",
    options: [
      { value: "sudden", label: "suddenly, within seconds", flag: "thunderclap" },
      { value: "hours", label: "over hours" },
      { value: "days", label: "over days or weeks" },
      { value: "months", label: "months or longer" },
    ],
  },
  {
    id: "pattern",
    prompt: "when is it worst?",
    type: "single",
    options: [
      { value: "movement", label: "on movement or load" },
      { value: "rest", label: "at rest" },
      { value: "night", label: "at night, waking me", flag: "night-pain" },
      { value: "morning", label: "first thing, easing with movement" },
      { value: "constant", label: "constant, no pattern" },
    ],
  },
  {
    id: "radiation",
    prompt: "does it travel anywhere?",
    type: "single",
    options: [
      { value: "no", label: "no, it stays put" },
      { value: "line", label: "along a line down a limb" },
      { value: "band", label: "around like a band" },
      { value: "jaw-arm", label: "to jaw, neck or arm", flag: "chest-radiating" },
    ],
  },
  {
    id: "systemic",
    prompt: "anything else alongside it?",
    type: "multi",
    options: [
      { value: "none", label: "nothing else" },
      { value: "fever", label: "fever or chills", flag: "fever" },
      { value: "weight-loss", label: "unintended weight loss", flag: "weight-loss" },
      { value: "numbness", label: "numbness or pins and needles" },
      { value: "weakness", label: "new weakness", flag: "neuro-deficit" },
      { value: "saddle-numbness", label: "numbness between the legs", flag: "saddle-numbness" },
      { value: "bladder-loss", label: "loss of bladder or bowel control", flag: "bladder-loss" },
      { value: "breathless", label: "breathlessness or sweating", flag: "chest-radiating" },
      { value: "vision-loss", label: "vision change", flag: "vision-loss" },
      { value: "calf-unilateral", label: "one calf swollen and warm", flag: "calf-unilateral" },
      { value: "abdo-rigid", label: "abdomen hard to touch", flag: "abdo-rigid" },
    ],
  },
  { id: "relief", prompt: "what makes it better?", type: "text" },
  { id: "duration", prompt: "how long has it been going on?", type: "text" },
];

export interface PainReport {
  id: string;
  /** the part clicked on the atlas, if any. */
  partId?: string;
  partName?: string;
  territoryKeys: string[];
  answers: Record<string, string | string[] | number>;
  createdAt: string;
  // additive spatial + adaptive-interview fields — all optional so every existing
  // caller and stored report keeps working untouched.
  points?: PainPoint[];
  radiation?: Radiation[];
  character?: PainQuality[];
  onset?: string;
  timePattern?: string;
  modifiers?: PainModifiers;
  intensityNow?: number;
  intensityWorst?: number;
  intensityLeast?: number;
  duration?: string;
  priorEpisodes?: string;
  functionLost?: string[];
}

function answerList(report: PainReport, id: string): string[] {
  const v = report.answers[id];
  if (Array.isArray(v)) return v as string[];
  if (typeof v === "string") return [v];
  return [];
}

export function triggeredFlags(report: PainReport): RedFlagRule[] {
  const flags = new Set<string>();
  for (const q of CORE_QUESTIONS) {
    const chosen = answerList(report, q.id);
    for (const opt of q.options ?? []) {
      if (opt.flag && chosen.includes(opt.value)) flags.add(opt.flag);
    }
  }
  const severity = Number(report.answers.severity ?? 0);
  if (severity >= 9 && answerList(report, "onset").includes("sudden")) flags.add("thunderclap");
  return RED_FLAGS.filter((r) => r.triggers.some((t) => flags.has(t)));
}

export interface PainReasoning {
  tissue: TissueClass;
  confidence: number;
  reasoning: string[];
}

export function reasonAboutPain(report: PainReport): PainReasoning {
  const qualities = answerList(report, "quality");
  const reasoning: string[] = [];
  const score = new Map<TissueClass, number>();
  for (const q of qualities) {
    const rule = QUALITY_RULES.find((r) => r.quality === q);
    if (!rule) continue;
    score.set(rule.tissue, (score.get(rule.tissue) ?? 0) + 1);
    reasoning.push(rule.reasoning);
  }
  const radiation = answerList(report, "radiation")[0];
  if (radiation === "line") {
    score.set("nerve", (score.get("nerve") ?? 0) + 1.5);
    reasoning.push("pain travelling in a line down a limb follows a nerve root distribution rather than a muscle belly.");
  }
  if (radiation === "band") {
    score.set("nerve", (score.get("nerve") ?? 0) + 0.8);
    reasoning.push("a band around the trunk follows a single dermatome, which places the origin at the nerve root.");
  }
  const pattern = answerList(report, "pattern")[0];
  if (pattern === "movement") {
    score.set("joint", (score.get("joint") ?? 0) + 1);
    reasoning.push("load dependence means the structure is mechanical — it hurts when it carries weight.");
  }
  if (pattern === "night") {
    score.set("bone", (score.get("bone") ?? 0) + 1);
    reasoning.push("night pain that is independent of position raises the priority of a bone or inflammatory cause.");
  }
  if (pattern === "morning") {
    score.set("joint", (score.get("joint") ?? 0) + 0.8);
    reasoning.push("morning stiffness easing with movement is an inflammatory rhythm rather than a degenerative one.");
  }
  if (answerList(report, "systemic").includes("numbness")) {
    score.set("nerve", (score.get("nerve") ?? 0) + 1);
    reasoning.push("sensory change alongside the pain confirms the nerve is involved, not just irritated tissue nearby.");
  }
  let best: TissueClass = "unclear";
  let bestScore = 0;
  score.forEach((v, k) => {
    if (v > bestScore) {
      bestScore = v;
      best = k;
    }
  });
  const total = [...score.values()].reduce((a, b) => a + b, 0) || 1;
  if (best === "unclear") reasoning.push("the pattern described does not separate the tissue classes; more detail or an examination is needed.");
  return { tissue: best, confidence: Math.min(0.9, bestScore / total), reasoning };
}

export function painFindings(reports: PainReport[]): Finding[] {
  const out: Finding[] = [];
  for (const report of reports) {
    const flags = triggeredFlags(report);
    const reasoning = reasonAboutPain(report);
    const severity = Number(report.answers.severity ?? 5);
    out.push({
      id: `pain:${report.id}`,
      layer: "pain",
      label: `pain · ${report.partName ?? "unlocated"}`,
      detail: `severity ${severity}/10. the pattern is most consistent with a ${reasoning.tissue === "unclear" ? "pattern that is not yet separable" : `${reasoning.tissue} source`}.`,
      mechanism: reasoning.reasoning.join(" "),
      nextStep: flags.length
        ? flags.map((f) => f.action).join(" ")
        : "track whether it changes with load, time of day and sleep for a week — that pattern is what a clinician will ask for.",
      territoryKeys: report.territoryKeys,
      direction: "elevated",
      weight: Math.max(0.3, Math.min(1, severity / 10)),
      source: "your pain report",
      redFlag: flags.length > 0,
    });
  }
  return out;
}

// ============================================================================
// additive extensions: spatial multi-point capture, radiation, adaptive
// interview questions, expanded red-flag catalogue, ranked pattern reasoning
// and a structured written package. every existing export above is unchanged.
// ============================================================================

export type PainDepth = "surface" | "deep" | "boney" | "visceral";
export type BodySide = "left" | "right" | "midline";

/** one clicked or described location, with how deep it feels. */
export interface PainPoint {
  id: string;
  territoryKey: string;
  territoryLabel?: string;
  side?: BodySide;
  depth: PainDepth;
}

export type RadiationPattern = "dermatomal" | "myotomal" | "vascular" | "referred-visceral" | "non-anatomical";

export interface Radiation {
  id: string;
  fromTerritoryKey: string;
  toTerritoryKey: string;
  pattern: RadiationPattern;
}

export interface PainModifiers {
  worse: string[];
  better: string[];
}

/** extends RedFlagRule with a machine-checkable trigger surface beyond option flags. */
export interface RedFlagKeywordRule {
  key: string;
  /** matched case-insensitively against any free-text field on the report. */
  keywords: string[];
}

// urgency tiers, expanded catalogue. additive to the original nine rules above —
// existing keys and shape are untouched, this only appends further rules.
RED_FLAGS.push(
  {
    key: "chest-exertional",
    label: "chest pain brought on by exertion that radiates and eases with rest",
    triggers: ["exertional-chest"],
    urgency: "urgent",
    action: "stop the activity and seek same-day cardiac assessment; call emergency services if it does not settle within minutes.",
  },
  {
    key: "testicular-torsion",
    label: "sudden severe one-sided testicular pain",
    triggers: ["torsion-pattern"],
    urgency: "urgent",
    action: "emergency assessment now — the window to save the testis is only a few hours.",
  },
  {
    key: "jaw-claudication",
    label: "jaw pain on chewing with scalp tenderness or headache over 50",
    triggers: ["jaw-claudication"],
    urgency: "same-day",
    action: "same-day review — this pattern can precede sudden vision loss if untreated.",
  },
  {
    key: "syncope-with-pain",
    label: "fainting or near-fainting alongside the pain",
    triggers: ["syncope"],
    urgency: "urgent",
    action: "emergency assessment now — loss of consciousness with pain needs a cause found today.",
  },
);

const KEYWORD_FLAG_RULES: RedFlagKeywordRule[] = [
  { key: "chest-exertional", keywords: ["exertion", "climbing stairs", "walking uphill", "on exertion"] },
  { key: "testicular-torsion", keywords: ["testicle", "testis", "scrotum", "scrotal"] },
  { key: "jaw-claudication", keywords: ["jaw", "chewing", "scalp tender"] },
  { key: "syncope-with-pain", keywords: ["fainted", "fainting", "passed out", "blacked out", "syncope"] },
  { key: "cauda-equina", keywords: ["saddle", "numb between my legs", "can't feel to wee", "incontinence"] },
  { key: "calf-swelling", keywords: ["calf swollen", "one leg swollen", "swollen calf"] },
  { key: "thunderclap", keywords: ["worst headache of my life", "thunderclap", "hit by a bat"] },
  { key: "abdo-rigid", keywords: ["board-like", "rigid abdomen", "hard stomach"] },
  { key: "fever-focal", keywords: ["fever", "chills", "shivering"] },
];

function freeTextOf(report: PainReport): string {
  const parts: string[] = [];
  if (report.character) parts.push(...report.character);
  if (report.modifiers) parts.push(...report.modifiers.worse, ...report.modifiers.better);
  if (report.functionLost) parts.push(...report.functionLost);
  if (report.duration) parts.push(report.duration);
  if (report.priorEpisodes) parts.push(report.priorEpisodes);
  if (typeof report.answers.relief === "string") parts.push(report.answers.relief);
  return parts.join(" · ").toLowerCase();
}

/** structured-field version of testicular torsion detection: sudden onset, severe, groin/testis point. */
function structuredTriggerKeys(report: PainReport): Set<string> {
  const keys = new Set<string>();
  const text = freeTextOf(report);
  for (const rule of KEYWORD_FLAG_RULES) {
    if (rule.keywords.some((k) => text.includes(k))) keys.add(rule.key);
  }
  const worst = report.intensityWorst ?? Number(report.answers.severity ?? 0);
  const suddenOnset = report.onset === "sudden" || answerList(report, "onset").includes("sudden");
  if (suddenOnset && worst >= 8 && (report.points ?? []).some((p) => p.territoryKey === "testis")) {
    keys.add("torsion-pattern");
  }
  if (report.radiation?.some((r) => r.pattern === "referred-visceral" && r.toTerritoryKey === "coronary")) {
    keys.add("exertional-chest");
  }
  return keys;
}

/** the full red-flag sweep: option-based triggers (original) plus structured/free-text triggers (additive). */
export function triggeredFlagsExtended(report: PainReport): RedFlagRule[] {
  const base = triggeredFlags(report);
  const extraKeys = structuredTriggerKeys(report);
  // keyword rules name the flag key directly; structured rules name a trigger token.
  // both have to resolve, or free-text warnings silently never fire.
  const extra = RED_FLAGS.filter((r) => extraKeys.has(r.key) || r.triggers.some((t) => extraKeys.has(t)));
  const seen = new Set(base.map((f) => f.key));
  const merged = [...base];
  for (const f of extra) if (!seen.has(f.key)) { merged.push(f); seen.add(f.key); }
  return merged;
}

/** rank red flags by urgency for display order. */
export function rankFlags(flags: RedFlagRule[]): RedFlagRule[] {
  const rank: Record<RedFlagRule["urgency"], number> = { urgent: 0, "same-day": 1, prompt: 2 };
  return [...flags].sort((a, b) => rank[a.urgency] - rank[b.urgency]);
}

export interface PainPatternCandidate {
  tissue: TissueClass;
  label: string;
  confidence: number;
  reasoning: string[];
  /** what additional detail would sharpen or overturn this read. */
  wouldChangeWith: string;
}

const WOULD_CHANGE: Record<TissueClass, string> = {
  nerve: "a dermatomal map or a positive straight-leg-raise / nerve stretch test would confirm root involvement.",
  muscle: "reproducing it exactly with palpation of one muscle belly would confirm a myofascial source.",
  joint: "pain confined to one movement arc, or joint-line tenderness on examination, would confirm a joint source.",
  bone: "night pain unrelated to position plus a point of bony tenderness would raise priority for imaging.",
  viscera: "a relationship to eating, bowel habit or menstrual cycle would confirm a visceral source.",
  vascular: "a pulse deficit, bruit, or pain reproduced by exertion and relieved by rest would confirm a vascular source.",
  referred: "pressing on the area that hurts not reproducing it, while pressing elsewhere does, confirms referral.",
  unclear: "more detail on quality, timing and what reproduces it would separate the tissue classes.",
};

/** ranked list of candidate mechanisms rather than one guess — every read carries what would sharpen it. */
export function painPattern(report: PainReport): PainPatternCandidate[] {
  const primary = reasonAboutPain(report);
  const qualities = answerList(report, "quality");
  const score = new Map<TissueClass, { score: number; reasoning: string[] }>();
  const bump = (t: TissueClass, amount: number, why: string) => {
    const cur = score.get(t) ?? { score: 0, reasoning: [] };
    cur.score += amount;
    cur.reasoning.push(why);
    score.set(t, cur);
  };
  for (const q of qualities) {
    const rule = QUALITY_RULES.find((r) => r.quality === q);
    if (rule) bump(rule.tissue, 1, rule.reasoning);
  }
  for (const c of report.character ?? []) {
    const rule = QUALITY_RULES.find((r) => r.quality === c);
    if (rule) bump(rule.tissue, 0.8, rule.reasoning);
  }
  if (report.radiation?.length) {
    for (const r of report.radiation) {
      if (r.pattern === "dermatomal") bump("nerve", 1.4, "a dermatomal radiation pattern places the origin at a nerve root.");
      if (r.pattern === "myotomal") bump("muscle", 1.1, "pain spreading along a muscle group rather than a nerve line points at a myotomal pattern.");
      if (r.pattern === "vascular") bump("vascular", 1.4, "radiation following a vascular territory suggests arterial or venous origin.");
      if (r.pattern === "referred-visceral") bump("referred", 1.4, "referred visceral patterns travel to a distant surface site sharing embryological origin, not a direct nerve line.");
      if (r.pattern === "non-anatomical") bump("unclear", 0.6, "a spread that does not follow any known nerve, muscle or vascular map is harder to localise anatomically.");
    }
  }
  for (const p of report.points ?? []) {
    if (p.depth === "boney") bump("bone", 1, "a point described as boney in depth is felt over the bone itself rather than the soft tissue above it.");
    if (p.depth === "visceral") bump("viscera", 1, "a point described as deep and visceral in character is felt behind, not on, the body wall.");
    if (p.depth === "surface") bump("referred", 0.3, "a surface-only sensation can still represent a referred pattern reaching the skin.");
  }
  if (primary.tissue !== "unclear") bump(primary.tissue, primary.confidence * 2, primary.reasoning.join(" "));
  const entries = [...score.entries()].sort((a, b) => b[1].score - a[1].score);
  const total = entries.reduce((sum, [, v]) => sum + v.score, 0) || 1;
  const out: PainPatternCandidate[] = entries.slice(0, 3).map(([tissue, v]) => ({
    tissue,
    label: tissue === "unclear" ? "not yet separable" : tissue,
    confidence: Math.round(Math.min(0.92, v.score / total) * 100) / 100,
    reasoning: [...new Set(v.reasoning)],
    wouldChangeWith: WOULD_CHANGE[tissue],
  }));
  if (out.length === 0) {
    out.push({ tissue: "unclear", label: "not yet separable", confidence: 0, reasoning: ["too little detail recorded yet to separate a tissue class."], wouldChangeWith: WOULD_CHANGE.unclear });
  }
  return out;
}

/** 1–3 adaptive next questions, branching on what has already been captured. */
export function nextQuestions(partial: Partial<PainReport>): InterviewQuestion[] {
  const asked = new Set(Object.keys(partial.answers ?? {}));
  const out: InterviewQuestion[] = [];
  const points = partial.points ?? [];
  const regions = new Set(points.map((p) => p.territoryKey));
  const hasChestPoint = regions.has("heart") || regions.has("coronary") || regions.has("aorta");
  const hasSpinePoint = regions.has("vertebra") || regions.has("sacroiliac");
  const hasHeadPoint = regions.has("brain") || regions.has("cerebral-cortex") || regions.has("frontal-lobe");
  const hasTestisPoint = regions.has("testis");

  if (points.length === 0) {
    return [{ id: "quality", prompt: "what does it feel like?", type: "multi", options: QUALITY_RULES.map((q) => ({ value: q.quality, label: q.label })) }];
  }
  if (hasChestPoint && !asked.has("radiation")) {
    out.push(CORE_QUESTIONS.find((q) => q.id === "radiation")!);
    out.push({
      id: "exertion",
      prompt: "does exertion bring it on, and does rest settle it?",
      type: "single",
      options: [
        { value: "yes", label: "yes — exertion brings it on", flag: "exertional-chest" },
        { value: "no", label: "no relationship to exertion" },
      ],
    });
  }
  if (hasSpinePoint && !asked.has("systemic")) {
    out.push(CORE_QUESTIONS.find((q) => q.id === "systemic")!);
  }
  if (hasHeadPoint && !asked.has("onset")) {
    out.push(CORE_QUESTIONS.find((q) => q.id === "onset")!);
  }
  if (hasTestisPoint) {
    out.push({
      id: "torsion-check",
      prompt: "did it come on suddenly and severely, on one side?",
      type: "single",
      options: [
        { value: "yes", label: "yes, suddenly and severely", flag: "torsion-pattern" },
        { value: "no", label: "no, it built up gradually" },
      ],
    });
  }
  if (!asked.has("quality") && out.length < 3) out.push(CORE_QUESTIONS.find((q) => q.id === "quality")!);
  if (!asked.has("pattern") && out.length < 3) out.push(CORE_QUESTIONS.find((q) => q.id === "pattern")!);
  if (!asked.has("radiation") && out.length < 3 && !hasChestPoint) out.push(CORE_QUESTIONS.find((q) => q.id === "radiation")!);
  if (!asked.has("relief") && out.length < 3) out.push(CORE_QUESTIONS.find((q) => q.id === "relief")!);
  if (!asked.has("duration") && out.length < 3) out.push(CORE_QUESTIONS.find((q) => q.id === "duration")!);
  // de-dupe by id, cap at three.
  const dedup: InterviewQuestion[] = [];
  const seenIds = new Set<string>();
  for (const q of out) {
    if (seenIds.has(q.id)) continue;
    seenIds.add(q.id);
    dedup.push(q);
    if (dedup.length === 3) break;
  }
  return dedup;
}

export interface PainOutputPackage {
  headline: string;
  flags: RedFlagRule[];
  pattern: PainPatternCandidate[];
  narrative: string;
  markdown: string;
}

/** the structured written package for one report: what was recorded, ranked reads, and next steps. */
export function painOutput(report: PainReport): PainOutputPackage {
  const flags = rankFlags(triggeredFlagsExtended(report));
  const pattern = painPattern(report);
  const worst = report.intensityWorst ?? Number(report.answers.severity ?? 0);
  const location = report.partName ?? points_label(report);
  const headline = `${location || "unlocated pain"} · worst intensity ${worst || "not recorded"}/10`;
  const narrativeLines: string[] = [];
  narrativeLines.push(`recorded ${report.duration ? `over ${report.duration}` : "with duration not yet recorded"}.`);
  if (report.character?.length) narrativeLines.push(`described as ${report.character.join(", ")}.`);
  if (report.radiation?.length) {
    narrativeLines.push(
      report.radiation.map((r) => `travels from ${r.fromTerritoryKey} to ${r.toTerritoryKey} in a ${r.pattern} pattern`).join("; ") + ".",
    );
  }
  if (report.modifiers?.worse.length) narrativeLines.push(`worse with: ${report.modifiers.worse.join(", ")}.`);
  if (report.modifiers?.better.length) narrativeLines.push(`better with: ${report.modifiers.better.join(", ")}.`);
  narrativeLines.push(
    pattern[0]?.tissue === "unclear"
      ? "the pattern described does not yet separate a tissue class."
      : `most consistent read: ${pattern[0].label} (${Math.round((pattern[0].confidence ?? 0) * 100)}% weight of the evidence gathered) — ${pattern[0].reasoning[0] ?? ""}`,
  );
  const narrative = narrativeLines.join(" ");
  const md: string[] = [];
  md.push(`### pain report — ${location || "unlocated"}`);
  md.push("");
  md.push(`- worst intensity: ${report.intensityWorst ?? "n/a"}/10, now: ${report.intensityNow ?? "n/a"}/10, least: ${report.intensityLeast ?? "n/a"}/10`);
  if (report.duration) md.push(`- duration: ${report.duration}`);
  if (report.character?.length) md.push(`- character: ${report.character.join(", ")}`);
  if (report.onset) md.push(`- onset: ${report.onset}`);
  if (report.timePattern) md.push(`- worst time: ${report.timePattern}`);
  if (report.modifiers?.worse.length) md.push(`- worse with: ${report.modifiers.worse.join(", ")}`);
  if (report.modifiers?.better.length) md.push(`- better with: ${report.modifiers.better.join(", ")}`);
  if (report.priorEpisodes) md.push(`- prior episodes: ${report.priorEpisodes}`);
  if (report.functionLost?.length) md.push(`- function affected: ${report.functionLost.join(", ")}`);
  if (report.radiation?.length) {
    md.push(`- radiation: ${report.radiation.map((r) => `${r.fromTerritoryKey} → ${r.toTerritoryKey} (${r.pattern})`).join("; ")}`);
  }
  md.push("");
  if (flags.length) {
    md.push("**see a clinician — red flags present:**");
    for (const f of flags) md.push(`- [${f.urgency}] ${f.label}: ${f.action}`);
    md.push("");
  }
  md.push("candidate mechanisms (ranked, not a diagnosis):");
  for (const c of pattern) {
    md.push(`- ${c.label} — ${Math.round(c.confidence * 100)}%. ${c.reasoning.join(" ")} what would sharpen this: ${c.wouldChangeWith}`);
  }
  md.push("");
  md.push("this is a self-collected, non-diagnostic summary generated on-device for use in conversation with a clinician.");
  return { headline, flags, pattern, narrative, markdown: md.join("\n") };
}

function points_label(report: PainReport): string {
  const pts = report.points ?? [];
  if (pts.length === 0) return "";
  return pts.map((p) => `${p.territoryLabel ?? p.territoryKey}${p.side ? ` (${p.side})` : ""}`).join(", ");
}
