// symptom layer: a non-pain complaint mapped to the organs that generate that experience.
// each entry states which systems to consider, never a single diagnosis.
import type { Finding } from "./model";

export interface SymptomDef {
  key: string;
  label: string;
  territoryKeys: string[];
  mechanism: string;
  nextStep: string;
  redFlag?: boolean;
}

export const SYMPTOMS: SymptomDef[] = [
  {
    key: "fatigue",
    label: "persistent fatigue",
    territoryKeys: ["thyroid", "marrow-axial", "liver", "adrenal", "brain"],
    mechanism: "energy availability is set by oxygen delivery, thyroid tone, sleep architecture and mood together; the complaint is shared across all four.",
    nextStep: "a basic panel separates most causes: full blood count, ferritin, tsh, glucose and b12.",
  },
  {
    key: "breathless-exertion",
    label: "breathless on exertion",
    territoryKeys: ["lung", "heart", "marrow-axial"],
    mechanism: "the limiting step is either gas exchange, cardiac output or oxygen carriage; the symptom cannot tell you which alone.",
    nextStep: "note the exact distance or stair count that triggers it — that number is what changes management.",
  },
  {
    key: "palpitations",
    label: "palpitations",
    territoryKeys: ["heart", "thyroid", "sympathetic-chain"],
    mechanism: "awareness of the heartbeat rises with rhythm change, thyroid excess or sympathetic drive.",
    nextStep: "capture one episode on a phone ecg or pulse trace if you can — timing and regularity are the useful data.",
  },
  {
    key: "dizziness",
    label: "dizziness",
    territoryKeys: ["vestibular", "cochlea", "brainstem", "heart"],
    mechanism: "spinning points at the vestibular apparatus; lightheadedness on standing points at blood pressure control.",
    nextStep: "distinguish spinning from faintness before anything else — they lead to different investigations.",
  },
  {
    key: "reflux",
    label: "reflux or heartburn",
    territoryKeys: ["oesophagus", "stomach", "diaphragm"],
    mechanism: "the lower oesophageal sphincter and diaphragmatic crus together form the barrier; both loosen with pressure and posture.",
    nextStep: "difficulty swallowing or weight loss alongside reflux changes urgency — mention them explicitly.",
  },
  {
    key: "bloating",
    label: "bloating and irregular bowels",
    territoryKeys: ["colon", "small-intestine", "stomach"],
    mechanism: "gas volume, transit time and visceral sensitivity all contribute; the microbiome shapes all three.",
    nextStep: "a symptom and food diary for two weeks tells you more than any single test.",
  },
  {
    key: "insomnia",
    label: "difficulty sleeping",
    territoryKeys: ["hypothalamus", "pineal", "brainstem", "cerebral-cortex"],
    mechanism: "sleep onset depends on circadian phase and arousal; maintenance depends on breathing, temperature and cortisol timing.",
    nextStep: "fix light timing and wake time first — they move the circadian phase that everything else follows.",
  },
  {
    key: "snoring-apnoea",
    label: "snoring or witnessed pauses in breathing",
    territoryKeys: ["upper-airway", "lung", "heart", "brain"],
    mechanism: "pharyngeal collapse during sleep fragments sleep and drives nocturnal sympathetic surges.",
    nextStep: "witnessed pauses warrant a sleep study — untreated apnoea drives blood pressure and rhythm risk.",
    redFlag: true,
  },
  {
    key: "headache",
    label: "recurrent headache",
    territoryKeys: ["brain", "trigeminal", "sinuses", "masseter", "cerebral-arteries"],
    mechanism: "most recurrent headache is generated by the trigeminovascular system, jaw muscles or cervical structures, not by the brain itself.",
    nextStep: "record frequency, duration and any warning symptoms — the pattern is diagnostic more than the pain is.",
  },
  {
    key: "low-mood",
    label: "low mood or loss of interest",
    territoryKeys: ["hippocampus", "amygdala", "frontal-lobe", "thyroid"],
    mechanism: "mood regulation sits across prefrontal control, limbic reactivity and endocrine tone; sleep and thyroid state modulate all of it.",
    nextStep: "if this has lasted more than two weeks, speak to a clinician; if you have thoughts of harming yourself, seek help today.",
  },
  {
    key: "brain-fog",
    label: "difficulty concentrating",
    territoryKeys: ["frontal-lobe", "hippocampus", "thyroid"],
    mechanism: "attention depends on sleep quality, glucose stability, thyroid tone and mood — it is rarely one thing.",
    nextStep: "sleep, caffeine timing and stimulant load are the fastest things to test.",
  },
  {
    key: "joint-stiffness",
    label: "joint stiffness",
    territoryKeys: ["cartilage", "knee", "hip", "shoulder", "sacroiliac"],
    mechanism: "morning stiffness longer than 30 minutes suggests an inflammatory pattern; brief stiffness after rest suggests a degenerative one.",
    nextStep: "time the stiffness with a clock for a few mornings; the duration is the discriminating detail.",
  },
  {
    key: "numbness",
    label: "numbness or tingling",
    territoryKeys: ["peripheral-nerve", "spinal-cord", "vertebra"],
    mechanism: "distribution decides the level: glove-and-stocking is peripheral, a strip is a nerve root, a level on the trunk is the cord.",
    nextStep: "draw the exact area on the atlas — the shape is the most informative part of this symptom.",
  },
  {
    key: "urinary-frequency",
    label: "urinary frequency or urgency",
    territoryKeys: ["bladder", "prostate", "kidney"],
    mechanism: "bladder capacity, outflow resistance and urine volume each produce frequency by a different route.",
    nextStep: "a three-day frequency-volume chart separates the three.",
  },
  {
    key: "tinnitus",
    label: "tinnitus",
    territoryKeys: ["cochlea", "vestibulocochlear", "cerebral-cortex"],
    mechanism: "the cortex amplifies its own noise when cochlear input drops; that is why tinnitus tracks hearing loss.",
    nextStep: "one-sided or pulsatile tinnitus should be assessed rather than accepted.",
  },
  {
    key: "night-sweats",
    label: "night sweats",
    territoryKeys: ["hypothalamus", "lymph-nodes", "thyroid"],
    mechanism: "thermoregulatory set point shifts with infection, endocrine change and lymphoid activity.",
    nextStep: "drenching sweats with weight loss or lumps should be reviewed promptly.",
    redFlag: true,
  },
  {
    key: "cough-persistent",
    label: "cough lasting more than three weeks",
    territoryKeys: ["lung", "upper-airway", "oesophagus"],
    mechanism: "three sources dominate persistent cough: airway inflammation, postnasal drip and reflux.",
    nextStep: "cough with blood, weight loss or fever needs assessment now rather than later.",
    redFlag: true,
  },
  {
    key: "cold-hands",
    label: "cold or colour-changing hands",
    territoryKeys: ["peripheral-arteries", "sympathetic-chain"],
    mechanism: "digital arteriolar tone is under sympathetic control; exaggerated closure produces the colour sequence.",
    nextStep: "note whether the colour changes are white then blue then red — that triphasic sequence is the useful detail.",
  },
];

export interface SymptomEntry {
  id: string;
  symptomKey: string;
  severity: number;
  since?: string;
  note?: string;
}

export function symptomFindings(entries: SymptomEntry[]): Finding[] {
  const out: Finding[] = [];
  for (const e of entries) {
    const def = SYMPTOMS.find((s) => s.key === e.symptomKey);
    if (!def) continue;
    out.push({
      id: `symptom:${e.id}`,
      layer: "symptom",
      label: def.label,
      detail: `${e.severity}/10${e.since ? ` · since ${e.since}` : ""}${e.note ? ` · ${e.note}` : ""}`,
      mechanism: def.mechanism,
      nextStep: def.nextStep,
      territoryKeys: def.territoryKeys,
      direction: "elevated",
      weight: Math.max(0.25, Math.min(0.95, e.severity / 10)),
      source: "your symptom record",
      redFlag: def.redFlag,
    });
  }
  return out;
}
