/**
 * Writes public/sitemap.xml from the real public route list.
 *
 * Rules:
 *  - one <loc> per path in ROUTE_SEO that is indexable and not excluded.
 *  - <lastmod> comes from the git commit date of the file that renders the
 *    route. When that cannot be resolved, <lastmod> is omitted — an invented
 *    date is worse than none.
 *  - no <changefreq>, no <priority>: Google ignores both, and a hand-painted
 *    priority ladder is theatre.
 *
 * Run: bunx tsx scripts/generate-sitemap.ts
 */

import { execFileSync } from "node:child_process";
import { existsSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { ORIGIN, ROUTE_SEO, sitemapPaths } from "../src/lib/routeSeoData";

/** Best-effort map from a route to the source file that renders it. */
function candidateFiles(path: string): string[] {
  if (path === "/") return ["src/pages/Index.tsx"];
  const seg = path.split("/").filter(Boolean);
  const pascal = (s: string) =>
    s
      .split("-")
      .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
      .join("");
  const last = pascal(seg[seg.length - 1]);
  const dir = seg.length > 1 ? seg[0] : "";
  return [dir ? `src/pages/${dir}/${last}.tsx` : `src/pages/${last}.tsx`, `src/pages/${last}.tsx`];
}

function gitDate(file: string): string | undefined {
  try {
    const out = execFileSync("git", ["log", "-1", "--format=%cs", "--", file], {
      encoding: "utf8",
    }).trim();
    return /^\d{4}-\d{2}-\d{2}$/.test(out) ? out : undefined;
  } catch {
    return undefined;
  }
}

function lastmodFor(path: string): string | undefined {
  const entry = ROUTE_SEO[path];
  for (const f of candidateFiles(path)) {
    if (!existsSync(f)) continue;
    const d = gitDate(f);
    if (d) return d;
  }
  return entry?.dateModified ?? entry?.datePublished;
}

const EXTRA_PATHS = [
  "/for",
  "/for/research",
  "/for/journalists",
  "/for/companies",
  "/for/investigators",
  "/for/analysts",
];
const urls = Array.from(new Set(sitemapPaths().concat(EXTRA_PATHS))).map((path) => {
  const lastmod = lastmodFor(path);
  return (
    `  <url>\n    <loc>${ORIGIN}${path}</loc>` + (lastmod ? `\n    <lastmod>${lastmod}</lastmod>` : "") + `\n  </url>`
  );
});

const xml = [
  `<?xml version="1.0" encoding="UTF-8"?>`,
  `<!-- Generated by scripts/generate-sitemap.ts from the public route list. -->`,
  `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">`,
  ...urls,
  `</urlset>`,
  ``,
].join("\n");

writeFileSync(resolve("public/sitemap.xml"), xml);
console.log(`sitemap.xml written (${urls.length} urls)`);
